import type { PoolQuestion } from "../question-pool"

export const PART1: PoolQuestion[] = [
  { q: { en: "If you could live in one season forever, which would it be?", "zh-TW": "如果只能活在一個季節裡，你選哪個？", ja: "一つの季節だけ永遠に過ごせるなら？" }, opts: [
    { s: { yang_deficient: 2, qi_stagnant: 1 }, en: "Winter — I crave the quiet. The cold doesn't bother me, it clears my head.", "zh-TW": "冬天 — 我渴望那種安靜。冷不困擾我，反而讓我清醒。", ja: "冬 — 静けさが欲しい。寒さは苦じゃない、頭がクリアになる" },
    { s: { yin_deficient: 1, damp_heat: 2 }, en: "Summer — I come alive when it's hot. Long days, high energy, let's go.", "zh-TW": "夏天 — 天熱我就活過來了。長長的白天、滿滿能量，出發。", ja: "夏 — 暑いと生き生きする。長い一日、エネルギー満タン、行こう" },
    { s: { qi_deficient: 2, blood_stasis: 1 }, en: "Autumn — the world slows down and I finally feel like I can breathe.", "zh-TW": "秋天 — 世界慢下來，我終於覺得可以好好呼吸了。", ja: "秋 — 世界がゆっくりして、ようやく深呼吸できる気がする" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Spring — but only the warm part. I need the sun to thaw me out.", "zh-TW": "春天 — 但只要溫暖的那段。我需要陽光把我融化。", ja: "春 — でも暖かい時期だけ。太陽に解凍してもらわないと" },
  ]},
  { q: { en: "Your perfect room temperature is...", "zh-TW": "你最舒服的室溫是...", ja: "あなたにとって快適な室温は..." }, opts: [
    { s: { yang_deficient: 3 }, en: "I'm the one who secretly turns the thermostat up. I'm always cold.", "zh-TW": "我會偷偷把暖氣調高。我永遠都在冷。", ja: "こっそり暖房を上げる人。いつも寒い" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Windows open, even in February. I run hot and I'm not sorry.", "zh-TW": "二月也開窗。我容易熱，我不道歉。", ja: "2月でも窓を開ける。暑がり、謝らない" },
    { s: { sensitive: 2, qi_deficient: 1 }, en: "It has to be exactly right — one degree off and my whole day is ruined.", "zh-TW": "一定要剛好——差一度就毀了我一整天。", ja: "ピッタリじゃなきゃ — 1度違うだけで1日台無し" },
    { s: { qi_stagnant: 2, phlegm_damp: 1 }, en: "I don't really care about temperature. I care about the draft on my neck.", "zh-TW": "我不太在意溫度。我在意的是脖子上的風。", ja: "温度は気にしない。首元の風が気になる" },
  ]},
  { q: { en: "How do you feel about air conditioning?", "zh-TW": "你對冷氣的看法是？", ja: "エアコンについてどう思う？" }, opts: [
    { s: { yang_deficient: 2, qi_stagnant: 1 }, en: "My nemesis. I bring a sweater everywhere, even in summer.", "zh-TW": "我的天敵。我到哪都帶外套，連夏天都帶。", ja: "天敵。夏でもどこにでもカーディガンを持っていく" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "My best friend. Point it directly at me and never turn it off.", "zh-TW": "我的摯友。對著我吹，永遠不要關。", ja: "親友。私に向けて、絶対に消さないで" },
    { s: { sensitive: 2, phlegm_damp: 1 }, en: "It dries my throat and makes my skin crawl. I can feel every vent.", "zh-TW": "它讓我喉嚨乾、皮膚不舒服。每個出風口我都能感覺到。", ja: "喉が乾くし肌がざわつく。吹き出し口が全部わかる" },
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "I don't love it, I don't hate it. I just forget it exists.", "zh-TW": "不喜歡也不討厭。我就是會忘記它的存在。", ja: "好きでも嫌いでもない。存在を忘れる" },
  ]},
  { q: { en: "Winter mornings, your first thought is...", "zh-TW": "冬天的早晨，你的第一個念頭是...", ja: "冬の朝、最初に思うことは..." }, opts: [
    { s: { qi_stagnant: 2, yang_deficient: 1 }, en: "Please don't make me leave this cocoon. The world can wait.", "zh-TW": "別讓我離開這個繭。世界可以等一下。", ja: "この繭から出さないで。世界は待てる" },
    { s: { qi_deficient: 3 }, en: "If I could just stay here for one more hour... okay, two... okay, forever.", "zh-TW": "如果我能再多躺一小時⋯好，兩小時⋯好，永遠。", ja: "あと1時間だけ...じゃ2時間...じゃ永遠に" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "My body is frozen but my brain's been running since 5 AM.", "zh-TW": "身體是冰的但腦袋從凌晨五點就開始跑了。", ja: "体は凍ってるけど脳は朝5時からフル回転" },
    { s: { yang_deficient: 2, damp_heat: 1 }, en: "Hot shower. Now. Everything else is negotiable.", "zh-TW": "熱水澡。現在。其他都可以商量。", ja: "熱いシャワー。今すぐ。他はなんでもいい" },
  ]},
  { q: { en: "When it rains, you feel...", "zh-TW": "下雨天，你覺得...", ja: "雨の日は..." }, opts: [
    { s: { damp_heat: 2, phlegm_damp: 1 }, en: "Disgusting. Everything sticks to me. My skin, my clothes, my mood.", "zh-TW": "噁心。所有東西都黏在我身上。皮膚、衣服、心情。", ja: "不快。全部がくっつく。肌、服、気分" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "It mirrors something inside me. I stand by the window and just... think.", "zh-TW": "它映照著我內心的什麼。我站在窗邊，然後就一直...想。", ja: "心の中の何かを映してる。窓辺に立ってただ...考える" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "It drops my body temperature by 10 degrees. I need a blanket and a soup.", "zh-TW": "它讓我的體溫降了十度。我需要被子和一碗湯。", ja: "体温が10度下がる。毛布とスープが必要" },
    { s: { sensitive: 2, blood_stasis: 1 }, en: "My knees know it's coming before the weather app does.", "zh-TW": "我的膝蓋比天氣APP更早知道要下雨了。", ja: "膝が天気アプリより先に雨を知ってる" },
  ]},
  { q: { en: "Your relationship with hot drinks is...", "zh-TW": "你跟熱飲的關係是...", ja: "温かい飲み物との関係は..." }, opts: [
    { s: { yang_deficient: 3 }, en: "Serious and committed. I drink everything hot. Ice is my enemy.", "zh-TW": "認真且忠誠的。我什麼都喝熱的。冰是我的敵人。", ja: "真剣で誠実。全部ホット。氷は敵" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "I don't trust people who don't drink iced coffee year-round.", "zh-TW": "我不相信全年不喝冰咖啡的人。", ja: "年中アイスコーヒーを飲まない人は信用できない" },
    { s: { qi_deficient: 2, qi_stagnant: 1 }, en: "I forget to drink water. I realize at 6 PM I've had nothing all day.", "zh-TW": "我忘記喝水。到傍晚六點才發現整天什麼都沒喝。", ja: "飲むの忘れる。18時に今日何も飲んでないことに気づく" },
    { s: { phlegm_damp: 2, sensitive: 1 }, en: "I drink things with flavor — juice, soda, bubble tea. Plain water is... fine, I guess.", "zh-TW": "我喝有味道的——果汁、汽水、珍奶。白開水嘛...也行啦。", ja: "味付きを飲む — ジュース、ソーダ、タピオカ。水は...まあいいか" },
  ]},
  { q: { en: "How do you sleep at night?", "zh-TW": "你晚上怎麼睡？", ja: "夜はどう寝てる？" }, opts: [
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Multiple blankets, curled into a tight ball, like a shrimp in armor.", "zh-TW": "蓋好幾條被子，蜷成一團，像穿盔甲的蝦子。", ja: "毛布を何枚もかけて、エビのように丸まる" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "One leg out, fan on, window cracked. Still too warm.", "zh-TW": "一條腿伸出來，電風扇開著，窗戶留縫。還是太熱。", ja: "片足が出て、扇風機ON、窓少し開け。まだ暑い" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "My body is tired but my mind decides 2 AM is brainstorming hour.", "zh-TW": "身體很累但腦袋覺得凌晨兩點是腦力激盪時間。", ja: "体は疲れてるのに脳は深夜2時がブレスト時間と決める" },
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "I sleep like a log. A log that somehow still wakes up exhausted.", "zh-TW": "我睡得像根木頭。一根莫名其妙醒來還是累的木頭。", ja: "丸太のように寝る。でも起きても疲れてる謎の丸太" },
  ]},
  { q: { en: "Rainy days make you feel...", "zh-TW": "下雨天讓你覺得...", ja: "雨の日だと..." }, opts: [
    { s: { damp_heat: 2, phlegm_damp: 1 }, en: "Heavy and slow. Like the air is made of wet cement.", "zh-TW": "沉重又遲鈍。空氣像濕水泥做的。", ja: "重だるい。空気が濡れたセメントみたい" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Like the sky finally understands what's going on inside my head.", "zh-TW": "天空終於懂了我腦袋裡在搞什麼。", ja: "空がようやく自分の頭の中を理解した気がする" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Colder, sleepier, and somehow more tired than when I woke up.", "zh-TW": "更冷、更困、不知道為什麼比起床時還累。", ja: "寒くなる、眠くなる、なぜか起きた時より疲れてる" },
    { s: { blood_stasis: 2, sensitive: 1 }, en: "Something shifts in my body — my joints know, my mood knows.", "zh-TW": "身體有什麼在變——關節知道，心情也知道。", ja: "体の中で何かが変わる — 関節がわかる、気分もわかる" },
  ]},
  { q: { en: "Your ideal shower temperature is...", "zh-TW": "你理想的洗澡水溫是...", ja: "理想のシャワー温度は..." }, opts: [
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Scalding hot, steam everywhere. It's a ritual, not a shower.", "zh-TW": "燙到冒煙的那種。這是儀式，不是洗澡。", ja: "熱湯、湯気だらけ。シャワーじゃない、儀式" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Cool or lukewarm. I step in already feeling overheated.", "zh-TW": "涼的或溫的。我進去的時候就已經覺得熱了。", ja: "涼しいかぬるめ。入る時点で暑い" },
    { s: { sensitive: 2, blood_stasis: 1 }, en: "Exactly right. My skin protests if the temperature moves even slightly.", "zh-TW": "剛好。水溫偏一點點皮膚就抗議。", ja: "ピッタリ。温度が少しでもズレると肌が抗議" },
    { s: { qi_stagnant: 2, phlegm_damp: 1 }, en: "Hot, but I spend the whole time thinking about my life.", "zh-TW": "熱的，但我整個過程都在想人生。", ja: "熱い、でもずっと人生について考えてる" },
  ]},
  { q: { en: "You open the window because...", "zh-TW": "你打開窗戶是因為...", ja: "窓を開ける理由は..." }, opts: [
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "The room is suffocating. I need air NOW or I'll lose it.", "zh-TW": "房間讓我窒息。我需要空氣，現在，不然我要瘋了。", ja: "部屋が窒息しそう。今すぐ空気が欲しい、じゃないとヤバい" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Only in summer. Only if it's warm. Otherwise the draft goes straight to my bones.", "zh-TW": "只有夏天。只有暖的時候。不然冷風直接灌進骨頭。", ja: "夏だけ。暖かい時だけ。じゃないと冷気が骨まで行く" },
    { s: { sensitive: 2, phlegm_damp: 1 }, en: "Carefully. One crack. Pollen, dust, and temperature shocks are all real threats.", "zh-TW": "小心地。開一條縫。花粉、灰塵、溫差都是真實的威脅。", ja: "慎重に。少しの隙間。花粉、埃、温度差は全部本物の脅威" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "I leave it open. I don't think about it. Fresh air is free.", "zh-TW": "就開著啊。沒想那麼多。新鮮空氣又不要錢。", ja: "開けっぱ。考えない。新鮮な空気はタダだし" },
  ]},
  { q: { en: "Summer nights, you're...", "zh-TW": "夏天的晚上，你是...", ja: "夏の夜、あなたは..." }, opts: [
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Still reaching for a blanket. I run cold year-round and I'm proud of it.", "zh-TW": "還是在找被子。我全年都怕冷，我驕傲。", ja: "まだ毛布を探してる。年中寒がり、誇りに思う" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "A human furnace. Sheets off, fan on, still sweating.", "zh-TW": "人形暖爐。被子踢掉、風扇開著、還是在流汗。", ja: "人間ヒーター。布団蹴って、扇風機つけて、まだ汗" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "Lying awake, replaying a conversation from 2019 for absolutely no reason.", "zh-TW": "躺在那裡，毫無理由地重播2019年的一次對話。", ja: "目覚めて横たわり、理由もなく2019年の会話をリプレイ" },
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "Asleep. Deeply. I could sleep through a fire alarm.", "zh-TW": "睡死了。深度睡眠。火災警報我都聽不到。", ja: "爆睡。深く。火災報知器も聞こえない" },
  ]},
  { q: { en: "Your hands and feet are usually...", "zh-TW": "你的手腳通常是...", ja: "手足はいつも..." }, opts: [
    { s: { yang_deficient: 3 }, en: "Ice blocks. My partner screams when I touch them. Year-round.", "zh-TW": "冰塊。我碰人的時候對方會尖叫。全年無休。", ja: "氷塊。触ると相手が叫ぶ。年中無休" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "Warm to hot. I'm the one who doesn't need gloves, ever.", "zh-TW": "偏熱。我是那種永遠不需要手套的人。", ja: "温かい〜熱い。手袋不要の人" },
    { s: { blood_stasis: 2, sensitive: 1 }, en: "Sometimes they tingle or go numb for no reason. Or turn purple-ish.", "zh-TW": "有時會無故發麻或刺痛。或者變紫。", ja: "時々理由なくしびれる。または紫になる" },
    { s: { qi_stagnant: 2, qi_deficient: 1 }, en: "Clammy. Especially when I'm nervous, which is often.", "zh-TW": "濕濕冷冷的。特別是緊張的時候，而我常常在緊張。", ja: "湿って冷たい。特に緊張時、よく緊張する" },
  ]},
  { q: { en: "Your energy at 3 PM is like...", "zh-TW": "下午三點你的能量像...", ja: "午後3時のエネルギーは..." }, opts: [
    { s: { qi_deficient: 3 }, en: "A phone at 3%. I'm in power-saving mode and everything hurts.", "zh-TW": "3%電量的手機。省電模式中，什麼都累。", ja: "バッテリー3%のスマホ。省電力モード、全部しんどい" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "A sudden wave of heat hits — I need to step out or I'll combust.", "zh-TW": "突然一陣熱浪——我需要出去，不然會自燃。", ja: "突然の熱波 — 外に出ないと自然発火しそう" },
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "Everything annoys me. The sound of someone chewing. The air. Existence.", "zh-TW": "所有事都煩。別人咀嚼的聲音。空氣。活著這件事。", ja: "全部イライラ。誰かの咀嚼音。空気。存在そのもの" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "I've been in a fog since 1 PM and I don't see it lifting.", "zh-TW": "從下午一點就開始霧茫茫的，看不到盡頭。", ja: "13時から霧の中にいて、晴れる気配がない" },
  ]},
  { q: { en: "After a full night's sleep, you feel...", "zh-TW": "睡了一整晚之後，你覺得...", ja: "十分寝た後、あなたは..." }, opts: [
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "Still tired. I could sleep another full night and still want more.", "zh-TW": "還是累。我可以再睡一整晚然後還想要更多。", ja: "まだ眠い。もう一晩寝てもまだ欲しい" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "My body rested but my brain's been running calculations since 4 AM.", "zh-TW": "身體休息了但腦袋從凌晨四點就開始運算。", ja: "体は休まったけど脳は朝4時から計算してる" },
    { s: { yang_deficient: 2, blood_stasis: 1 }, en: "It takes two hours, a hot drink, and sunlight before I feel human.", "zh-TW": "需要兩小時、一杯熱飲、和陽光才能覺得自己是個人。", ja: "2時間と温かい飲み物と日光が必要でやっと人間になれる" },
    { s: { damp_heat: 2, balanced: 1 }, en: "Actually pretty good. But by 2 PM I'll be running on fumes again.", "zh-TW": "其實還不錯。但到下午兩點又會沒電。", ja: "実はけっこういい感じ。でも14時にはまたガス欠" },
  ]},
  { q: { en: "Your battery recharges by...", "zh-TW": "你的電池靠什麼充電...", ja: "バッテリーの充電方法は..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Sleep. Period. Everything else is a nice idea but sleep is the only thing that works.", "zh-TW": "睡覺。就這樣。其他都只是好聽的話，只有睡覺有用。", ja: "睡眠。それだけ。他はいい考えだけど睡眠だけが効く" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Being alone with my thoughts. Music, a book, silence. People drain me.", "zh-TW": "獨處思考。音樂、一本書、安靜。人讓我耗竭。", ja: "一人で考える時間。音楽、本、静寂。人が消耗する" },
    { s: { damp_heat: 2 }, en: "Doing something intense — workout, dance, run. I need to burn to recharge.", "zh-TW": "做點激烈的——健身、跳舞、跑步。我需要燃燒才能充電。", ja: "激しいことをする — 筋トレ、ダンス、ランニング。燃焼が必要" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Eating something warm and lying down. Preferably under a weighted blanket.", "zh-TW": "吃點熱的然後躺下。最好在重力毯下面。", ja: "温かいものを食べて横になる。できれば加重ブランケットの下で" },
  ]},
  { q: { en: "How many hours of sleep do you actually need?", "zh-TW": "你實際上需要多少小時的睡眠？", ja: "実際何時間の睡眠が必要？" }, opts: [
    { s: { qi_deficient: 2, phlegm_damp: 2 }, en: "Don't ask. It's embarrassing. And I still wake up tired.", "zh-TW": "別問。很丟臉。而且醒來還是累。", ja: "聞かないで。恥ずかしい。起きてもまだ眠い" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "6 hours of sleep + 4 hours of lying awake thinking. So technically 10 hours in bed.", "zh-TW": "6小時睡覺 + 4小時躺著想事情。所以技術上在床上10小時。", ja: "睡眠6時間 + いろいろ考えながら横たわる4時間。ベッドには技術的に10時間" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "At least 8, ideally 9, wrapped up warm. Any less and I'm not a person.", "zh-TW": "至少8，最好9，包得暖暖的。少於這個我做人不完整。", ja: "最低8、理想9、温かく包まって。これ以下だと人間じゃない" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "I can function on 5-6. I don't love it, but I push through.", "zh-TW": "5-6小時也能撐。我不喜歡，但我硬扛。", ja: "5-6時間で動ける。好きじゃないけど押し切る" },
  ]},
  { q: { en: "After a long day, you...", "zh-TW": "漫長的一天後，你...", ja: "長い1日の後..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Collapse onto the nearest soft surface. Brain off. Body off. Done.", "zh-TW": "倒在最近的柔軟表面上。腦袋關機。身體關機。結束。", ja: "一番近い柔らかいところに倒れ込む。脳オフ。体オフ。終わり" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Get a mysterious second wind at 10 PM. My body doesn't know how to shut down.", "zh-TW": "晚上十點莫名其妙又活過來了。身體不知道怎麼關機。", ja: "22時に謎の第二の風。体のシャットダウン方法を知らない" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "Scroll my phone and mentally replay everything I said today. Was that weird?", "zh-TW": "滑手機然後在腦中重播今天說過的每句話。那樣會不會很怪？", ja: "スマホを見て今日言ったことを全再生。あれ変だったかな？" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Still going. I'll crash eventually, but right now I'm running on spite.", "zh-TW": "還在跑。最後會垮掉，但現在靠意志力撐著。", ja: "まだ動いてる。いつかバテる、でも今は意地で動いてる" },
  ]},
  { q: { en: "Your ideal weekend involves...", "zh-TW": "你的理想週末包含...", ja: "理想の週末は..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Nothing. No plans. Zero human interaction. Maybe a nap. Maybe three.", "zh-TW": "沒有。沒計畫。零社交。可能小睡。可能睡三次。", ja: "なし。予定なし。人との接触ゼロ。昼寝するかも。3回するかも" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Solo time is sacred. I need it to think, create, or just exist in silence.", "zh-TW": "獨處是神聖的。我需要它來思考、創造、或者只是安靜地存在。", ja: "一人の時間は神聖。考える、創る、ただ静かに存在するために必要" },
    { s: { damp_heat: 2, balanced: 1 }, en: "Packed schedule. Brunch, hiking, drinks. If I'm home by midnight I failed.", "zh-TW": "滿滿的行程。早午餐、爬山、喝酒。半夜前到家算我輸。", ja: "予定満載。ブランチ、ハイキング、飲み。深夜帰りなら負け" },
    { s: { phlegm_damp: 2, blood_stasis: 1 }, en: "Comfort food, comfort shows, comfortable clothes. The trifecta.", "zh-TW": "療癒食物、療癒劇集、舒服的衣服。三合一。", ja: "慰めの食べ物、好きな番組、楽な服。三位一体" },
  ]},
  { q: { en: "When you're tired, you...", "zh-TW": "你累的時候，你...", ja: "疲れた時..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Shut down completely. I can't pretend. My face says it all.", "zh-TW": "完全關機。我裝不了。我的臉會說話。", ja: "完全シャットダウン。誤魔化せない。顔が全部語ってる" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "Push through with caffeine and spite. I'll deal with the crash later.", "zh-TW": "用咖啡因和怨念撐過去。崩潰的事之後再說。", ja: "カフェインと意地で押し切る。バテるのは後で対処" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "Get irritable and take everything personally. Every. Little. Thing.", "zh-TW": "變得易怒然後把所有事都當成針對我。每。一。件。", ja: "イライラして全部自分に向けられてる気がする。全。部。" },
    { s: { phlegm_damp: 2, blood_stasis: 1 }, en: "Feel heavy, like I'm moving through soup. Everything slows down.", "zh-TW": "覺得沉重，像在湯裡移動。一切都慢下來。", ja: "重く感じる、スープの中を動いてるみたい。すべてが遅くなる" },
  ]},
  { q: { en: "You can focus for how long?", "zh-TW": "你能專注多久？", ja: "集中力はどれくらい？" }, opts: [
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "45 minutes, tops. Then my brain is soup and I need to lie down.", "zh-TW": "最多45分鐘。然後腦袋變成糊，需要躺下。", ja: "せいぜい45分。その後脳がスープになって横になりたい" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "Terrible during the day, laser-focused at 11 PM. My brain has a timezone.", "zh-TW": "白天超爛，晚上11點像雷射一樣。我的腦袋有時區的。", ja: "昼はダメ、23時にレーザー集中。脳に時 zone がある" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Short, explosive bursts of productivity. Then I'm useless for an hour.", "zh-TW": "短暫爆發性的生產力。然後廢掉一小時。", ja: "短時間で爆発的な生産性。その後1時間機能不全" },
    { s: { qi_stagnant: 2, yang_deficient: 1 }, en: "I can focus, but only on things I care about. Everything else is noise.", "zh-TW": "我可以專注，但只在我在乎的事上。其他都是噪音。", ja: "集中できる、でも気になることだけ。他はノイズ" },
  ]},
  { q: { en: "After exercise, you feel...", "zh-TW": "運動後，你覺得...", ja: "運動後は..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Destroyed. I need a full day to recover. Was it worth it? Debatable.", "zh-TW": "被摧毀了。我需要一整天來恢復。值得嗎？有待商榷。", ja: "破壊された。丸1日回復が必要。価値あった？議論の余地あり" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Overheated and flushed for an hour. But kind of great?", "zh-TW": "過熱又臉紅了一小時。但有點爽？", ja: "1時間オーバーヒートで赤くなる。でもちょっと気持ちいい？" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Heavy and slow, like I'm wearing a lead suit. But I know I need it.", "zh-TW": "沉重又遲鈍，像穿了一件鉛衣。但我知道我需要它。", ja: "重だるい、鉛の服を着てるみたい。でも必要なのはわかる" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Amazing. I want more. When's the next session?", "zh-TW": "超讚。我還要。下一次什麼時候？", ja: "最高。もっと欲しい。次いつ？" },
  ]},
  { q: { en: "Your morning routine is...", "zh-TW": "你的早晨習慣是...", ja: "朝のルーティンは..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Snooze × 3, drag myself to the kettle, stare at the wall for 15 minutes.", "zh-TW": "貪睡三次，拖著身體去燒水，盯著牆壁發呆15分鐘。", ja: "スヌーズ×3、ケトルへ這って、壁を15分見つめる" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "Coffee first. Then more coffee. I'll feel alive by noon.", "zh-TW": "先咖啡。然後更多咖啡。中午我才會覺得活著。", ja: "まずコーヒー。そしてもっとコーヒー。正午にやっと実感" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Cold shower, loud music, out the door. I don't ease into the day, I attack it.", "zh-TW": "冷水澡、大聲音樂、出門。我不會慢慢進入狀態，我直接開戰。", ja: "冷水シャワー、大音量、出発。ゆっくり始めない、アタックする" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Hot tea, warm shower, sit in the sun. I need 30 minutes of warmth to function.", "zh-TW": "熱茶、熱水澡、坐在陽光下。我需要30分鐘的溫暖才能運作。", ja: "ホットティー、温かいシャワー、日向ぼっこ。30分の温もりが必要" },
  ]},
  { q: { en: "You've been called lazy...", "zh-TW": "你被說過懶嗎...", ja: "ズルいと言われたこと..." }, opts: [
    { s: { qi_deficient: 3 }, en: "More times than I can count. I'm not lazy, I'm running on empty.", "zh-TW": "多到數不清。我不是懶，我是電量為零。", ja: "数えきれない。ズルじゃない、バッテリーゼロ" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Not lazy — selectively energetic. I just choose where to spend my energy.", "zh-TW": "不是懶——是選擇性有活力。我只是選擇把能量花在哪。", ja: "ズルじゃない — 選択的エネルギー。使う場所を選んでるだけ" },
    { s: { damp_heat: 2 }, en: "Never. If anything, people tell me to slow down. I don't know how.", "zh-TW": "從來沒有。別人反而叫我慢下來。我不知道怎麼慢。", ja: "ない。むしろゆっくりしろと言われる。ゆっくりする方法がわからない" },
    { s: { yang_deficient: 2, phlegm_damp: 1 }, en: "I conserve energy. It's not laziness, it's efficiency. I know my limits.", "zh-TW": "我在保存能量。不是懶，是效率。我知道自己的極限。", ja: "エネルギーを節約してる。ズルじゃない、効率。限界を知ってる" },
  ]},
  { q: { en: "Your energy compared to your friends is...", "zh-TW": "跟朋友比，你的能量...", ja: "友達よりエネルギーは..." }, opts: [
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "Noticeably lower. They want to go out and I want to go home.", "zh-TW": "明顯低很多。他們想出門，我想回家。", ja: "明らかに低い。みんな出かけたい、私は帰りたい" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "I'm the group's engine. If I stop, everything stops.", "zh-TW": "我是團隊的引擎。我停了，一切就停。", ja: "グループのエンジン。私が止まると全部止まる" },
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "Different frequency. I spend mine on thinking, not doing.", "zh-TW": "不同的頻率。我把能量花在思考，不是行動。", ja: "周波数が違う。思考に使う、行動には使わない" },
    { s: { yang_deficient: 2, sensitive: 1 }, en: "Variable. Some days I can keep up, some days I need to recharge alone.", "zh-TW": "不穩定。有時候跟得上，有時候需要獨自充電。", ja: "変動的。ついていける日もあれば一人で充電が必要な日も" },
  ]},
  { q: { en: "Your plans get cancelled at the last minute. You feel...", "zh-TW": "臨時被取消計畫。你覺得...", ja: "直前で予定がキャンセル。あなたは..." }, opts: [
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Relief. Pure, undiluted relief. I'm already reaching for my book.", "zh-TW": "鬆了一口氣。純粹的、百分百的放鬆。我已經在拿書了。", ja: "ホッとした。純粋な、混じりけない安堵。すでに本を手に取ってる" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "A little guilty... but mostly grateful. My body needed this.", "zh-TW": "有點內疚...但主要是感恩。我的身體需要這個。", ja: "ちょっと罪悪感...でも主に感謝。体がこれを必要としてた" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Instantly texting the backup plan crew. The night is still young.", "zh-TW": "立刻發訊息給備用計畫的人。夜晚還很長。", ja: "すぐに予備メンバーに連絡。夜はまだ始まったばかり" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "Relieved... then anxious that they'll reschedule and I'll have to go.", "zh-TW": "鬆一口氣...然後焦慮他們會改期然後我又得去。", ja: "ホッとする...でも再予約されて行かなきゃいけなくなる不安" },
  ]},
  { q: { en: "In a group, you're usually...", "zh-TW": "在群體中，你通常是...", ja: "グループの中では..." }, opts: [
    { s: { phlegm_damp: 2, sensitive: 1 }, en: "The cozy anchor — I brought the snacks, picked the playlist, and I'm making sure everyone's warm enough.", "zh-TW": "溫暖的定海神針 — 我帶了零食、選了歌單，還在確認每個人夠不夠暖。", ja: "居場所の錨 — お菓子持参、プレイリスト選曲、みんなが温かいかまで気遣う" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "The quiet observer — I remember everything everyone says. It's a gift and a curse.", "zh-TW": "安靜的觀察者 — 我記得每個人說過的每句話。這是天賦也是詛咒。", ja: "静かな観察者 — みんなの発言を全部覚えてる。才能であり呪い" },
    { s: { damp_heat: 2 }, en: "The chaos engine — I know everyone's name, their dog's name, and their birth chart by midnight.", "zh-TW": "混亂引擎 — 到午夜我已經知道每個人的名字、他們狗的名字、和他們的星盤。", ja: "カオスエンジン — 深夜までに全員の名前、犬の名前、星座を把握する" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "The one who mentally left 20 minutes ago but is still physically sitting here, smiling.", "zh-TW": "那個20分鐘前靈魂已經離開但身體還在這裡微笑的人。", ja: "20分前に精神的には帰ったのに、体だけここで笑ってる人" },
  ]},
  { q: { en: "When someone says 'let's hang out'...", "zh-TW": "有人說「出來玩啊」...", ja: "「遊ぼう」と言われたら..." }, opts: [
    { s: { damp_heat: 2 }, en: "YES. Where are we going? I'm already putting shoes on.", "zh-TW": "好！去哪？我已經在穿鞋了。", ja: "行く行く！どこ？もう靴履いてる" },
    { s: { blood_stasis: 2, qi_stagnant: 1 }, en: "Depends on my mood. Sometimes I'm the first to say yes, sometimes I've already invented three excuses.", "zh-TW": "看心情。有時我第一個說好，有時已經編好三個理由了。", ja: "気分次第。即OKの時もあれば、言い訳を3つ用意してる時もある" },
    { s: { qi_stagnant: 2, qi_deficient: 1 }, en: "I run a full cost-benefit analysis in my head. Will there be a bathroom I can hide in?", "zh-TW": "腦中進行完整的成本效益分析。那裡有我可以躲的廁所嗎？", ja: "頭の中で費用便益分析。隠れられるトイレはある？" },
    { s: { yang_deficient: 2 }, en: "Only if it's somewhere warm, close to home, and I can wear sweatpants.", "zh-TW": "只有暖和、離家近、而且可以穿運動褲的地方才行。", ja: "温かくて家の近くで、スウェットで行ける場所だけ" },
  ]},
  { q: { en: "You get a text at 10 PM...", "zh-TW": "晚上十點收到訊息...", ja: "夜10時にメッセージが..." }, opts: [
    { s: { qi_stagnant: 2, damp_heat: 1 }, en: "I draft it, delete it, redraft it, stare at it, then send something totally different.", "zh-TW": "打了又刪、刪了又打、盯著看了半天，最後發了完全不同的內容。", ja: "書いて消して、書き直して、見つめて、全然違う内容を送る" },
    { s: { damp_heat: 2, yang_deficient: 1 }, en: "I reply with a voice note or I just call. Why type when you can talk?", "zh-TW": "我會回語音訊息或直接打電話。能說話幹嘛打字？", ja: "ボイスメモか電話で返す。話せるのに何でタイピングするの？" },
    { s: { yin_deficient: 2 }, en: "If I'm awake, I'm texting back immediately. My brain doesn't have a 'wait' function.", "zh-TW": "如果我醒著，我立刻回。我的大腦沒有「等一下」的功能。", ja: "起きてれば即レス。脳に「待つ」機能がない" },
    { s: { qi_deficient: 2 }, en: "I see it. I'll reply tomorrow. No guilt, no explanation, just vibes.", "zh-TW": "我看到了。明天再回。沒有罪惡感、不解釋、就是這樣。", ja: "見た。返信は明日。罪悪感なし、説明なし、ただバイブスで" },
  ]},
  { q: { en: "Your social battery lasts...", "zh-TW": "你的社交電池能撐...", ja: "社交バッテリーはどれくらい持つ？" }, opts: [
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "About 2 hours. Then I start looking at exit routes like I'm in a spy movie.", "zh-TW": "大約2小時。然後我開始像間諜電影一樣找逃生路線。", ja: "約2時間。その後スパイ映画みたいに脱出ルートを探し始める" },
    { s: { sensitive: 2, phlegm_damp: 1 }, en: "I can fake it for hours. But tomorrow I'm cancelling everything to recover.", "zh-TW": "我可以假裝好幾個小時。但明天我會取消所有計畫來恢復。", ja: "何時間も偽装できる。でも明日は回復のために全予定キャンセル" },
    { s: { damp_heat: 2 }, en: "All night. I'm the last one standing and I'm already planning the afterparty.", "zh-TW": "整晚。我是最後一個還站的，而且我已經在規劃續攤了。", ja: "オールナイト。最後まで立ってて、すでに二次会を計画中" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "I prefer one-on-one. Groups make me feel like a TV on with no signal.", "zh-TW": "我偏好一對一。群體讓我像一台沒有訊號的電視。", ja: "1対1がいい。グループだと砂嵐のテレビみたいになる" },
  ]},
  { q: { en: "At a party, you're...", "zh-TW": "在派對上，你是...", ja: "パーティーでは..." }, opts: [
    { s: { damp_heat: 2 }, en: "Talking to everyone, probably holding a drink, definitely the loudest laugh in the room.", "zh-TW": "跟每個人聊天，手裡可能拿杯酒，絕對是全場笑最大聲的那個。", ja: "みんなと話してる、たぶん飲み物持ち、確実に部屋で一番笑ってる" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "In a corner, having a deep conversation with one person about their childhood trauma.", "zh-TW": "在角落，跟一個人深入聊他的童年創傷。", ja: "隅っこで、誰か一人と幼少期のトラウマについて深く語ってる" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "By the food table. The snacks are the only ones who truly understand me.", "zh-TW": "在食物桌旁。零食是唯一真正懂我的存在。", ja: "食べ物テーブルのそば。お菓子だけが本当に私を理解してる" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Calculating the earliest socially acceptable time to leave. The clock is my enemy.", "zh-TW": "在計算社會能接受的最早離開時間。時鐘是我的敵人。", ja: "社会的に許される最も早い帰宅時間を計算中。時計は敵" },
  ]},
  { q: { en: "When you're stressed, you...", "zh-TW": "壓力大的時候，你...", ja: "ストレスがかかると..." }, opts: [
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "I withdraw into my shell. I need silence like I need oxygen.", "zh-TW": "我縮回我的殼裡。我需要安靜，像需要氧氣一樣。", ja: "殻に閉じこもる。酸素みたいに静けさが必要" },
    { s: { damp_heat: 2 }, en: "I vent. Loudly. To anyone who'll listen. My group chat has seen things.", "zh-TW": "我發洩。大聲地。對任何願意聽的人。我的群組看過不該看的。", ja: "発散する。大声で。聞いてくれる人に。グループチャットが修羅場" },
    { s: { yang_deficient: 2, sensitive: 1 }, en: "I need warmth — hot tea, a bath, my bed. Stress literally makes me feel cold inside.", "zh-TW": "我需要溫暖 — 熱茶、泡澡、我的床。壓力真的讓我從裡面冷出來。", ja: "温もりが必要 — ホットティー、お風呂、ベッド。ストレスで文字通り内側から寒くなる" },
    { s: { qi_deficient: 2 }, en: "I shut down. My body treats stress like a software update — everything freezes.", "zh-TW": "我當機。身體把壓力當成軟體更新 — 一切凍結。", ja: "シャットダウン。体がストレスをアップデート扱い — 全部フリーズ" },
  ]},
  { q: { en: "Your phone is...", "zh-TW": "你的手機是...", ja: "スマホは..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "Full of unread messages. I'll get to them... eventually. Maybe. Possibly never.", "zh-TW": "充滿未讀訊息。我會回的⋯之後。可能。也許永遠不會。", ja: "未読メッセージで溢れてる。そのうち...多分。たぶん永遠に" },
    { s: { blood_stasis: 2, sensitive: 1 }, en: "My screen time report is a horror movie. I've stopped looking at it out of self-preservation.", "zh-TW": "我的螢幕使用時間報告是恐怖片。為了自保我已經不敢看了。", ja: "スクリーンタイムレポートはホラー映画。自己防衛のため見るのをやめた" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "Blowing up. I'm in 5 group chats, all active, and I'm the one keeping them alive.", "zh-TW": "訊息爆炸。我在5個群組裡，全部活躍，而且我是維持它們生命的那個人。", ja: "爆発中。5つのグループチャットにいて、全部活発で、私が生かしてる" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "On silent. Do Not Disturb is my lifestyle. My ringtone hasn't been on since 2019.", "zh-TW": "靜音。勿擾模式是我的生活方式。我的鈴聲從2019年就沒開過。", ja: "マナーモード。DNDはライフスタイル。着信音は2019年からオフ" },
  ]},
  { q: { en: "You're described as...", "zh-TW": "別人形容你是...", ja: "あなたはこう言われる..." }, opts: [
    { s: { damp_heat: 2 }, en: "Intense and passionate — I have two speeds: off and absolutely unhinged.", "zh-TW": "強烈又熱情 — 我只有兩個檔：關機和完全暴走。", ja: "激しく情熱的 — オンか暴走かの2段階しかない" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Deep and thoughtful — I feel everything inside and process it for approximately 3-7 business days.", "zh-TW": "深刻又深思 — 我把一切放在心裡，大約需要3到7個工作天來消化。", ja: "深く思慮深い — 全部内面で感じて、処理に3〜7営業日かかる" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Chill and unbothered — I've mastered the art of looking calm. (Inside? Screaming.)", "zh-TW": "佛系又無所謂 — 我精通看起來很平靜的藝術。（內心？在尖叫。）", ja: "穏やかで動じない — 冷静に見える術を極めた。（中身？叫んでる。）" },
    { s: { sensitive: 2, qi_deficient: 1 }, en: "Perceptive and careful — I notice what others miss. I also overthink what others forget.", "zh-TW": "敏銳又謹慎 — 我注意到別人忽略的。我也過度思考別人早就忘記的。", ja: "鋭く慎重 — 他人が見逃すことに気づく。他人が忘れたことも考えすぎる" },
  ]},
  { q: { en: "You're ordering comfort food. What sounds right?", "zh-TW": "你想點一份療癒食物，你選...", ja: "慰めの食べ物を頼むなら..." }, opts: [
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Something warm and soupy — stew, ramen, congee. If it doesn't steam, I don't want it.", "zh-TW": "溫熱湯類 — 燉湯、拉麵、粥。如果不冒煙我不要。", ja: "温かいスープ系 — シチュー、ラーメン、お粥。湯気がなきゃいらない" },
    { s: { yin_deficient: 1, damp_heat: 2 }, en: "Something fresh and light — salads, ceviche, cold noodles. Heavy food is a personal attack.", "zh-TW": "清爽輕食 — 沙拉、生魚片、涼麵。重食是對我的攻擊。", ja: "さっぱり軽く — サラダ、カルパッチョ、冷麺。重いものは攻撃" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Something sweet and filling — pasta, curry, rice bowls. Carbs are my love language.", "zh-TW": "甜蜜飽足 — 義大利麵、咖哩、丼飯。碳水化合物是我的愛之語。", ja: "甘くて満足 — パスタ、カレー、丼もの。炭水化物は愛の言語" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Something with a kick — spicy, bold, intense flavors. Bland food is a waste of a meal.", "zh-TW": "重口味 — 辣的、大膽的、濃烈的風味。清淡的食物是在浪費一餐。", ja: "刺激的 — 辛い、大胆、強烈な味。薄味は食事の無駄遣い" },
  ]},
  { q: { en: "Your relationship with breakfast is...", "zh-TW": "你跟早餐的關係是...", ja: "朝食との関係は..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Essential. Without it I'm a glitchy robot running on yesterday's battery.", "zh-TW": "必須的。沒有早餐我是一個用昨天電量運作的故障機器人。", ja: "必須。朝食なきゃ昨日のバッテリーで動く故障ロボット" },
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "I think about breakfast, then I think about everything else, then suddenly it's lunch.", "zh-TW": "我想著早餐，然後想著別的，然後突然就午餐了。", ja: "朝食を考え、次に別のことを考え、気づけば昼食" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "Coffee IS my breakfast. Don't judge me. The caffeine enters my bloodstream before my eyes open.", "zh-TW": "咖啡就是我的早餐。別評判我。咖啡因在我睜眼之前就進入血液了。", ja: "コーヒーが朝食。批判しないで。目が開く前にカフェインが血管に入る" },
    { s: { phlegm_damp: 2 }, en: "I could eat breakfast all day. Brunch is my religion. I will fight for the buffet.", "zh-TW": "我可以整天吃早餐。早午餐是我的信仰。我會為自助餐而戰。", ja: "朝食を1日中食べられる。ブランチは私の宗教。ビュッフェのために戦う" },
  ]},
  { q: { en: "After a heavy meal you feel...", "zh-TW": "吃太飽後你覺得...", ja: "食べすぎた後は..." }, opts: [
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Bloated and sluggish. I need a nap and possibly a formal apology from the food.", "zh-TW": "脹脹的、沉甸甸的。我想睡覺，而且可能需要食物給我一個正式道歉。", ja: "膨満感とだるさ。寝たいし、食べ物から正式な謝罪が必要かも" },
    { s: { yang_deficient: 2, qi_stagnant: 1 }, en: "Warm and cozy — like I've been wrapped in a heated blanket from the inside. Bliss.", "zh-TW": "溫暖又舒適 — 像從裡面被裹上電熱毯。幸福。", ja: "温かく心地よい — 内側から電気毛布に包まれたみたい。至福" },
    { s: { damp_heat: 2 }, en: "Too full, too warm, sweating slightly. I did this to myself and I'd do it again.", "zh-TW": "太撐、太熱、微微出汗。這是我自找的，但我還會再做。", ja: "食べすぎ、暑い、少し汗。自業自得、でもまたやる" },
    { s: { yin_deficient: 2 }, en: "Thirsty and overheated — I'm already reaching for something iced. My body is a furnace.", "zh-TW": "口渴又過熱 — 我已經在拿冰的東西了。我的身體是個火爐。", ja: "喉が渇いてオーバーヒート — もう冷たいものを探してる。体が炉みたい" },
  ]},
  { q: { en: "Your water drinking habit is...", "zh-TW": "你喝水的習慣是...", ja: "水を飲む習慣は..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "I forget water exists until 6 PM, then I chug a liter like I'm crossing the Sahara.", "zh-TW": "我忘記水的存在直到傍晚六點，然後像穿越撒哈拉一樣灌一公升。", ja: "18時まで水の存在を忘れ、サハラ横断みたいに1リットル一気飲み" },
    { s: { yin_deficient: 2 }, en: "Constantly sipping — my mouth is always dry. I have a water bottle surgically attached to my hand.", "zh-TW": "一直在啜飲 — 我的嘴巴永遠是乾的。水瓶已經跟我的手長在一起了。", ja: "常に飲んでる — 口がいつも乾く。水ボトルは手に埋め込まれてる" },
    { s: { sensitive: 2, damp_heat: 1 }, en: "Only room temperature or warm. Cold water is a personal attack on my entire digestive system.", "zh-TW": "只喝常溫或溫的。冰水是對我整個消化系統的攻擊。", ja: "常温か温かいものだけ。冷水は消化器系への攻撃" },
    { s: { phlegm_damp: 2, damp_heat: 1 }, en: "I drink flavored stuff — juice, soda, bubble tea. Plain water and I have a purely professional relationship.", "zh-TW": "我喝有味道的 — 果汁、汽水、珍奶。白開水跟我只有純粹的職業關係。", ja: "味付きを飲む — ジュース、ソーダ、タピオカ。水とは業務関係のみ" },
  ]},
  { q: { en: "When you're stressed, you eat...", "zh-TW": "壓力大的時候你吃...", ja: "ストレス時に食べるもの..." }, opts: [
    { s: { damp_heat: 2, phlegm_damp: 1 }, en: "I eat everything in sight. My stress coping mechanism is called 'the entire fridge.'", "zh-TW": "我看什麼吃什麼。我的壓力應對機制叫「整個冰箱」。", ja: "目に入るもの全部食べる。ストレス対処法は『冷蔵庫まるごと』" },
    { s: { qi_stagnant: 2 }, en: "I lose my appetite completely. Food becomes a concept, not a necessity.", "zh-TW": "我完全失去食慾。食物變成一個概念，不是必需品。", ja: "食欲が完全に消える。食べ物が概念になる、必需品じゃなくなる" },
    { s: { yang_deficient: 2, sensitive: 1 }, en: "I crave warmth — hot chocolate, soup, toast. Anything that feels like a hug from the inside.", "zh-TW": "我渴望溫暖 — 熱可可、湯、吐司。任何像從裡面擁抱我的東西。", ja: "温もりが欲しい — ホットココア、スープ、トースト。内側からのハグみたいなもの" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "I crave warm, comforting food. Stress makes my stomach demand a peace offering.", "zh-TW": "我渴望溫暖、療癒的食物。壓力讓我的胃要求一個求和供品。", ja: "温かい、慰める食べ物が欲しい。ストレスで胃が供物を要求する" },
  ]},
  { q: { en: "Your ideal snack is...", "zh-TW": "你的理想零食是...", ja: "理想のおやつは..." }, opts: [
    { s: { damp_heat: 2 }, en: "Something spicy. I crave heat like it's a personality trait. Sriracha is my emotional support condiment.", "zh-TW": "辣的東西。我渴望熱度像是人格特質。辣椒醬是我的情緒支援調味料。", ja: "辛いもの。熱を求めるのは性格。スリラチャは心の付き添い調味料" },
    { s: { yin_deficient: 2 }, en: "Fruit. Something cool and refreshing. I want to feel like I'm eating a mountain stream.", "zh-TW": "水果。涼涼的、清爽的。我想感受像在吃山泉水的感覺。", ja: "果物。涼しくてさっぱり。渓流を食べてる感覚がいい" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Carbs. Bread, cookies, anything baked. I don't have a sweet tooth, I have sweet teeth.", "zh-TW": "碳水化合物。麵包、餅乾、任何烤的東西。我不是有一顆甜牙齒，是一整口。", ja: "炭水化物。パン、クッキー、焼き菓子。甘い歯が1本じゃなくて全部" },
    { s: { yang_deficient: 2, qi_stagnant: 1 }, en: "Something warm from the oven — toasted nuts, hot cocoa. Cold snacks feel like a betrayal.", "zh-TW": "烤箱出來的溫熱東西 — 烤堅果、熱可可。冰的零食感覺像背叛。", ja: "オーブンから出た温かいもの — ローストナッツ、ホットココア。冷たいおやつは裏切り" },
  ]},
  { q: { en: "How do you feel about spicy food?", "zh-TW": "你對辣的看法？", ja: "辛いものについてどう思う？" }, opts: [
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Love it. The spicier the better. I sweat, I cry, and I order another round.", "zh-TW": "愛死了。越辣越好。我流汗、我流淚、然後再點一輪。", ja: "大好き。辛ければ辛いほど。汗と涙で、もう一周頼む" },
    { s: { yin_deficient: 2, yang_deficient: 1 }, en: "I avoid it — my body treats spicy food like a house fire. Total evacuation mode.", "zh-TW": "我避開它 — 我的身體把辣食當火災處理。全面撤離模式。", ja: "避ける — 体が辛いものを火事扱い。全面避難モード" },
    { s: { qi_stagnant: 2, phlegm_damp: 1 }, en: "I want to love it, I really do. But I pay for it every single time. The heart wants what the stomach can't handle.", "zh-TW": "我想愛它，真的。但每次都付出代價。心之所向，胃不能及。", ja: "愛したい、本当に。でも毎回代償を払う。心が求めても胃が追いつかない" },
    { s: { sensitive: 2, qi_deficient: 1 }, en: "It upsets my stomach, triggers my skin, and ruins my week. But it IS delicious, so...", "zh-TW": "它讓我胃不舒服、皮膚出狀況、毀了我一整週。但它真的好吃，所以⋯", ja: "胃が痛い、肌が荒れる、1週間台無し。でも美味しいから..." },
  ]},
  { q: { en: "Your coffee/tea habit is...", "zh-TW": "你的咖啡/茶習慣是...", ja: "コーヒー・お茶の習慣は..." }, opts: [
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "Multiple cups of coffee. It's not a habit, it's an identity. My blood type is espresso.", "zh-TW": "好幾杯咖啡。這不是習慣，是身份認同。我的血型是濃縮咖啡。", ja: "コーヒー数杯。習慣じゃなくアイデンティティ。血液型はエスプレッソ" },
    { s: { yang_deficient: 2 }, en: "Tea, always hot. Coffee makes me jittery and anxious. Tea is a warm hug for my soul.", "zh-TW": "茶，永遠喝熱的。咖啡讓我緊張焦慮。茶是我靈魂的溫暖擁抱。", ja: "お茶、いつもホット。コーヒーは不安になる。お茶は魂の温かいハグ" },
    { s: { damp_heat: 2, phlegm_damp: 1 }, en: "I drink iced lattes like water. My barista knows my name, my order, and my emotional state.", "zh-TW": "我喝冰拿鐵像喝水。我的咖啡師知道我的名字、我的點單、和我的情緒狀態。", ja: "アイスラテを水みたいに飲む。バリスタが名前、注文、感情状態を把握してる" },
    { s: { qi_deficient: 2, sensitive: 1 }, en: "Herbal tea or warm water. Caffeine doesn't energize me, it just gives me anxiety and a fast heartbeat.", "zh-TW": "花草茶或溫水。咖啡因不給我能量，只給我焦慮和心跳加速。", ja: "ハーブティーか白湯。カフェインは元気ではなく不安と動悸をくれる" },
  ]},
  { q: { en: "You crave...", "zh-TW": "你渴望...", ja: "無性に欲しくなるのは..." }, opts: [
    { s: { damp_heat: 2, phlegm_damp: 1 }, en: "Rich, bold flavors — cheese, meat, sauce. If it's not intense, what's the point?", "zh-TW": "濃郁大膽的風味 — 起司、肉、醬汁。不夠強烈有什麼意義？", ja: "濃厚で大胆 — チーズ、肉、ソース。激しくなきゃ意味ない" },
    { s: { yin_deficient: 2 }, en: "Light and cooling — fruits, salads, smoothies. My body runs hot, I eat to cool down.", "zh-TW": "清淡降溫 — 水果、沙拉、冰沙。我的身體很熱，我靠吃來降溫。", ja: "軽くて涼しい — 果物、サラダ、スムージー。体が暑いから食べて冷やす" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Warm and comforting — soup, stew, rice dishes. If it doesn't warm me from the inside, I don't trust it.", "zh-TW": "溫暖療癒 — 湯、燉菜、飯類。如果不能從裡面溫暖我，我不信任它。", ja: "温かくて癒される — スープ、シチュー、ご飯もの。内側から温めないものは信じない" },
    { s: { blood_stasis: 2, qi_stagnant: 1 }, en: "Something I can crunch on — chips, nuts, ice. My jaw wants to work through my feelings.", "zh-TW": "可以嚼的東西 — 洋芋片、堅果、冰塊。我的下巴想幫我消化情緒。", ja: "噛めるもの — ポテトチップス、ナッツ、氷。顎で感情を処理したい" },
  ]},
  { q: { en: "Your eating speed is...", "zh-TW": "你的吃飯速度是...", ja: "食べるスピードは..." }, opts: [
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Slow. I savor every bite. Sometimes too many bites. My meal has a movie-length runtime.", "zh-TW": "慢的。我細嚼慢嚥。有時候太多口了。我的一餐有電影那麼長。", ja: "ゆっくり。一口一口味わう。時々食べすぎ。食事が映画並みの尺" },
    { s: { damp_heat: 2 }, en: "Fast and intense. I'm usually done first. My fork is a weapon and the plate is my enemy.", "zh-TW": "快又猛。我通常是第一個吃完的。叉子是武器，盤子是敵人。", ja: "早くて激しい。たいてい一番最初に食べ終わる。フォークは武器、皿は敵" },
    { s: { sensitive: 2, yang_deficient: 1 }, en: "I eat while watching something. If the screen is off, I forget how to swallow.", "zh-TW": "我邊看東西邊吃。螢幕關了的話我忘記怎麼吞嚥。", ja: "何かを見ながら食べる。画面がオフだと飲み込み方を忘れる" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "I forget to eat until I'm suddenly starving. Then I eat like I've been rescued from a desert island.", "zh-TW": "我忘記吃飯，直到突然餓到不行。然後像從荒島獲救一樣狂吃。", ja: "食べるのを忘れて、急に空腹で気づく。無人島から救出されたみたいに食べる" },
  ]},
  { q: { en: "Your fridge is mostly...", "zh-TW": "你的冰箱大多是...", ja: "冷蔵庫には主に..." }, opts: [
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "Takeout containers from three different weeks. I call it an archaeological site.", "zh-TW": "三個不同星期的外送盒。我稱之為考古遺址。", ja: "3週間分のデリバリー容器。考古遺跡と呼んでる" },
    { s: { yang_deficient: 2 }, en: "Leftovers and warm things. Lots of butter. It's basically a hug in appliance form.", "zh-TW": "剩菜和熱的東西。很多奶油。它基本上是家電形式的擁抱。", ja: "残り物と温かいもの。バター多め。基本的に家電形态のハグ" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Condiments and random items. No real meals. Just vibes and expired hot sauce.", "zh-TW": "調味料和零碎東西。沒有真正的餐點。只有氣氛和過期的辣醬。", ja: "調味料とバラバラのもの。ちゃんとした食事なし。雰囲気と期限切れのホットソースだけ" },
    { s: { phlegm_damp: 2 }, en: "Snacks, desserts, and something expired that I will defend with my life.", "zh-TW": "零食、甜點，還有過期的東西但我會誓死保衛它。", ja: "お菓子、デザート、と期限切れの何かを命懸けで守ってる" },
  ]},
  { q: { en: "You feel best after eating...", "zh-TW": "吃了什麼之後你感覺最好...", ja: "何を食べた後が一番いいか..." }, opts: [
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "After something warm and nourishing — like soup. My body literally thanks me.", "zh-TW": "吃了溫暖滋補的東西之後 — 像湯。我的身體會當面感謝我。", ja: "温かく滋養のあるものの後 — スープとか。体が直接感謝してくる" },
    { s: { phlegm_damp: 2, qi_stagnant: 1 }, en: "After a massive meal. Full to the point of bliss. My happy place is a food coma.", "zh-TW": "吃了大餐之後。飽到幸福的境界。我的快樂老家是飯氣攻心。", ja: "大量の食事の後。至福の満腹感。幸せの場所は食べ過ぎコーマ" },
    { s: { yin_deficient: 2 }, en: "After something light and fresh. Heavy food turns me into a sweaty, regretful gremlin.", "zh-TW": "吃了清爽的東西之後。重食讓我變成一個流汗、後悔的小惡魔。", ja: "軽くて新鮮なものの後。重いものを食べると汗ばむ後悔のグレムリンになる" },
    { s: { damp_heat: 2 }, en: "Honestly, after anything spicy or bold. Bland food leaves me hollow and confused.", "zh-TW": "說真的，吃了辣的或重口味的之後。清淡食物讓我空虛又困惑。", ja: "正直、辛いものや濃いものの後。薄味だと虚しくて混乱する" },
  ]},
  { q: { en: "Your relationship with sweets is...", "zh-TW": "你跟甜食的關係是...", ja: "甘いものとの関係は..." }, opts: [
    { s: { phlegm_damp: 2, damp_heat: 1 }, en: "I have a sweet tooth and I'm not ashamed. Dessert is not a course, it's the main event.", "zh-TW": "我有甜食癮，我不害羞。甜點不是一道菜，它是主角。", ja: "甘党、恥ずかしくない。デザートはコースじゃなくメインイベント" },
    { s: { blood_stasis: 2, sensitive: 1 }, en: "I go through phases. Right now I'm in my 'dark chocolate at midnight' era and I refuse to explain.", "zh-TW": "我會經歷不同階段。現在我的時代是「半夜吃苦巧克力」然後我拒絕解釋。", ja: "フェーズがある。今は「深夜にダークチョコ」期、説明は拒否" },
    { s: { yin_deficient: 2 }, en: "I prefer subtle sweetness — honey, dried fruit. Overly sweet things make me feel like I'm vibrating.", "zh-TW": "我偏好微甜 — 蜂蜜、果乾。太甜的東西讓我覺得自己在震動。", ja: "控えめな甘さが好き — 蜂蜜、ドライフルーツ。甘すぎると震えてる感じ" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "I crave them when I'm tired. So... always. My bloodstream is 40% cookie at this point.", "zh-TW": "我累的時候會想吃。所以⋯永遠。我的血管裡現在40%是餅乾。", ja: "疲れた時に欲しくなる。だから...いつも。血管の40%はクッキー" },
  ]},
  { q: { en: "Your skin is usually...", "zh-TW": "你的皮膚通常是...", ja: "肌の調子は主に..." }, opts: [
    { s: { blood_stasis: 2, yang_deficient: 1 }, en: "Dry and sometimes dull — like a sponge left in the sun. I moisturize like it's my job.", "zh-TW": "偏乾，有時候暗沉 — 像被太陽曬乾的海綿。我保濕像在上班。", ja: "乾燥しがち、くすみやすい — 太陽に乾いたスポンジみたい。保湿が仕事" },
    { s: { damp_heat: 2, phlegm_damp: 1 }, en: "Oily and breakout-prone — I've declared war on my T-zone and it's winning.", "zh-TW": "容易出油長痘 — 我已經向T字部位宣戰了，而它正在贏。", ja: "脂っぽくニキビができやすい — Tゾーンに宣戦布告したが向こうが勝ってる" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Pale. People keep asking if I'm okay. I'm fine, I just don't see the sun and I'm at peace with that.", "zh-TW": "蒼白。人們一直問我還好嗎。我很好，我只是看不到太陽，而且我已接受了。", ja: "白い。大丈夫？と聞かれる。大丈夫、太陽を見ないだけ、受け入れてる" },
    { s: { sensitive: 2, qi_stagnant: 1 }, en: "Reactive — it changes with my mood, the weather, my sleep, the lunar cycle, probably.", "zh-TW": "很敏感 — 跟著我的心情、天氣、睡眠、可能還有月相變化。", ja: "敏感 — 気分、天気、睡眠、たぶん月齢でも変わる" },
  ]},
  { q: { en: "Close your eyes and scan your body. What do you notice first?", "zh-TW": "閉上眼睛感受身體，你第一個注意到的是...", ja: "目を閉じて体をスキャン。最初に気づくのは..." }, opts: [
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Tight shoulders and a clenched jaw. I'm one stressful email away from a full body knot.", "zh-TW": "緊繃的肩膀和咬緊的牙關。我距離全身結成一團只差一封壓力郵件。", ja: "肩こりと食いしばり。ストレスメール一本で全身が結び目になる" },
    { s: { damp_heat: 2 }, en: "Hot and restless — like something's burning inside. My personal thermostat is stuck on 'broil.'", "zh-TW": "燥熱不安 — 像有什麼在裡面燒。我的個人恆溫器卡在「燒烤」了。", ja: "暑くて落ち着かない — 何かが中で燃えてる。内部サーモスタットが『焼き』で固定されてる" },
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "Heavy and sluggish — like I'm wearing a lead wetsuit. Gravity hits different for me.", "zh-TW": "沉重又遲鈍 — 像穿了一件鉛做的潛水衣。重力對我的影響不太一樣。", ja: "重だるい — 鉛のウェットスーツを着てるみたい。重力の感じ方が違う" },
    { s: { yang_deficient: 2 }, en: "Cold — especially my hands and feet. My extremities have their own climate zone.", "zh-TW": "冷 — 特別是手腳。我的四肢有自己的氣候區。", ja: "冷たい — 特に手足。末端に独自の気候帯がある" },
  ]},
]
