import type { PoolQuestion } from "../question-pool"

export const PART2: PoolQuestion[] = [
  { q: { en: "Your skin's personality is...", "zh-TW": "你的皮膚的個性是...", ja: "肌の性格は..." }, opts: [
    { s: { blood_stasis: 2, yang_deficient: 1 }, en: "My skin bruises easily and marks take forever to fade.", "zh-TW": "我的皮膚容易瘀青，痕跡很久才會消。", ja: "あざができやすく、消えるのに時間がかかる" },
    { s: { yin_deficient: 2 }, en: "I get hot flashes and my cheeks flush easily.", "zh-TW": "我會突然一陣熱，臉頰容易泛紅。", ja: "ほてりが来て、ほおが赤くなりやすい" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Translucent. You can map my veins from across the room. SPF is my entire personality.", "zh-TW": "半透明的。隔著房間就能畫出血管分佈圖。防曬是我整個人格。", ja: "透けてる。部屋の向こうから血管マップが描ける。日焼け止めがアイデンティティ" },
    { s: { sensitive: 2 }, en: "I react to everything — new products, weather changes, stress.", "zh-TW": "我對一切都有反應 — 新產品、天氣變化、壓力。", ja: "全部に反応する — 新しい製品、天気、ストレス" },
  ]},
  { q: { en: "Your digestion is...", "zh-TW": "你的消化能力是...", ja: "消化は..." }, opts: [
    { s: { yin_deficient: 2 }, en: "Way too fast. Two hours later I'm starving again. My metabolism doesn't believe in pacing.", "zh-TW": "快到不行。兩小時後又餓得要命。我的代謝不懂什麼叫節奏。", ja: "速すぎ。2時間後にはもう空腹。私の代謝はペース配信を知らない" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Slow and sometimes uncomfortable after cold food.", "zh-TW": "慢，有時吃了冷的東西後不舒服。", ja: "遅い、冷たいものの後に不快" },
    { s: { phlegm_damp: 2, damp_heat: 1 }, en: "Heavy and bloated — I feel like I'm always full.", "zh-TW": "沉重又脹 — 我覺得自己永遠都是飽的。", ja: "重くて膨満 — いつも満腹感" },
    { s: { qi_stagnant: 2 }, en: "Tied to my mood — stress goes straight to my gut.", "zh-TW": "跟心情有關 — 壓力直接反映在腸胃。", ja: "気分と連動 — ストレスが直接胃腸に" },
  ]},
  { q: { en: "You sweat when...", "zh-TW": "你什麼時候流汗...", ja: "汗をかくのは..." }, opts: [
    { s: { qi_deficient: 2 }, en: "At the slightest effort. A brisk walk does it.", "zh-TW": "一點點運動就流。快走就行了。", ja: "少しの運動で。速歩でも" },
    { s: { damp_heat: 2 }, en: "A lot, and it's intense. I glisten.", "zh-TW": "很多，而且很猛。我會發光。", ja: "大量で激しい。テカテカ" },
    { s: { phlegm_damp: 2 }, en: "Thick and sticky. Not a graceful glisten — more like I've been steamed like a dumpling.", "zh-TW": "稠稠黏黏的。不是優雅的發光 — 比較像被蒸成一顆小籠包。", ja: "濃くてベタベタ。上品な汗じゃない — 蒸し餃子みたいに蒸されてる" },
    { s: { yang_deficient: 2, yin_deficient: 1 }, en: "Rarely. Even during intense workouts.", "zh-TW": "很少。就算劇烈運動也是。", ja: "稀に。激しい運動でも" },
  ]},
  { q: { en: "Your weight tends to...", "zh-TW": "你的體重傾向...", ja: "体重は..." }, opts: [
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "Thin and stuck. Sounds like a flex until you realize I can't build muscle either.", "zh-TW": "瘦而且不上不下。聽起來像炫耀，直到你發現我也練不出肌肉。", ja: "細くて増えない。自慢に聞こえるけど、筋肉もつかないと気づくまでの話" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "It creeps up, especially when I'm stressed.", "zh-TW": "它會慢慢增加，特別是壓力大的時候。", ja: "じわじわ増える、特にストレス時" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "It fluctuates with my emotions.", "zh-TW": "跟著我的情緒波動。", ja: "感情と一緒に変動" },
    { s: { damp_heat: 2 }, en: "I gain muscle easily but also hold water weight.", "zh-TW": "我很容易長肌肉，但也容易水腫。", ja: "筋肉がつきやすいが、むくみやすい" },
  ]},
  { q: { en: "You bruise...", "zh-TW": "你瘀青的情況是...", ja: "あざのできやすさは..." }, opts: [
    { s: { blood_stasis: 3 }, en: "All the time. I find new ones and wonder where they came from.", "zh-TW": "隨時都有。我會發現新的然後想從哪來的。", ja: "いつも。新しいのを見つけてどこから来たか考える" },
    { s: { phlegm_damp: 2, damp_heat: 1 }, en: "Not really my issue. My body is soft and squishy — bruising is way down my worry list.", "zh-TW": "不太是我的問題。身體軟軟泡泡的 — 瘀青在擔心清單很下面。", ja: "あまり問題ない。体は柔らかくてぷにぷに — あざは心配リストの最後の方" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Sometimes, especially in cold weather.", "zh-TW": "有時候，特別是冷天。", ja: "時々、特に寒い時" },
    { s: { sensitive: 2 }, en: "My skin reacts to everything — bumps, rashes, redness.", "zh-TW": "我的皮膚對一切都有反應 — 凸起、疹子、泛紅。", ja: "肌が全部に反応 — ブツブツ、発疹、赤み" },
  ]},
  { q: { en: "Your hair is...", "zh-TW": "你的頭髮是...", ja: "髪の調子は..." }, opts: [
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Fine. I take care of it.", "zh-TW": "不錯。我有在照顧。", ja: "良い。ケアしてる" },
    { s: { damp_heat: 2 }, en: "Oily, especially on my face.", "zh-TW": "油性，特別是臉部。", ja: "脂っぽい、特に顔" },
    { s: { yin_deficient: 2, blood_stasis: 1 }, en: "Dry and sometimes brittle.", "zh-TW": "乾燥，有時脆弱。", ja: "乾燥してて脆い時がある" },
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "Normal but I wish it were thicker.", "zh-TW": "正常但希望它更濃密。", ja: "普通だけど、もっと厚くなってほしい" },
  ]},
  { q: { en: "You carry tension in your...", "zh-TW": "你把壓力扛在哪裡...", ja: "緊張をどこにためる？" }, opts: [
    { s: { qi_stagnant: 3 }, en: "Shoulders and jaw — I carry the world's stress there.", "zh-TW": "肩膀和下巴 — 我把全世界的壓力都放在那裡。", ja: "肩と顎 — 世界のストレスをそこに背負ってる" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Lower back and knees — everything feels heavy.", "zh-TW": "下背和膝蓋 — 一切都覺得沉重。", ja: "腰と膝 — 全部が重く感じる" },
    { s: { blood_stasis: 2 }, en: "Neck and head — like something's not flowing right.", "zh-TW": "脖子和頭 — 像有什麼流不順。", ja: "首と頭 — 何かが流れてない感じ" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "Everywhere simultaneously. I'm one big exposed nerve. Poke me and I'd probably vibrate.", "zh-TW": "同時全身緊繃。我是一條裸露的神經。戳我一下我可能會震動。", ja: "全身同時に。私は巨大なむき出しの神経。突いたら震えるかも" },
  ]},
  { q: { en: "Your immune system is...", "zh-TW": "你的免疫力是...", ja: "免疫力は..." }, opts: [
    { s: { qi_deficient: 1, yang_deficient: 1, qi_stagnant: 1 }, en: "I don't get full-blown sick, but I'm always at 70%. I've forgotten what 100% feels like.", "zh-TW": "不會大病，但永遠只運作在70%。已經忘了100%是什麼感覺。", ja: "本格的な病気はないけど、いつも70%。100%の感覚を忘れた" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Weak — I catch every cold that goes around.", "zh-TW": "虛弱 — 每個流行感冒我都會中。", ja: "弱い — 流行る風邪は全部もらう" },
    { s: { sensitive: 3 }, en: "Reactive — my body responds to everything dramatically.", "zh-TW": "反應強烈 — 我的身體對一切都有戲劇性的反應。", ja: "過剰反応 — 体が全てにドラマチックに反応" },
    { s: { damp_heat: 2, phlegm_damp: 1 }, en: "Decent, but I tend to get skin issues instead.", "zh-TW": "還行，但我容易有皮膚問題。", ja: "まあまあ、でも肌トラブルになりがち" },
  ]},
  { q: { en: "Your complexion is usually...", "zh-TW": "你的臉色通常是...", ja: "顔色はいつも..." }, opts: [
    { s: { yin_deficient: 2 }, en: "Flushed, especially in the afternoon.", "zh-TW": "泛紅，特別是下午。", ja: "赤み、特に午後" },
    { s: { yang_deficient: 2 }, en: "Pale. People sometimes ask if I'm feeling okay.", "zh-TW": "蒼白。有時候有人問我還好嗎。", ja: "青白い。大丈夫？と聞かれる" },
    { s: { blood_stasis: 2 }, en: "Slightly dark or uneven — especially around my eyes.", "zh-TW": "有點暗沉或不均 — 特別是眼周。", ja: "少し暗いやムラ — 特に目の周り" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Dull. I look tired even on my best day. Concealer is my best friend.", "zh-TW": "暗沉。狀態最好的日子看起來還是累。遮瑕膏是我最好的朋友。", ja: "くすんでる。調子が良い日でも疲れて見える。コンシーラーが親友" },
  ]},
  { q: { en: "You get sick when...", "zh-TW": "你什麼時候會生病...", ja: "病気になるのは..." }, opts: [
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "When seasons change. Every single time.", "zh-TW": "季節轉換的時候。每次都是。", ja: "季節の変わり目。毎回" },
    { s: { sensitive: 3 }, en: "From specific triggers — foods, pollen, stress.", "zh-TW": "特定的觸發因素 — 食物、花粉、壓力。", ja: "特定のトリガー — 食べ物、花粉、ストレス" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "When I burn out from pushing too hard for too long. The crash is always coming.", "zh-TW": "撐太久終於崩潰的時候。崩潰永遠在路上。", ja: "長期間頑張りすぎて燃え尽きた時。クラッシュはいつも来る" },
    { s: { qi_stagnant: 2 }, en: "When I'm emotionally drained.", "zh-TW": "當我情緒耗盡的時候。", ja: "精神的に疲れ果てた時" },
  ]},
  { q: { en: "Your body runs...", "zh-TW": "你的身體運行在...", ja: "体の温度は..." }, opts: [
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Hot. I feel like a space heater.", "zh-TW": "熱的。我像一台暖氣機。", ja: "熱い。ストーブみたい" },
    { s: { yang_deficient: 2 }, en: "Cold. I'm always seeking warmth.", "zh-TW": "冷的。我永遠在尋找溫暖。", ja: "冷たい。いつも温かさを求めてる" },
    { s: { sensitive: 2, phlegm_damp: 1 }, en: "Fine most of the time, but the MOMENT something shifts — a breeze, a draft — I feel it in my bones.", "zh-TW": "大部分時候沒事，但一有變化 — 一陣風、一絲涼意 — 就覺得到骨子裡。", ja: "たいてい大丈夫、でも変化があった瞬間 — 風、冷気 — 骨まで感じる" },
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "Depends on the day — it fluctuates.", "zh-TW": "看日子 — 會波動。", ja: "日による — 変動する" },
  ]},
  { q: { en: "No alarm clock. No obligations. You naturally wake up at...", "zh-TW": "沒有鬧鐘、沒有行程，你自然醒的時間是...", ja: "目覚ましなし、予定なし。自然に起きる時間は..." }, opts: [
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "7–8 AM, but I wake up with a full mental to-do list already queued. My brain boots before my body.", "zh-TW": "7-8點，但醒來時腦中待辦清單已經排好了。大腦比身體先開機。", ja: "7〜8時、でも目が覚める前にToDoリストは完成済み。脳が体より先に起動する" },
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "8–9 AM — I need my sleep but I function fine once I'm up.", "zh-TW": "8-9點 — 需要睡飽但起來後還行。", ja: "8〜9時 — 睡眠は必要だけど起きれば動ける" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "10–11 AM — honestly I could sleep forever and still be tired.", "zh-TW": "10-11點 — 說真的我可以睡到永遠還是累。", ja: "10〜11時 — 正直、いくら寝ても眠い" },
    { s: { yin_deficient: 3 }, en: "Early, but I can't fall back asleep — my mind is already racing.", "zh-TW": "很早醒，但睡不回去 — 腦袋已經開始轉了。", ja: "早く起きるけど二度寝できない — 頭がもう動いてる" },
  ]},
  { q: { en: "Your sleep quality is...", "zh-TW": "你的睡眠品質是...", ja: "睡眠の質は..." }, opts: [
    { s: { yang_deficient: 2, phlegm_damp: 1 }, en: "Heavy and deep, like a hibernating bear. But I still wake up groggy. How is that fair?", "zh-TW": "沉又深，像冬眠的熊。但醒來還是昏昏沉沉。這公平嗎？", ja: "重くて深い、冬眠中の熊みたい。でも起きてもぼんやり。どういう理不尽？" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "My body sleeps but my mind keeps running.", "zh-TW": "身體睡了但腦袋繼續跑。", ja: "体は寝てるけど頭は動き続ける" },
    { s: { qi_deficient: 2 }, en: "I sleep a lot but never feel rested.", "zh-TW": "我睡很多但從不覺得有休息到。", ja: "たくさん寝るけど疲れが取れない" },
    { s: { yang_deficient: 2 }, en: "Good, but I always need more blankets than everyone else.", "zh-TW": "不錯，但我永遠比別人需要更多被子。", ja: "良いけど、みんなより毛布が常に必要" },
  ]},
  { q: { en: "You dream about...", "zh-TW": "你夢到...", ja: "夢の中身は..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "Anxiety dreams — I'm always late or unprepared.", "zh-TW": "焦慮夢 — 我永遠遲到或沒準備好。", ja: "不安な夢 — いつも遅刻か準備不足" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Vivid and intense — I remember every detail.", "zh-TW": "鮮明又強烈 — 我記得每個細節。", ja: "鮮やかで激しい — 全部の詳細を覚えてる" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "I sleep so deep I don't dream — or I just don't remember. Either way, it's a void.", "zh-TW": "睡得太深不做夢 — 或者只是不記得。不管怎樣都是一片虛無。", ja: "深く寝すぎて夢を見ない — または覚えてない。どっちにしても虚無" },
    { s: { blood_stasis: 2, sensitive: 1 }, en: "Recurring themes — the same situations keep coming back.", "zh-TW": "反覆的主題 — 同樣的情境一直回來。", ja: "繰り返すテーマ — 同じ場面が戻ってくる" },
  ]},
  { q: { en: "Before bed, you...", "zh-TW": "睡前，你...", ja: "寝る前は..." }, opts: [
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Scroll my phone and overthink the day.", "zh-TW": "滑手機，然後過度回顧今天。", ja: "スマホを見て1日を考えすぎる" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Wrap myself in blankets like a burrito. The warmer the better. I'm basically a lizard seeking heat.", "zh-TW": "把自己像墨西哥捲餅一樣包在被子裡。越暖越好。我基本上是一隻找熱源的蜥蜴。", ja: "ブランケットでブリトー巻き。暖かければ暖かいほど良い。私は basically 暖を求めるトカゲ" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "A warm bath or shower — it helps me unwind.", "zh-TW": "泡個熱水澡或沖個澡 — 幫我放鬆。", ja: "温かいお風呂 — リラックスできる" },
    { s: { damp_heat: 2 }, en: "I'm still going — bedtime is a suggestion.", "zh-TW": "我還在跑 — 睡覺時間只是建議。", ja: "まだ動いてる — 就寝は提案に過ぎない" },
  ]},
  { q: { en: "Your sleeping position is...", "zh-TW": "你的睡姿是...", ja: "寝姿勢は..." }, opts: [
    { s: { yang_deficient: 2 }, en: "Curled up in a ball, hugging a pillow.", "zh-TW": "蜷成一團，抱著枕頭。", ja: "丸まって、枕を抱えて" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "On my side, curled slightly, with at least one pillow tucked somewhere for support. Comfort is non-negotiable.", "zh-TW": "側躺微蜷，至少要塞一個枕頭在某個地方支撐。舒適是不能妥協的。", ja: "横向きで少し丸まって、最低1つの枕をどこかに挟む。快適さは譲れない" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "On my stomach or side, changing positions all night.", "zh-TW": "趴著或側躺，整晚換姿勢。", ja: "うつ伏せか横向き、一晩中姿勢を変える" },
    { s: { yin_deficient: 2 }, en: "Starfished — I need space and I run hot.", "zh-TW": "大字形 — 我需要空間而且我會熱。", ja: "大の字 — スペースが必要、暑がり" },
  ]},
  { q: { en: "You wake up in the middle of the night because...", "zh-TW": "你半夜醒來是因為...", ja: "夜中に目が覚める理由は..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "My mind won't shut off — thinking about tomorrow.", "zh-TW": "腦袋關不掉 — 在想明天的事。", ja: "頭が止まらない — 明日のことを考えてる" },
    { s: { yang_deficient: 2 }, en: "I'm cold and need another blanket.", "zh-TW": "我覺得冷，需要多一條被子。", ja: "寒い、毛布がもう一枚必要" },
    { s: { yin_deficient: 2 }, en: "I'm too hot and need to kick off the covers.", "zh-TW": "我太熱了，需要踢掉被子。", ja: "暑すぎて布団を蹴りたい" },
    { s: { damp_heat: 2, sensitive: 1 }, en: "My bladder. Every single night. My kidneys have a strict schedule and they don't negotiate.", "zh-TW": "膀胱。每天晚上。我的腎臟有嚴格的時間表，不接受協商。", ja: "膀胱。毎晩。私の腎臟は厳格なスケジュールで、交渉不可" },
  ]},
  { q: { en: "Your ideal bedtime is...", "zh-TW": "你的理想上床時間是...", ja: "理想の就寝時間は..." }, opts: [
    { s: { qi_stagnant: 2, damp_heat: 1 }, en: "10 PM in theory, midnight in practice. I know I should sleep. My phone disagrees.", "zh-TW": "理論上10點，實際上12點。我知道該睡了。手機不同意。", ja: "理論は22時、実践は深夜0時。寝なきゃって分かってる。スマホが反対してる" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "9–10 PM. I need all the sleep I can get.", "zh-TW": "9-10點。我需要所有能得到的睡眠。", ja: "21〜22時。眠れるだけ眠りたい" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "After midnight. I come alive at night.", "zh-TW": "午夜之後。我在晚上才活過來。", ja: "深夜0時以降。夜に生き生きする" },
    { s: { damp_heat: 2 }, en: "Whenever I crash. Usually late.", "zh-TW": "什麼時候垮掉就什麼時候睡。通常很晚。", ja: "いつバテるか。たいてい遅い" },
  ]},
  { q: { en: "When you can't sleep, you...", "zh-TW": "睡不著的時候，你...", ja: "眠れない時..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "I think more. Which makes it worse.", "zh-TW": "我想更多。結果更慘。", ja: "もっと考える。悪化する" },
    { s: { yang_deficient: 2 }, en: "I make warm milk or tea and try again. No drama, just persistence. I'll wear sleep down eventually.", "zh-TW": "泡杯熱牛奶或茶再試一次。不搞戲劇化，就是堅持。我會把睡意磨出來的。", ja: "温かい牛乳かお茶を作ってもう一度。ドラマなし、ただ粘る。いずれ眠気が折れる" },
    { s: { yin_deficient: 2 }, en: "I get up and do something — lying there is torture.", "zh-TW": "我起來做點事 — 躺在那裡是折磨。", ja: "起きて何かする — 横になってるのは苦痛" },
    { s: { qi_deficient: 2 }, en: "I just lie there, exhausted but awake.", "zh-TW": "我就躺在那裡，筋疲力盡但醒著。", ja: "ただ横たわる、疲れきってるのに目が覚めてる" },
  ]},
  { q: { en: "Your naps are...", "zh-TW": "你的午睡是...", ja: "昼寝は..." }, opts: [
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "Accidental 3-hour naps that ruin my night.", "zh-TW": "不小心睡了3小時，毀了我一整晚。", ja: "うっかり3時間、夜が台無し" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "I nap whenever I can. A 20-minute nap? A 2-hour nap? I don't discriminate. Sleep is sleep.", "zh-TW": "能睡就睡。20分鐘？2小時？我不挑。睡就是睡。", ja: "いつでも昼寝する。20分？2時間？選ばない。寝れる時に寝る" },
    { s: { yin_deficient: 2 }, en: "I can't nap — my brain won't let me.", "zh-TW": "我沒辦法小睡 — 我的腦袋不讓我。", ja: "昼寝できない — 頭が許さない" },
    { s: { damp_heat: 2 }, en: "Short and intense, like everything I do.", "zh-TW": "短暫但猛烈，像我做的一切。", ja: "短くて激しい、私の全てと同じ" },
  ]},
  { q: { en: "Your pillow is...", "zh-TW": "你的枕頭是...", ja: "枕は..." }, opts: [
    { s: { yang_deficient: 2 }, en: "Flat and cool. I like it minimal.", "zh-TW": "扁平又涼。我喜歡極簡。", ja: "平らで涼しい。ミニマルが好き" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "Cool to the touch. I flip it constantly chasing the cold side. It's a whole ritual.", "zh-TW": "觸感要涼。我不斷翻面找冷的那一面。這是一個完整的儀式。", ja: "ひんやり冷たい感触。冷たい面を探して裏返し続ける。もう儀式" },
    { s: { qi_stagnant: 2 }, en: "I rearrange it ten times before I can relax.", "zh-TW": "我重新整理十次才能放鬆。", ja: "10回 arrange してようやくリラックス" },
    { s: { qi_deficient: 2 }, en: "Fluffy and abundant. More pillows = better sleep.", "zh-TW": "蓬鬆又多。越多枕頭 = 越好睡。", ja: "ふわふわでたっぷり。枕が多いほど良い睡眠" },
  ]},
  { q: { en: "Which phrase hits closest to home?", "zh-TW": "哪句話最戳中你？", ja: "一番グサッとくる言葉は？" }, opts: [
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "I overthink everything and then feel bad about overthinking.", "zh-TW": "我想太多，然後又因為想太多而難過。", ja: "考えすぎて、考えすぎたことに落ち込む" },
    { s: { damp_heat: 2 }, en: "I feel everything — the good, the bad, and what no one else notices.", "zh-TW": "我什麼都感受得到 — 好的、壞的、別人注意不到的。", ja: "すべてを感じる — 良いことも悪いことも" },
    { s: { blood_stasis: 2 }, en: "I love deeply, but I don't let go easily.", "zh-TW": "我愛得很深，但我不容易放手。", ja: "深く愛する、でも簡単に手放せない" },
    { s: { qi_deficient: 2 }, en: "I'm tired on a spiritual level.", "zh-TW": "我是靈魂深處的累。", ja: "魂レベルで疲れてる" },
  ]},
  { q: { en: "When stress hits, you...", "zh-TW": "壓力來襲時，你...", ja: "ストレスが来たら..." }, opts: [
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "I withdraw into my own world and overthink.", "zh-TW": "我退回自己的世界裡過度思考。", ja: "自分の世界に引きこもって考えすぎる" },
    { s: { damp_heat: 2 }, en: "I explode — then feel better. Then feel guilty.", "zh-TW": "我爆發 — 然後感覺好多了。然後感到內疚。", ja: "爆発 — それでスッキリ。その後罪悪感" },
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "I rationalize it perfectly. On the outside I'm fine. Inside, I've been screaming for three days.", "zh-TW": "我完美地合理化它。表面好好的。裡面已經尖叫三天了。", ja: "完璧に合理化する。外は平気。中では3日間叫んでる" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "I shut down. I literally can't deal.", "zh-TW": "我當機。我真的無法處理。", ja: "シャットダウン。本当に対応できない" },
  ]},
  { q: { en: "Your emotional range is...", "zh-TW": "你的情緒範圍是...", ja: "感情の幅は..." }, opts: [
    { s: { damp_heat: 2 }, en: "Wide and intense — I feel everything at 200%.", "zh-TW": "寬廣又強烈 — 我以200%感受一切。", ja: "広くて激しい — 全てを200%感じる" },
    { s: { qi_stagnant: 2 }, en: "Deep but contained — I process internally.", "zh-TW": "深但壓抑 — 我在內部處理。", ja: "深く抑圧 — 内面で処理する" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Narrow and muted — I feel things, but quietly. My emotions are on permanent Do Not Disturb.", "zh-TW": "窄而低沉 — 我有感覺，但安靜的。我的情緒永遠開啟勿擾模式。", ja: "狭くて静か — 感じるけどひっそりと。感情は常に「おやすみモード」" },
    { s: { sensitive: 2 }, en: "Extreme — I absorb everyone else's emotions too.", "zh-TW": "極端 — 我也吸收了所有人的情緒。", ja: "極端 — 他人の感情も吸収する" },
  ]},
  { q: { en: "You process feelings by...", "zh-TW": "你處理情緒的方式是...", ja: "感情の処理方法は..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "By thinking about it. Then thinking more. Then more.", "zh-TW": "思考它。然後再想。然後再想更多。", ja: "考える。そしてもっと考える。さらに考える" },
    { s: { damp_heat: 2 }, en: "By expressing it immediately — no filter.", "zh-TW": "立刻表達出來 — 沒有過濾。", ja: "すぐ表現する — フィルターなし" },
    { s: { qi_stagnant: 2, sensitive: 1 }, en: "By absorbing them quietly for weeks, then randomly crying in the shower about something from 2019.", "zh-TW": "默默吸收好幾週，然後在洗澡時突然為2019年的某件事哭出來。", ja: "何週間も静かに吸収して、シャワー中に2019年のことを急に泣く" },
    { s: { blood_stasis: 2, qi_deficient: 1 }, en: "They sit in my body for days. I feel them physically.", "zh-TW": "它們在我身體裡待好幾天。我會感覺到它們。", ja: "体に何日も居座る。物理的に感じる" },
  ]},
  { q: { en: "Your biggest worry is...", "zh-TW": "你最大的擔憂是...", ja: "一番の心配は..." }, opts: [
    { s: { qi_stagnant: 2, qi_deficient: 1 }, en: "Not being good enough, despite trying so hard.", "zh-TW": "不夠好，儘管我已經很努力了。", ja: "いくら頑張っても十分じゃないこと" },
    { s: { damp_heat: 2 }, en: "Losing control — of my schedule, my health, my life.", "zh-TW": "失去控制 — 我的日程、健康、生活。", ja: "コントロールを失うこと — スケジュール、健康、人生" },
    { s: { blood_stasis: 2 }, en: "Being misunderstood or forgotten.", "zh-TW": "被誤解或被遺忘。", ja: "誤解されること、忘れられること" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "That I'll never have enough energy to do all the things I want. My ambition and my body are in different zip codes.", "zh-TW": "永遠沒有足夠的精力做我想做的事。我的野心和身體在不同的郵遞區號。", ja: "やりたいことをするエネルギーが永遠に足りないこと。野心と体が別の郵便番号" },
  ]},
  { q: { en: "You deal with anger by...", "zh-TW": "你處理憤怒的方式是...", ja: "怒りへの対処法は..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "I don't. I bottle it up until it explodes.", "zh-TW": "我不處理。我壓抑它直到爆炸。", ja: "しない。爆発するまで溜め込む" },
    { s: { damp_heat: 2 }, en: "I confront it head-on. Immediately.", "zh-TW": "我正面迎擊。立刻。", ja: "正面から対決。即座に" },
    { s: { sensitive: 2, damp_heat: 1 }, en: "I write a devastating text, delete it, write another, delete that too. The unsent drafts are a novel.", "zh-TW": "打了一段致命的訊息，刪掉，再打一段，再刪。草稿匣可以出小說了。", ja: "破壊的なメッセージを書いて消して、また書いて消す。下書きフォルダは小説になる" },
    { s: { qi_deficient: 2 }, en: "I avoid it. Conflict drains my already limited energy.", "zh-TW": "我避開它。衝突會耗盡我已經有限的能量。", ja: "避ける。対立は限られたエネルギーを奪う" },
  ]},
  { q: { en: "When you're happy, you...", "zh-TW": "你開心的時候，你...", ja: "嬉しい時..." }, opts: [
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "Intensely and openly — I can't hide it.", "zh-TW": "強烈又公開 — 我藏不住。", ja: "激しくオープンに — 隠せない" },
    { s: { qi_stagnant: 2 }, en: "Quietly, in a moment alone with music or art.", "zh-TW": "安靜地，一個人聽音樂或看藝術的時候。", ja: "静かに、音楽やアートと一人でいる時に" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "By feeling warm all over, like sunshine from the inside. It's subtle but it sustains me for days.", "zh-TW": "全身暖洋洋的，像從裡面照出陽光。很細微但可以撐我好幾天。", ja: "全身がぽかぽかする、内側から太陽が出たみたい。さりげないけど何日も続く" },
    { s: { blood_stasis: 2 }, en: "Deeply — it stays with me for days.", "zh-TW": "深刻 — 它會跟著我好幾天。", ja: "深く — 何日も残る" },
  ]},
  { q: { en: "Your inner voice usually says...", "zh-TW": "你的內心聲音通常說...", ja: "心の声はいつも..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "You're not doing enough.", "zh-TW": "你做得不夠。", ja: "もっとやれ" },
    { s: { qi_deficient: 2 }, en: "You should rest more.", "zh-TW": "你應該多休息。", ja: "もっと休むべき" },
    { s: { yang_deficient: 2, sensitive: 1 }, en: "Did you lock the door? Did you send that email? Are you sure? Double check. Triple check.", "zh-TW": "你鎖門了嗎？那封信寄了嗎？你確定嗎？再檢查一次。再一次。", ja: "ドア閉めた？メール送った？本当に？もう一度確認。もう一回確認" },
    { s: { damp_heat: 2 }, en: "Go big or go home.", "zh-TW": "要嘛做大要嘛回家。", ja: "デカく行くか帰るか" },
  ]},
  { q: { en: "You cry when...", "zh-TW": "你什麼時候哭...", ja: "泣くのは..." }, opts: [
    { s: { sensitive: 2, qi_stagnant: 1 }, en: "At movies, songs, even commercials. I can't help it.", "zh-TW": "看電影、聽歌、甚至廣告。我忍不住。", ja: "映画、曲、CMでも。止められない" },
    { s: { qi_stagnant: 2 }, en: "When I finally let my guard down, which is rare.", "zh-TW": "當我終於放下防備的時候，這很少發生。", ja: "ようやくガードを下げた時、稀に" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "When I'm overtired and someone is unexpectedly kind to me. Kindness + exhaustion = instant waterworks.", "zh-TW": "累到不行的時候有人突然對我溫柔。善意加疲憊 = 秒哭。", ja: "疲れ果ててる時に誰かが優しくしてくれた時。優しさ＋疲労 = 即泣き" },
    { s: { damp_heat: 2 }, en: "When something is profoundly unjust — I cry from anger.", "zh-TW": "當事情嚴重不公的時候 — 我氣哭。", ja: "何かがひどく不当な時 — 怒りで泣く" },
  ]},
  { q: { en: "You make decisions by...", "zh-TW": "你做決定的方式是...", ja: "決断の仕方は..." }, opts: [
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "By feel. I weigh every option for days.", "zh-TW": "靠感覺。我會衡量每個選項好幾天。", ja: "感覚で。何日も全選択肢を検討" },
    { s: { damp_heat: 2 }, en: "Quickly and confidently. Gut instinct.", "zh-TW": "快速又自信。直覺。", ja: "速く自信を持って。直感" },
    { s: { blood_stasis: 2, qi_stagnant: 1 }, en: "I go with my gut, then second-guess myself for three weeks. The decision is fast; the peace is slow.", "zh-TW": "靠直覺，然後自我懷疑三週。決定很快，安心很慢。", ja: "直感で決めて、その後3週間自己嫌悪。決断は速い、安心は遅い" },
    { s: { qi_deficient: 2 }, en: "I avoid deciding until the last possible moment.", "zh-TW": "我避免做決定，直到最後一刻。", ja: "ギリギリまで決定を避ける" },
  ]},
  { q: { en: "Your ideal work rhythm is...", "zh-TW": "你的理想工作節奏是...", ja: "理想の働き方は..." }, opts: [
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Slow and steady. I need warm-up time. Don't rush me — I'll get there on my own timeline.", "zh-TW": "慢而穩。我需要暖機。別催我 — 我會到的，照自己的時間表。", ja: "ゆっくり着実。ウォームアップが必要。急かさないで — 自分のペースで着く" },
    { s: { qi_deficient: 2 }, en: "Short bursts of intense focus, then I need a real break.", "zh-TW": "短時間高強度專注，然後真的需要休息。", ja: "短時間の集中、その後しっかり休憩" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "I work best under pressure, late at night, with a coffee in hand.", "zh-TW": "壓力下表現最好、深夜、手拿咖啡。", ja: "追い込まれた方がいい、深夜、コーヒー片手に" },
    { s: { damp_heat: 1, blood_stasis: 2 }, en: "I need variety — I can't do the same thing all day long.", "zh-TW": "需要變化 — 沒辦法一整天做同樣的事。", ja: "変化が必要 — 一日同じことは無理" },
  ]},
  { q: { en: "When you're most productive...", "zh-TW": "你最有生產力的時候是...", ja: "一番生産的なのは..." }, opts: [
    { s: { phlegm_damp: 2, damp_heat: 1 }, en: "After a good meal. My brain only works when my stomach is happy. Food is my productivity hack.", "zh-TW": "吃完一頓好的之後。胃開心了腦袋才動。食物是我的生產力秘訣。", ja: "美味しいご飯の後。胃が幸せじゃないと脳も動かない。食事が生産性ハック" },
    { s: { yin_deficient: 2, qi_stagnant: 1 }, en: "Late at night, when the world is quiet.", "zh-TW": "深夜，世界安靜的時候。", ja: "深夜、世界が静かな時" },
    { s: { damp_heat: 2 }, en: "Under a tight deadline — I thrive on pressure.", "zh-TW": "緊迫的截止日下 — 壓力讓我茁壯。", ja: "厳しい締め切り下 — プレッシャーで伸びる" },
    { s: { qi_deficient: 2 }, en: "In the late morning, after I've warmed up.", "zh-TW": "接近中午，暖機完之後。", ja: "遅い朝、ウォームアップ後" },
  ]},
  { q: { en: "Your desk is...", "zh-TW": "你的桌子是...", ja: "机の上は..." }, opts: [
    { s: { blood_stasis: 2, qi_stagnant: 1 }, en: "Covered in sentimental items. Photos, old tickets, a rock from that one beach. Everything has a story.", "zh-TW": "堆滿有紀念意義的東西。照片、舊票根、那個海灘的石頭。每樣東西都有故事。", ja: "思い出品で溢れてる。写真、古いチケット、あの海で拾った石。すべてに物語がある" },
    { s: { qi_stagnant: 2, damp_heat: 1 }, en: "Organized chaos. I know where everything is. Don't touch it.", "zh-TW": "有組織的混亂。我知道每樣東西在哪。別碰。", ja: "秩序あるカオス。どこに何があるかわかる。触るな" },
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "A mess. I clean it once a month whether it needs it or not.", "zh-TW": "一團亂。我每個月整理一次不管需不需要。", ja: "散らかってる。月1で片付ける必要あるなしに関わらず" },
    { s: { yin_deficient: 2 }, en: "Minimal. Clutter makes me anxious.", "zh-TW": "極簡。雜亂讓我焦慮。", ja: "ミニマル。散らかりは不安になる" },
  ]},
  { q: { en: "You procrastinate because...", "zh-TW": "你拖延是因為...", ja: "先延ばしする理由は..." }, opts: [
    { s: { qi_stagnant: 2 }, en: "I'm afraid it won't be perfect.", "zh-TW": "我怕它不夠完美。", ja: "完璧じゃないのが怖い" },
    { s: { qi_deficient: 2 }, en: "I genuinely don't have the energy to start.", "zh-TW": "我真的沒有能量開始。", ja: "本当に始めるエネルギーがない" },
    { s: { damp_heat: 2 }, en: "I don't procrastinate. I just do everything at the last minute.", "zh-TW": "我不拖延。我只是都在最後一刻做。", ja: "先延ばししない。ただ最後の瞬間にやる" },
    { s: { blood_stasis: 2 }, en: "Because I'm stuck between options and can't let go of any of them. Analysis paralysis is my middle name.", "zh-TW": "因為卡在選項之間，哪個都放不下。分析癱瘓是我的中間名。", ja: "選択肢の間で動けなくて、どれも手放せない。分析麻痺がミドルネーム" },
  ]},
  { q: { en: "Your creativity peaks when...", "zh-TW": "你的創造力在什麼時候達到巔峰...", ja: "創造性がピークなのは..." }, opts: [
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Late at night, when it's quiet and my thoughts are flowing.", "zh-TW": "深夜，安靜且思緒流動的時候。", ja: "深夜、静かで考えが流れる時" },
    { s: { sensitive: 2, qi_stagnant: 1 }, en: "When something triggers a deep emotion — a song, a memory, a random text from an old friend at 2 AM.", "zh-TW": "有東西觸發深層情緒的時候 — 一首歌、一段記憶、凌晨兩點老朋友的一條訊息。", ja: "深い感情がトリガーされた時 — 曲、記憶、深夜2時の古い友達からのメッセージ" },
    { s: { damp_heat: 2 }, en: "In high-energy, collaborative settings.", "zh-TW": "在高能量、合作的環境中。", ja: "高エネルギーな協力環境で" },
    { s: { blood_stasis: 2 }, en: "When I'm going through something difficult.", "zh-TW": "當我正在經歷困難的時候。", ja: "困難なことを経験している時" },
  ]},
  { q: { en: "You learn best by...", "zh-TW": "你最好的學習方式是...", ja: "一番の学習方法は..." }, opts: [
    { s: { blood_stasis: 2, qi_stagnant: 1 }, en: "By connecting everything to a personal story. If I can feel it, I remember it forever.", "zh-TW": "把一切都連結到自己的故事。有感覺就能永遠記住。", ja: "すべてを自分の物語に結びつける。感じれば永遠に覚えてる" },
    { s: { qi_stagnant: 2 }, en: "By reading and reflecting deeply.", "zh-TW": "閱讀和深度反思。", ja: "読んで深く考察" },
    { s: { damp_heat: 2 }, en: "By intense, focused immersion.", "zh-TW": "密集、專注的沉浸。", ja: "集中的で没頭する学習" },
    { s: { sensitive: 2, qi_deficient: 1 }, en: "Slowly and carefully — I need to feel confident.", "zh-TW": "慢慢地、謹慎地 — 我需要感到有信心。", ja: "ゆっくり慎重に — 自信が必要" },
  ]},
  { q: { en: "Under pressure, you...", "zh-TW": "壓力之下，你...", ja: "プレッシャーの下では..." }, opts: [
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "I slow down. Everything takes twice as long. My brain enters power-saving mode under stress.", "zh-TW": "我慢下來。所有事花兩倍時間。壓力下大腦自動進入省電模式。", ja: "遅くなる。すべてに2倍の時間がかかる。ストレス下では脳が省エネモードに" },
    { s: { damp_heat: 2 }, en: "I thrive. Pressure is my fuel.", "zh-TW": "我茁壯。壓力是我的燃料。", ja: "伸びる。プレッシャーは燃料" },
    { s: { qi_stagnant: 2, qi_deficient: 1 }, en: "I freeze. My mind goes blank.", "zh-TW": "我僵住。腦袋一片空白。", ja: "フリーズ。頭が真っ白" },
    { s: { yin_deficient: 2 }, en: "I get a burst of manic energy, then crash.", "zh-TW": "我會有一陣狂暴能量，然後崩潰。", ja: "マニックなエネルギーの爆発、その後バテる" },
  ]},
  { q: { en: "Your to-do list is...", "zh-TW": "你的待辦清單是...", ja: " ToDoリストは..." }, opts: [
    { s: { yin_deficient: 2 }, en: "Color-coded with timestamps, synced across three devices. I take my lists very, very personally.", "zh-TW": "用顏色標記加時間戳，三個裝置同步。我對清單非常非常認真。", ja: "カラー分け、タイムスタンプ付き、3デバイス同期。リストには超本気" },
    { s: { qi_stagnant: 2 }, en: "Long, detailed, and constantly rewritten.", "zh-TW": "冗長、詳細、不斷重寫。", ja: "長くて詳細で、常に書き直してる" },
    { s: { qi_deficient: 2 }, en: "Ambitious but half-finished.", "zh-TW": "雄心勃勃但完成一半。", ja: "野心的だけど半分終わり" },
    { s: { damp_heat: 2 }, en: "Aggressive and color-coded.", "zh-TW": "激進且用顏色標記。", ja: "アグレッシブでカラー分け" },
  ]},
  { q: { en: "You're drawn to...", "zh-TW": "你被什麼吸引...", ja: "惹かれるのは..." }, opts: [
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Warm reds and earth tones — fire, passion, intensity.", "zh-TW": "暖紅和大地色 — 火、熱情、強烈。", ja: "暖かい赤とアーストーン — 火、情熱、強さ" },
    { s: { yang_deficient: 1, sensitive: 1, qi_stagnant: 1 }, en: "Cool blues and deep greens — calm, depth, water.", "zh-TW": "冷藍和深綠 — 冷靜、深度、水。", ja: "クールな青と深い緑 — 静けさ、深さ、水" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Soft neutrals and creams — simplicity, light, air.", "zh-TW": "柔和中性色和米色 — 簡約、輕盈、空氣感。", ja: "柔らかいニュートラルとクリーム — シンプル、軽さ、空気" },
    { s: { damp_heat: 2, blood_stasis: 1 }, en: "Bold, saturated colors — life, energy, fullness.", "zh-TW": "大膽飽和色 — 生命、能量、豐滿。", ja: "鮮やかなビビッドカラー — 命、エネルギー、満ち足りた感じ" },
  ]},
  { q: { en: "Your dream home is...", "zh-TW": "你的夢想之家是...", ja: "理想の家は..." }, opts: [
    { s: { yang_deficient: 2 }, en: "A cozy cabin with a fireplace and warm blankets everywhere.", "zh-TW": "一個有壁爐的溫馨小木屋，到處都是暖被。", ja: "暖炉のあるコジーなロッジ、毛布が至る所に" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "A quiet hideaway with a view. Somewhere I can disappear into my own world for days.", "zh-TW": "一個有景的安靜避難所。可以消失在自己的世界裡好幾天的地方。", ja: "眺めのいい静かな隠れ家。自分の世界に何日も消えていられる場所" },
    { s: { damp_heat: 2 }, en: "A vibrant loft in the middle of a busy city.", "zh-TW": "繁華市中心一個充滿活力的閣樓。", ja: "賑やかな都市の真ん中の活気あるロフト" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "A quiet library-like space with books and soft lighting.", "zh-TW": "一個像圖書館一樣安靜的空間，有書和柔和燈光。", ja: "図書館のような静かな空間、本と柔らかい照明" },
  ]},
  { q: { en: "Your dream vacation is...", "zh-TW": "你的夢想假期是...", ja: "理想のバケーションは..." }, opts: [
    { s: { yang_deficient: 2, qi_stagnant: 1 }, en: "A cabin in the mountains. Fireplace, hot cocoa, zero people.", "zh-TW": "山裡的小木屋。壁爐、熱可可、零社交。", ja: "山の中のロッジ。暖炉、ホットココア、誰もいない" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "A tropical beach. Cold drinks, ocean breeze, doing absolutely nothing.", "zh-TW": "熱帶海灘。冷飲、海風、什麼都不做。", ja: "南国のビーチ。冷たい飲み物、潮風、何もしない" },
    { s: { phlegm_damp: 1, qi_deficient: 2 }, en: "A wellness retreat. Spa, yoga, healthy food, total reset.", "zh-TW": "靜修營。SPA、瑜伽、健康飲食、徹底重啟。", ja: "ウェルネスリトリート。スパ、ヨガ、ヘルシー食、リセット" },
    { s: { sensitive: 2, blood_stasis: 1 }, en: "Exploring a new city. Walking all day, discovering hidden gems.", "zh-TW": "探索新城市。走一整天、發現隱藏寶藏。", ja: "新しい街の探索。一日歩き、隠れた名所を発見" },
  ]},
  { q: { en: "Your music taste is...", "zh-TW": "你的音樂品味是...", ja: "音楽の好みは..." }, opts: [
    { s: { damp_heat: 2 }, en: "Loud, fast, high-energy — I want to feel something.", "zh-TW": "大聲、快節奏、高能量 — 我想要有感覺。", ja: "大音量、テンポ速い、高エネルギー — 何かを感じたい" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Moody and atmospheric — it matches my inner world.", "zh-TW": "有氛圍和情緒感的 — 它匹配我的內心世界。", ja: "ムーディでアトモスフィア — 内面の世界にマッチ" },
    { s: { sensitive: 2, qi_stagnant: 1 }, en: "Nostalgic. I have playlists for different eras of my life. Each one is a time machine.", "zh-TW": "懷舊的。我不同的人生階段都有歌單。每一個都是時光機。", ja: "ノスタルジック。人生の各時代のプレイリストがある。それぞれがタイムマシン" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Calm and acoustic — anything that helps me decompress.", "zh-TW": "平靜的、不插電的 — 任何能幫我減壓的。", ja: "落ち着いてアコースティック — リラックスできるもの" },
  ]},
  { q: { en: "Your morning starts with...", "zh-TW": "你的早晨從什麼開始...", ja: "朝の始まりは..." }, opts: [
    { s: { damp_heat: 2, qi_stagnant: 1 }, en: "Already planning the day before my feet hit the floor. My brain doesn't do slow mornings.", "zh-TW": "腳還沒落地就在規劃今天了。我的大腦不懂得慢早晨。", ja: "足が床につく前に今日の計画は完成。私の脳はゆっくり朝ができない" },
    { s: { qi_deficient: 2 }, en: "Reaching for my phone to delay the inevitable.", "zh-TW": "拿手機來延遲不可避免的起床。", ja: "スマホに手を伸ばして起きるのを遅らせる" },
    { s: { yin_deficient: 2 }, en: "Already awake — my mind started running an hour ago.", "zh-TW": "已經醒了 — 我的腦袋一小時前就開始跑了。", ja: "すでに起きてる — 頭は1時間前から動いてる" },
    { s: { damp_heat: 2 }, en: "Music on, coffee brewing, attacking the day.", "zh-TW": "音樂放著、咖啡煮著、攻擊這一天。", ja: "音楽ON、コーヒー淹れて、1日にアタック" },
  ]},
  { q: { en: "You collect...", "zh-TW": "你收集...", ja: "集めるのは..." }, opts: [
    { s: { blood_stasis: 2 }, en: "Memories and keepsakes — I hold onto everything.", "zh-TW": "回憶和紀念品 — 我什麼都留著。", ja: "思い出と記念品 — 全部残してる" },
    { s: { damp_heat: 2, yang_deficient: 1 }, en: "I collect moments — a photo of every sunset, every meal, every weird thing I see.", "zh-TW": "我收集時刻——每一個日落的照片、每一餐、每一個奇怪的東西。", ja: "瞬間を集める — 全夕日の写真、全食事、見かけた変なもの全部" },
    { s: { damp_heat: 2 }, en: "I don't collect — I consume. Everything is an experience.", "zh-TW": "我不收集 — 我消費。一切都是體驗。", ja: "集めない — 消費する。全てが体験" },
    { s: { qi_stagnant: 2 }, en: "Books, playlists, and thoughts. Lots of thoughts.", "zh-TW": "書、歌單、和想法。很多想法。", ja: "本、プレイリスト、思考。たくさんの思考" },
  ]},
  { q: { en: "Friday night, 10 PM. Your phone buzzes with a text. You glance at it and...", "zh-TW": "週五晚上十點。手機震了一下。你瞄了一眼...", ja: "金曜22時。スマホが震える。チラッと見て..." }, opts: [
    { s: { yang_deficient: 2, phlegm_damp: 1 }, en: "Reply immediately with a voice note. I process better out loud.", "zh-TW": "立刻回一條語音。我大聲說出來會想得更清楚。", ja: "すぐボイスメモで返す。声に出した方が整理できる" },
    { s: { qi_stagnant: 2 }, en: "Already drafting three different replies in your head and ranking them.", "zh-TW": "已經在腦中起草了三種回覆並開始排名。", ja: "すでに3パターンの返信を頭で作ってランキング中" },
    { s: { damp_heat: 2 }, en: "Ignore it — you're in the middle of something and nothing breaks your flow.", "zh-TW": "不理它 — 你正在做別的事，沒什麼能打斷你的節奏。", ja: "無視 — 今途中だし、流れは止められない" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Feel a wave of exhaustion just thinking about having to respond.", "zh-TW": "光想到要回覆就湧上一陣疲憊。", ja: "返信を考えただけで波のように疲れが来る" },
  ]},
  { q: { en: "No one's home. The whole evening is yours. You...", "zh-TW": "家裡沒人。整個晚上都是你的。你...", ja: "家に誰もいない。夜は全部自分のもの。あなたは..." }, opts: [
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Order way too much food, put on that show you've seen four times, and don't move for three hours.", "zh-TW": "點太多外送，打開那部已經看過四遍的劇，三小時不動。", ja: "食べすぎるほど注文して、4回目のドラマをつけて3時間動かない" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Somehow end up deep in a Wikipedia rabbit hole at 2 AM. How did I get here?", "zh-TW": "不知怎麼地在凌晨兩點掉進了維基百科的兔子洞。我怎麼到這的？", ja: "なぜか深夜2時にWikipediaの穴に落ちてる。なんでここに？" },
    { s: { qi_stagnant: 2 }, en: "Start journaling, accidentally write six pages about your entire life trajectory.", "zh-TW": "開始寫日記，不小心寫了六頁關於整個人生軌跡的東西。", ja: "日記を書き始めたら、気づけば人生の軌跡を6ページ書いてる" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "Put on music that matches my exact mood and have a whole cinematic moment alone.", "zh-TW": "放一首完全匹配心情的音樂，一個人上演一場電影時刻。", ja: "気分にぴったりの曲をかけて、一人でシネマティックな時間を過ごす" },
  ]},
  { q: { en: "Someone you just met asks 'so what are you like?' You...", "zh-TW": "剛認識的人問你「你是什麼樣的人？」你...", ja: "初めて会った人に「どんな人？」と聞かれて..." }, opts: [
    { s: { damp_heat: 2 }, en: "Tell them everything — you're an open book and you don't know how to be otherwise.", "zh-TW": "什麼都說了 — 你是打開的書，你也不知道怎麼做別的自己。", ja: "全部話す — オープンブックだし、他のやり方がわからない" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "Give a safe answer. The real answer requires three hours and probably some wine.", "zh-TW": "給一個安全的答案。真正的答案需要三小時，可能還要一些酒。", ja: "無難な答え。本当の答えには3時間と多分ワインが必要" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Shrug. You're still figuring that out, honestly.", "zh-TW": "聳聳肩。說實話，你自己也還在搞清楚。", ja: "肩をすくめる。正直、まだわかってない" },
    { s: { sensitive: 2, blood_stasis: 1 }, en: "Deflect with humor. Nobody's ready for the real answer. Including me.", "zh-TW": "用幽默閃躲。沒人準備好聽真正的答案。包括我自己。", ja: "ユーモアでかわす。本当の答えに誰も準備できてない。自分も" },
  ]},
  { q: { en: "You're packing for a week-long trip. Halfway through, you realize you...", "zh-TW": "你在打包一週旅行的行李。包到一半你發現...", ja: "1週間の旅行の荷造り。途中で気づく..." }, opts: [
    { s: { blood_stasis: 2 }, en: "Packed three books 'just in case' and the shirt your ex said looked good on you.", "zh-TW": "帶了三本書「以防萬一」，還有前任說穿著好看的那件襯衫。", ja: "念のため本を3冊と、元カレが似合うと言ったシャツを詰めた" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Brought way too many 'cozy options.' You will use all of them.", "zh-TW": "帶了太多「舒適選項」。你全部都會用到。", ja: "「くつろぎオプション」を詰め込みすぎた。全部使うつもり" },
    { s: { damp_heat: 2 }, en: "Forgot something obvious but brought three different outfits for 'vibes.'", "zh-TW": "忘了帶明顯的東西，但帶了三套不同「氛圍」的衣服。", ja: "大事なものを忘れたけど「ムード用」の服は3着持ってきた" },
    { s: { sensitive: 2, qi_stagnant: 1 }, en: "Packed four 'emergency outfits' because what if I feel different on Wednesday?", "zh-TW": "帶了四套「緊急穿搭」因為萬一週三我的心情變了呢？", ja: "「緊急用アウトフィット」を4着詰めた。水曜日に気分が変わったらどうする？" },
  ]},
  { q: { en: "It's 11 PM. Your brain decides it's the perfect time to...", "zh-TW": "晚上十一點。你的大腦覺得這是最佳時機來...", ja: "夜11時。脳が「今がベストタイミング」と判断して..." }, opts: [
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Replay that one conversation from 2016 with a better script.", "zh-TW": "重新播放2016年那次對話，配上更好的劇本。", ja: "2016年のあの会話をより良いセリフでリプレイする" },
    { s: { qi_stagnant: 2 }, en: "Plan an entire life change that you'll forget by morning.", "zh-TW": "規劃一場完整的人生改變，明早就忘了。", ja: "朝には忘れる完全な人生変更プランを立てる" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Convince you that you're not actually tired, just 'winding down.' You wind down until 2 AM.", "zh-TW": "說服你不是真的累，只是「慢慢放鬆」。你放鬆到凌晨兩點。", ja: "疲れてない「リラックス中」と言い聞かせる。深夜2時までリラックス" },
    { s: { qi_stagnant: 2, yang_deficient: 1 }, en: "Rewrite tomorrow's to-do list for the third time. With categories. And stickers.", "zh-TW": "第三次重寫明天的待辦清單。有分類。還有貼紙。", ja: "明日の ToDo リストを3回目の書き直し。カテゴリー付き。シールも貼る" },
  ]},
  { q: { en: "Your tongue — when you actually think about it — is usually...", "zh-TW": "你的舌頭——當你真的去想的時候——通常是...", ja: "あなたの舌 — 意識してみると — いつも..." }, opts: [
    { s: { balanced: 2 }, en: "A healthy pink. Honestly never thought about it until this very question.", "zh-TW": "健康的粉紅色。說真的直到被問才第一次認真想。", ja: "健康的なピンク。正直この質問まで考えたことなかった" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Pale, with teeth marks on the edges. Like it's been pressing against my teeth.", "zh-TW": "偏白，邊緣有齒痕。像是被牙齒壓著。", ja: "白っぽく、縁に歯形がある。歯に押されているみたい" },
    { s: { yin_deficient: 2 }, en: "Red — really red. With very little coating.", "zh-TW": "紅——真的很紅。幾乎沒有舌苔。", ja: "赤い — すごく赤い。舌苔がほとんどない" },
    { s: { blood_stasis: 2 }, en: "Dark or purplish. Sometimes with dark spots underneath.", "zh-TW": "偏暗或偏紫。有時底下有暗斑。", ja: "暗いか紫がかる。下に暗い斑点があることも" },
  ]},
  { q: { en: "People who meet you for the first time usually say you look...", "zh-TW": "第一次見你的人通常說你看起來...", ja: "初めて会う人はたいていあなたの見た目をこう言う..." }, opts: [
    { s: { balanced: 2 }, en: "Fine, apparently. No one has ever said anything about my face. Which is... good?", "zh-TW": "看起來還行。沒人對我的臉說過什麼。這應該...是好事吧？", ja: "まあまあらしい。顔について言われたことない。それは...良いこと？" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Tired. Even when I feel fine, they ask if I slept well.", "zh-TW": "累。就算我覺得還好，他們也問我睡得好不好。", ja: "疲れてる。元気でも「よく寝た？」と聞かれる" },
    { s: { damp_heat: 2 }, en: "Flushed or red-faced. Like I'm always running hot.", "zh-TW": "臉紅或面色偏紅。像一直在發熱。", ja: "顔が赤い。いつも暑がってるように見える" },
    { s: { phlegm_damp: 2 }, en: "Puffy or swollen. Like I'm retaining water all the time.", "zh-TW": "浮腫或虛胖。像我一直在水腫。", ja: "むくんでる。いつも水分を溜め込んでるみたい" },
  ]},
  { q: { en: "Your relationship with sweating is...", "zh-TW": "你跟出汗的關係是...", ja: "汗との関係は..." }, opts: [
    { s: { balanced: 2 }, en: "I sweat when it's hot or I exercise. Revolutionary, I know.", "zh-TW": "熱的時候或運動的時候流汗。很革命性的發現，我知道。", ja: "暑い時や運動時に汗をかく。画期的な発見だよね" },
    { s: { yang_deficient: 2, blood_stasis: 1 }, en: "I barely sweat. Even during exercise. It's like my pores forgot how.", "zh-TW": "幾乎不出汗。連運動都不太流汗。毛孔好像忘記怎麼工作了。", ja: "ほとんど汗をかかない。運動しても。毛穴が働き方を忘れたみたい" },
    { s: { damp_heat: 2, yin_deficient: 1 }, en: "I sweat easily and a lot. Even when it's not hot. My body just runs hot.", "zh-TW": "我很容易大量出汗。就算不熱也會。身體就是偏熱。", ja: "すぐたくさん汗をかく。暑くなくても。体が暑い" },
    { s: { yin_deficient: 2 }, en: "Night sweats. I wake up and my shirt is damp, even in cool weather.", "zh-TW": "盜汗。我醒來衣服是濕的，天氣涼也一樣。", ja: "寝汗。起きたらシャツが濡れてる。涼しい季節でも" },
  ]},
  { q: { en: "After a big meal, your stomach feels...", "zh-TW": "大餐之後，你的胃感覺...", ja: "食べすぎた後、胃の調子は..." }, opts: [
    { s: { balanced: 2 }, en: "Fine. My stomach and I have a respectful, drama-free relationship.", "zh-TW": "沒事。我的胃和我之間有互相尊重、零戲劇的關係。", ja: "問題なし。胃とは敬意を持ったドラマなしの関係" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "Bloated. Like a balloon for hours. Why did I do this to myself.", "zh-TW": "脹氣。像氣球撐了好幾個小時。我為什麼要這樣對自己。", ja: "膨満感。風船みたいに何時間も。なんでこんなことしたんだろ" },
    { s: { damp_heat: 2 }, en: "A bit acidic or burning. Like my stomach wants to reject what I just gave it.", "zh-TW": "有點反酸或灼熱。胃好像想拒絕我剛給它的東西。", ja: "少し酸っぱい or 焼ける。胃が受け付けないみたい" },
    { s: { qi_stagnant: 2 }, en: "Heavy and slow. Like my whole body shut down to process this.", "zh-TW": "沉重又遲鈍。全身好像關機來消化這頓飯。", ja: "重くてだるい。全身が消化のためにシャットダウンしたみたい" },
  ]},
  { q: { en: "Your skin has always been...", "zh-TW": "你的皮膚一直是...", ja: "あなたの肌はずっと..." }, opts: [
    { s: { balanced: 2 }, en: "Pretty chill. It does its thing and I do mine. We have an understanding.", "zh-TW": "蠻平靜的。它做它的事，我做我的。我們有默契。", ja: "けっこう平気。肌は肌のこと、私は私のこと。理解し合ってる" },
    { s: { yin_deficient: 2, blood_stasis: 1 }, en: "Dry. Sometimes itchy. Like it needs something it's not getting.", "zh-TW": "偏乾。有時會癢。像缺了什麼東西。", ja: "乾燥。かゆいことも。何かが足りないみたい" },
    { s: { damp_heat: 2 }, en: "Oily and active. Prone to breakouts, especially in humid weather.", "zh-TW": "偏油又活躍。容易長東西，特別是潮濕天氣。", ja: "脂性でアクティブ。吹き出物ができやすい、特に湿度が高い時" },
    { s: { sensitive: 2 }, en: "Reactive. New soap? New season? It has an opinion about everything.", "zh-TW": "很敏感。新肥皂？新季節？它對什麼都有意見。", ja: "過敏。新しい石鹸？新しい季節？何にでも意見がある" },
  ]},
  { q: { en: "Your body temperature on a normal day runs...", "zh-TW": "你正常情況下的體溫偏...", ja: "普通の日、体温は..." }, opts: [
    { s: { balanced: 2 }, en: "Comfortable. I literally never think about my body temperature. Lucky me.", "zh-TW": "舒服。我真的從來不會去想體溫這件事。算我好運。", ja: "快適。体温のことなんて考えたことない。ラッキー" },
    { s: { yang_deficient: 2 }, en: "Cool. My hands and feet are basically room-temperature objects.", "zh-TW": "偏涼。我的手腳基本上是室溫物體。", ja: "冷たい。手足は基本、室温の物体" },
    { s: { yin_deficient: 2, damp_heat: 1 }, en: "Warm to hot. I'm the one who's always opening windows.", "zh-TW": "偏熱。我是那個一直開窗的人。", ja: "温かいか熱い。いつも窓を開けてる人" },
    { s: { qi_stagnant: 2, blood_stasis: 1 }, en: "Depends on the day. Some days warm, some cold. Unpredictable.", "zh-TW": "看情況。有時熱有時冷。不太穩定。", ja: "日による。暑い日も寒い日も。予測不能" },
  ]},
  { q: { en: "When you wake up in the morning, you usually feel...", "zh-TW": "早上醒來，你通常覺得...", ja: "朝起きた時、いつも..." }, opts: [
    { s: { balanced: 2 }, en: "Functional. Give me 15 minutes and a coffee and I'm a person.", "zh-TW": "能運作。給我15分鐘和一杯咖啡我就是個人了。", ja: "機能する。15分とコーヒーをくれれば人間になれる" },
    { s: { qi_deficient: 2, phlegm_damp: 1 }, en: "Like I didn't sleep at all. The exhaustion is in my bones.", "zh-TW": "像根本沒睡過。疲憊在骨頭裡。", ja: "全然寝てない感じ。疲れが骨に染みてる" },
    { s: { qi_stagnant: 2, yin_deficient: 1 }, en: "My body is up but my brain is still processing last night.", "zh-TW": "身體醒了，但大腦還在處理昨晚的事。", ja: "体は起きてるけど脳は昨夜の処理中" },
    { s: { yang_deficient: 2 }, en: "Groggy and cold. I need warm things — tea, shower, sunlight — to feel human.", "zh-TW": "昏沉又冷。我需要溫暖的東西——茶、熱水、陽光——才能像個人。", ja: "ぼんやりして寒い。温かいもの — お茶、シャワー、日光 — がないと人間になれない" },
  ]},
  { q: { en: "Unexplained aches and pains — you get them...", "zh-TW": "不明原因的酸痛——你...", ja: "理由のない痛みやコリ — ..." }, opts: [
    { s: { balanced: 2 }, en: "Rarely. My body is low-key and I appreciate that about it.", "zh-TW": "很少。我的身體很低調，我對此很感恩。", ja: "めったに。体は控えめ、それに感謝してる" },
    { s: { yang_deficient: 2, qi_deficient: 1 }, en: "Lower back, knees — especially when it's cold or damp out.", "zh-TW": "腰和膝蓋——特別是又冷又濕的時候。", ja: "腰、膝 — 特に寒くて湿気のある時" },
    { s: { qi_stagnant: 2 }, en: "Headaches, tense shoulders, or a weird tight feeling in my chest.", "zh-TW": "頭痛、肩頸緊繃、或胸口一種奇怪的悶感。", ja: "頭痛、肩こり、胸の奇妙な締め付け感" },
    { s: { blood_stasis: 2 }, en: "Random spots that just show up. Bruises that take weeks to disappear.", "zh-TW": "隨機的地方突然痛。瘀青要好幾週才消。", ja: "ランダムな場所が痛む。あざが消えるのに何週間も" },
  ]},
  { q: { en: "Your thirst situation is...", "zh-TW": "你的口渴情況是...", ja: "喉の渇きは..." }, opts: [
    { s: { balanced: 2 }, en: "I drink water when I'm thirsty. Turns out that's the whole trick.", "zh-TW": "渴了就喝水。原來這就是全部的秘訣。", ja: "喉が渇いたら飲む。それが全部の秘訣だった" },
    { s: { phlegm_damp: 2, qi_deficient: 1 }, en: "I forget to drink. I'm basically never thirsty. Hours go by and I don't notice.", "zh-TW": "我忘記喝水。基本上不渴。過了好幾小時才發現。", ja: "飲むの忘れる。基本的に喉が渇かない。何時間も気づかない" },
    { s: { yin_deficient: 2 }, en: "Always thirsty. My mouth feels dry no matter how much I drink.", "zh-TW": "永遠在渴。不管喝多少嘴巴還是乾。", ja: "いつも喉が渇く。どれだけ飲んでも口が乾く" },
    { s: { yang_deficient: 2 }, en: "I prefer warm drinks. Cold water makes my stomach unhappy.", "zh-TW": "我偏愛溫熱的。冷水讓胃不舒服。", ja: "温かい飲み物が好き。冷水は胃が喜ばない" },
  ]},
  { q: { en: "Your digestion schedule is...", "zh-TW": "你的排便習慣是...", ja: "排泄のリズムは..." }, opts: [
    { s: { balanced: 2 }, en: "Like clockwork. I didn't realize this was a flex until I read the other options.", "zh-TW": "像時鐘一樣準時。看到其他選項才意識到這是值得炫耀的。", ja: "時計のように正確。他の選択肢を見て自慢できることだと気づいた" },
    { s: { qi_deficient: 2, yang_deficient: 1 }, en: "Unpredictable. Sometimes loose, sometimes fine. Depends on what I ate.", "zh-TW": "不太穩定。有時偏稀，有時正常。看我吃了什麼。", ja: "不規則。緩い時も普通の時も。食べたもの次第" },
    { s: { yin_deficient: 2, blood_stasis: 1 }, en: "On the slow side. Things move... eventually. I've accepted this.", "zh-TW": "偏慢。東西會動...最終。我已經接受了。", ja: "遅め。動くけど...最終的に。諦めてる" },
    { s: { damp_heat: 2 }, en: "Urgent. When it hits, it hits. There is no negotiation.", "zh-TW": "急迫。來了就是來了。沒得商量。", ja: "緊急。来る時は来る。交渉不可" },
  ]},
  ]
