import type { ConstitutionType, ConstitutionId } from "./types"

export const TYPES: Record<ConstitutionId, ConstitutionType> = {
  balanced: {
    id: "balanced",
    zh: "平和质",
    zhPy: "Píng Hé",
    en: "The Still Lake",
    line: "You're the 1 in 10 who got it right",
    color: "#C4A882",
    pct: "~30%",
    celebs: "The Dalai Lama, Kung Fu Panda (Po, post-training)",
  },
  qi_deficient: {
    id: "qi_deficient",
    zh: "气虚质",
    zhPy: "Qì Xū",
    en: "The Gentle Breeze",
    line: "Everything works, just needs a jumpstart",
    color: "#B8A472",
    pct: "~15%",
    celebs: "Mr. Rogers, Ikkyu-san, Lin-Manuel Miranda",
  },
  yang_deficient: {
    id: "yang_deficient",
    zh: "阳虚质",
    zhPy: "Yáng Xū",
    en: "The Moonlit Garden",
    line: "Sunlight is your superpower",
    color: "#7B9EB0",
    pct: "~10%",
    celebs: "Elsa from Frozen, early Vincent van Gogh, Thom Yorke",
  },
  yin_deficient: {
    id: "yin_deficient",
    zh: "阴虚质",
    zhPy: "Yīn Xū",
    en: "The Volcanic Spring",
    line: "Calm outside, volcanic inside",
    color: "#C75B3A",
    pct: "~10%",
    celebs: "Audrey Hepburn, Frida Kahlo, Céline from Before Sunset",
  },
  phlegm_damp: {
    id: "phlegm_damp",
    zh: "痰湿质",
    zhPy: "Tán Shī",
    en: "The Mossy Stone",
    line: "Your body moves slower than your mind",
    color: "#8E9B90",
    pct: "~8%",
    celebs: "Jack Black, Luis from Ant-Man, Paddington Bear",
  },
  damp_heat: {
    id: "damp_heat",
    zh: "湿热质",
    zhPy: "Shī Rè",
    en: "The Summer Storm",
    line: "Intensity is your default setting",
    color: "#8B7355",
    pct: "~8%",
    celebs: "Anthony Bourdain, Gordon Ramsay, Elizabeth Gilbert",
  },
  blood_stasis: {
    id: "blood_stasis",
    zh: "血瘀质",
    zhPy: "Xuè Yū",
    en: "The Frozen Stream",
    line: "Everything flows, just not fast enough",
    color: "#6B4C3B",
    pct: "~6%",
    celebs: "Neo from The Matrix, Lisbeth Salander, Prince",
  },
  qi_stagnant: {
    id: "qi_stagnant",
    zh: "气郁质",
    zhPy: "Qì Yù",
    en: "The Clouded Peak",
    line: "Your mind never stops, your body pays the price",
    color: "#9B8AA0",
    pct: "~8%",
    celebs: "Virginia Woolf, Will from Good Will Hunting, BoJack Horseman",
  },
  sensitive: {
    id: "sensitive",
    zh: "特禀质",
    zhPy: "Tè Bǐng",
    en: "The Wild Orchid",
    line: "You feel everything everyone else doesn't",
    color: "#A0C4B8",
    pct: "~5%",
    celebs: "Eleven from Stranger Things, Amélie Poulain, Spider-Man",
  },
}

export const TYPE_IDS = Object.keys(TYPES) as ConstitutionId[]
