export interface PromoCaption {
  en: string
  zh: string
}

export const PROMO_CAPTIONS: PromoCaption[] = [
  { en: "You're not lazy.\nYour body is speaking a language you haven't learned yet.", zh: "你不是懒。你的身体在说你还没学会的语言。" },
  { en: "That 3 PM crash?\nIt's not about coffee. It's about your constitution.", zh: "下午三点的崩溃？不是咖啡的事，是你的体质。" },
  { en: "You've been treating symptoms.\nYour body wants you to see the pattern.", zh: "你一直在治症状。你的身体想让你看到规律。" },
  { en: "Why do you wake up tired\nafter 8 hours of sleep?", zh: "睡了8小时还是累，为什么？" },
  { en: "Your body has been dropping hints for years.\nIt's time to read them.", zh: "你的身体已经暗示了好几年。该读懂它了。" },
  { en: "That bloating after every meal isn't random.\nYour body type explains why.", zh: "每次吃完都胀气，不是偶然。你的体质能解释。" },
  { en: "You don't need another supplement.\nYou need to understand your body.", zh: "你不需要又一个补品。你需要理解你的身体。" },
  { en: "Cold hands, cold feet, always cold.\nThere's a reason your thermostat is broken.", zh: "手冷脚冷，永远怕冷。你的恒温器坏了是有原因的。" },
  { en: "Why does anxiety show up\neven when nothing is wrong?", zh: "明明没事，为什么还是焦虑？" },
  { en: "Your body is not broken.\nIt's been trying to tell you something.", zh: "你的身体没坏。它一直在试图告诉你什么。" },
  { en: "3,000 years of wisdom says:\nyour fatigue has a name.", zh: "三千年的智慧说：你的疲劳有个名字。" },
  { en: "Stop Googling your symptoms.\nStart understanding your pattern.", zh: "别再搜索症状了。开始理解你的体质。" },
  { en: "Why can't you lose weight\nno matter what you eat?", zh: "为什么不管吃什么，都瘦不下来？" },
  { en: "Your sleep is broken. Your digestion is off.\nYour energy is gone. It's all connected.", zh: "睡不好、消化差、没精神。这些都是连着的。" },
  { en: "Some bodies run hot.\nSome run cold. Which one are you?", zh: "有些体质偏热，有些偏寒。你是哪种？" },
  { en: "That brain fog isn't age.\nIt might be your body type.", zh: "脑子不清醒不是因为年纪。可能是你的体质。" },
  { en: "Why do you crave sweets\nat 10 PM every night?", zh: "为什么每晚十点都特别想吃甜的？" },
  { en: "You've tried everything to fix your energy.\nHave you tried understanding where it went?", zh: "你试过所有办法提神。你试过理解能量去哪了吗？" },
  { en: "Your body has a type. Your food has a nature.\nWhen they match, everything changes.", zh: "你的身体有类型，你的食物有属性。对上了，一切都会变。" },
  { en: "Why does your stomach hate you\nafter every meal?", zh: "为什么每次吃完饭，胃都在抗议？" },
  { en: "Night sweats, hot flashes, can't cool down.\nYour body is not your enemy.", zh: "夜间盗汗、潮热、降不了温。你的身体不是你的敌人。" },
  { en: "The answer to \"why am I always tired\"\nisn't in a blood test.", zh: "「为什么总是累」的答案，验血查不出来。" },
  { en: "Your acne isn't a skin problem.\nIt's a body signal.", zh: "你的痘痘不是皮肤问题。是身体信号。" },
  { en: "Why do you wake up at 3 AM\nevery single night?", zh: "为什么每天凌晨三点都会醒？" },
  { en: "You eat healthy but still feel terrible.\nThe problem isn't the food. It's the match.", zh: "你吃得健康但还是不舒服。问题不在食物，在于搭配。" },
  { en: "That constant anxiety in your chest?\nEastern medicine calls it \"stuck energy.\"", zh: "胸口总堵着的那种焦虑？中医叫「气郁」。" },
  { en: "Your body is the only home\nyou'll ever live in.\nMaybe learn its floor plan.", zh: "你的身体是你唯一住一辈子的房子。也许该看看它的户型图。" },
  { en: "Why does your period make you\nwant to disappear?", zh: "为什么每次来月经都想消失？" },
  { en: "You're not weak.\nYou're running on the wrong fuel.", zh: "你不是虚弱。你是加错了油。" },
  { en: "Your body type decides which foods\nheal you and which ones drain you.", zh: "你的体质决定了哪些食物养你，哪些食物耗你。" },
  { en: "Why can you never finish a sentence\nwithout forgetting what you were saying?", zh: "为什么话到嘴边就忘了？" },
  { en: "You've been ignoring your body's emails\nfor years. Time to open them.", zh: "你忽视身体的邮件好多年了。该打开了。" },
  { en: "That weight you can't lose?\nIt might not be calories. It might be dampness.", zh: "怎么都减不掉的体重？可能不是热量的事，是「湿气」。" },
  { en: "Why do you feel anxious\nfor absolutely no reason?", zh: "为什么莫名其妙就焦虑了？" },
  { en: "Your digestion is the engine.\nYour constitution is the fuel type. Know your fuel.", zh: "消化是引擎，体质是油号。了解你的油。" },
  { en: "Why do your hands and feet\ngo numb even in summer?", zh: "为什么夏天手脚也会发麻？" },
  { en: "Some people heal with ginger.\nSome people get worse. Know which one you are.", zh: "有人吃姜好了，有人吃姜更差。你是哪种？" },
  { en: "You know something is off.\nYou just can't name it. We can help.", zh: "你知道哪里不对，就是说不上来。我们来帮你。" },
  { en: "Why does your face break out\nevery time you eat dairy?", zh: "为什么一吃奶制品就长痘？" },
  { en: "Your body isn't random.\nThere's a pattern. Find yours.", zh: "你的身体不是随机的。有一个规律。找到你的。" },
  { en: "That heavy, sluggish feeling\nthat never goes away?\nYour body is holding moisture.", zh: "那种永远消不掉的沉重感？你的身体在积水。" },
  { en: "Why can't you fall asleep\neven though you're exhausted?", zh: "明明累得不行，为什么就是睡不着？" },
  { en: "You don't need motivation.\nYou need a body that actually has energy.", zh: "你不需要动力。你需要一个真的有能量的身体。" },
  { en: "Why does your lower back ache\nevery single morning?", zh: "为什么每天早上腰都疼？" },
  { en: "Your body has been whispering.\nIf you don't listen, it will scream.", zh: "你的身体一直在低语。你不听，它就会喊。" },
  { en: "Why do you feel sick\nevery time the seasons change?", zh: "为什么每次换季都生病？" },
  { en: "What if one quiz could explain\nwhy you've been feeling off for years?", zh: "如果一个测试能解释你这些年为什么不舒服呢？" },
  { en: "You're not aging fast.\nYou're running the wrong operating system.", zh: "你不是老得快。你运行了错误的操作系统。" },
  { en: "Why do you get migraines\nevery time the weather changes?", zh: "为什么一变天就偏头痛？" },
  { en: "Your body already knows the answer.\nYou just need to ask the right question.", zh: "你的身体已经知道答案了。你只需要问对问题。" },
]
