export interface SymptomPage {
  slug: string
  title: { en: string; "zh-TW": string; ja: string }
  metaTitle: string
  metaDesc: string
  ogDesc: string
  h1: { en: string; "zh-TW": string; ja: string }
  tag: string
  readTime: string
  relatedTypes: string[]
  relatedSymptoms: string[]
}

export const SYMPTOMS: Record<string, SymptomPage> = {
  "why-am-i-always-tired": {
    slug: "why-am-i-always-tired",
    title: { en: "Why Am I Always Tired?", "zh-TW": "為什麼我總是累？", ja: "なぜいつも疲れている？" },
    metaTitle: "Why Am I Always Tired? Eastern Body Type Insights | EastType",
    metaDesc: "Always tired even after sleeping well? Learn why from a Traditional Chinese Medicine perspective — and which body type may be connected to your chronic fatigue.",
    ogDesc: "Sleeping well but still exhausted? TCM says your body type may explain why. Free 5-min assessment included.",
    h1: { en: "Why Am I Always Tired? What Your Body Type May Reveal", "zh-TW": "為什麼我總是累？你的體質可能透露什麼", ja: "なぜいつも疲れている？体質が明かすこと" },
    tag: "Fatigue",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yang_deficient"],
    relatedSymptoms: ["why-am-i-always-sleepy", "why-do-i-feel-anxious"],
  },
  "why-am-i-always-cold": {
    slug: "why-am-i-always-cold",
    title: { en: "Why Am I Always Cold?", "zh-TW": "為什麼我總是冷？", ja: "なぜいつも寒い？" },
    metaTitle: "Why Am I Always Cold? Eastern Body Type Insights | EastType",
    metaDesc: "Always cold when others are comfortable? Learn which Eastern body type is associated with cold sensitivity and what warming foods may help.",
    ogDesc: "Cold hands and feet year-round? Your Eastern body type may explain it. Learn which foods can warm you from the inside.",
    h1: { en: "Why Am I Always Cold? What Your Body Type May Reveal", "zh-TW": "為什麼我總是冷？你的體質可能透露什麼", ja: "なぜいつも寒い？体質が明かすこと" },
    tag: "Cold Sensitivity",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-do-i-wake-up-at-3am"],
  },
  "why-do-i-wake-up-at-3am": {
    slug: "why-do-i-wake-up-at-3am",
    title: { en: "Why Do I Wake Up at 3AM?", "zh-TW": "為什麼我凌晨三點會醒？", ja: "なぜ午前3時に目が覚める？" },
    metaTitle: "Why Do I Wake Up at 3AM? Eastern Body Type Insights | EastType",
    metaDesc: "Waking up at 3AM every night? Traditional Chinese Medicine connects this to specific body types. Learn what your sleep pattern may mean.",
    ogDesc: "3AM wakeups every night? TCM says your body type may be the reason. Find out which type and what may help.",
    h1: { en: "Why Do I Wake Up at 3AM? What Your Body Type May Reveal", "zh-TW": "為什麼我凌晨三點會醒？你的體質可能透露什麼", ja: "なぜ午前3時に目が覚める？体質が明かすこと" },
    tag: "Sleep",
    readTime: "7 min",
    relatedTypes: ["yin_deficient", "qi_stagnant"],
    relatedSymptoms: ["why-am-i-always-tired", "always-bloated-after-eating"],
  },
  "always-bloated-after-eating": {
    slug: "always-bloated-after-eating",
    title: { en: "Always Bloated After Eating", "zh-TW": "飯後總是脹氣", ja: "食後いつもお腹が張る" },
    metaTitle: "Always Bloated After Eating? Eastern Body Type Insights | EastType",
    metaDesc: "Bloated after every meal? Traditional Chinese Medicine links bloating to specific body types. Learn which foods may help reduce that heavy feeling.",
    ogDesc: "Bloated after meals? Your Eastern body type may explain it. Learn which foods are easier on your digestion.",
    h1: { en: "Always Bloated After Eating? What Your Body Type May Reveal", "zh-TW": "飯後總是脹氣？你的體質可能透露什麼", ja: "食後いつもお腹が張る？体質が明かすこと" },
    tag: "Digestion",
    readTime: "7 min",
    relatedTypes: ["qi_deficient", "phlegm_damp"],
    relatedSymptoms: ["why-am-i-always-tired", "why-am-i-always-sleepy"],
  },
  "why-am-i-always-sleepy": {
    slug: "why-am-i-always-sleepy",
    title: { en: "Why Am I Always Sleepy?", "zh-TW": "為什麼我總是想睡？", ja: "なぜいつも眠い？" },
    metaTitle: "Why Am I Always Sleepy? Eastern Body Type Insights | EastType",
    metaDesc: "Can't stay awake during the day? Your Eastern body type may explain daytime sleepiness. Learn which patterns are connected to low energy.",
    ogDesc: "Always sleepy no matter how much you sleep? Your body type may be the reason. Free assessment to find out.",
    h1: { en: "Why Am I Always Sleepy? What Your Body Type May Reveal", "zh-TW": "為什麼我總是想睡？你的體質可能透露什麼", ja: "なぜいつも眠い？体質が明かすこと" },
    tag: "Energy",
    readTime: "7 min",
    relatedTypes: ["qi_deficient", "phlegm_damp"],
    relatedSymptoms: ["why-am-i-always-tired", "always-bloated-after-eating"],
  },
  "why-do-i-have-night-sweats": {
    slug: "why-do-i-have-night-sweats",
    title: { en: "Why Do I Have Night Sweats?", "zh-TW": "為什麼我會盜汗？", ja: "なぜ寝汗をかく？" },
    metaTitle: "Why Do I Have Night Sweats? Eastern Body Type Insights | EastType",
    metaDesc: "Waking up drenched in sweat? Traditional Chinese Medicine connects night sweats to specific body types. Learn what your body may be telling you.",
    ogDesc: "Night sweats but no fever? TCM says your body type may explain it. Free assessment to find out.",
    h1: { en: "Why Do I Have Night Sweats? What Your Body Type May Reveal", "zh-TW": "為什麼我會盜汗？你的體質可能透露什麼", ja: "なぜ寝汗をかく？体質が明かすこと" },
    tag: "Night Sweats",
    readTime: "7 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-wake-up-at-3am", "why-is-my-hair-falling-out"],
  },
  "why-do-i-feel-anxious": {
    slug: "why-do-i-feel-anxious",
    title: { en: "Why Do I Feel Anxious?", "zh-TW": "為什麼我總是焦慮？", ja: "なぜ不安を感じる？" },
    metaTitle: "Why Do I Feel Anxious? Eastern Body Type Insights | EastType",
    metaDesc: "Anxious all the time for no clear reason? Traditional Chinese Medicine connects chronic anxiety to specific body types. Learn what your body may be telling you.",
    ogDesc: "Anxious but nothing is wrong? TCM says your body type may explain it. Free assessment to find out.",
    h1: { en: "Why Do I Feel Anxious? What Your Body Type May Reveal", "zh-TW": "為什麼我總是焦慮？你的體質可能透露什麼", ja: "なぜ不安を感じる？体質が明かすこと" },
    tag: "Anxiety",
    readTime: "7 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-wake-up-at-3am", "why-am-i-so-irritable"],
  },
  "why-do-i-have-brain-fog": {
    slug: "why-do-i-have-brain-fog",
    title: { en: "Why Do I Have Brain Fog?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Brain Fog? Eastern Body Type Insights | EastType",
    metaDesc: "Can't think clearly? Brain fog may be connected to your Eastern body type. Learn which TCM patterns are linked to mental fogginess and what may help clear it.",
    ogDesc: "Head in a cloud? Your Eastern body type may explain why your thinking feels foggy.",
    h1: { en: "Why Do I Have Brain Fog? When Your Head Lives in a Cloud", "zh-TW": "", ja: "" },
    tag: "Mental Clarity",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-sleepy", "always-bloated-after-eating"],
  },
  "why-cant-i-fall-asleep": {
    slug: "why-cant-i-fall-asleep",
    title: { en: "Why Can't I Fall Asleep?", "zh-TW": "", ja: "" },
    metaTitle: "Why Can't I Fall Asleep? Eastern Body Type Insights | EastType",
    metaDesc: "Lying awake for hours? Your Eastern body type may explain why you can't fall asleep. Learn which TCM patterns are linked to trouble falling asleep and what may help.",
    ogDesc: "Can't fall asleep even when you're exhausted? Your body type may hold the answer.",
    h1: { en: "Why Can't I Fall Asleep? The Nighttime Tug-of-War", "zh-TW": "", ja: "" },
    tag: "Sleep",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_stagnant"],
    relatedSymptoms: ["why-do-i-wake-up-at-3am", "why-do-i-have-night-sweats"],
  },
  "why-do-i-keep-gaining-weight": {
    slug: "why-do-i-keep-gaining-weight",
    title: { en: "Why Do I Keep Gaining Weight?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Keep Gaining Weight? Eastern Body Type Insights | EastType",
    metaDesc: "Gaining weight despite eating the same? Your Eastern body type may explain it. Learn which TCM patterns are linked to weight gain and what may help your metabolism.",
    ogDesc: "Eating the same but the scale keeps climbing? Your body type may explain why.",
    h1: { en: "Why Do I Keep Gaining Weight? The Soggy Metabolism", "zh-TW": "", ja: "" },
    tag: "Weight",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["always-bloated-after-eating", "why-am-i-always-tired"],
  },
  "why-are-my-moods-all-over-the-place": {
    slug: "why-are-my-moods-all-over-the-place",
    title: { en: "Why Are My Moods All Over the Place?", "zh-TW": "", ja: "" },
    metaTitle: "Why Are My Moods All Over the Place? Eastern Body Type Insights | EastType",
    metaDesc: "Mood swings that come out of nowhere? Your Eastern body type may explain unpredictable emotions. Learn which TCM patterns are linked to emotional instability.",
    ogDesc: "Fine one minute, furious or tearful the next? Your body type may be behind it.",
    h1: { en: "Why Are My Moods All Over the Place? The Internal Pressure Cooker", "zh-TW": "", ja: "" },
    tag: "Emotional",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-feel-anxious", "why-do-i-wake-up-at-3am"],
  },
  "why-do-i-get-sick-so-often": {
    slug: "why-do-i-get-sick-so-often",
    title: { en: "Why Do I Get Sick So Often?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Get Sick So Often? Eastern Body Type Insights | EastType",
    metaDesc: "Always catching every cold going around? Your Eastern body type may explain low immunity. Learn which TCM patterns are linked to frequent illness.",
    ogDesc: "Every cold, every flu season? Your body type may explain it.",
    h1: { en: "Why Do I Get Sick So Often? The Body That Forgot Its Shield", "zh-TW": "", ja: "" },
    tag: "Immunity",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yang_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-am-i-always-cold"],
  },
  "why-do-my-hands-and-feet-go-numb": {
    slug: "why-do-my-hands-and-feet-go-numb",
    title: { en: "Why Do My Hands and Feet Go Numb?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do My Hands and Feet Go Numb? Eastern Body Type Insights | EastType",
    metaDesc: "Numb or tingling hands and feet? Your Eastern body type may explain poor circulation. Learn which TCM patterns are linked to numbness.",
    ogDesc: "Tingling, numbness, pins and needles? Your body type may explain it.",
    h1: { en: "Why Do My Hands and Feet Go Numb? When Your Extremities Check Out", "zh-TW": "", ja: "" },
    tag: "Circulation",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-cold", "why-am-i-always-tired"],
  },
  "why-is-my-skin-so-dry": {
    slug: "why-is-my-skin-so-dry",
    title: { en: "Why Is My Skin So Dry?", "zh-TW": "", ja: "" },
    metaTitle: "Why Is My Skin So Dry? Eastern Body Type Insights | EastType",
    metaDesc: "Dry skin that no moisturizer fixes? Your Eastern body type may explain it. Learn which TCM patterns are linked to chronic dryness.",
    ogDesc: "Lotion every day and still dry? Your body type may explain it.",
    h1: { en: "Why Is My Skin So Dry? The Moisture That Disappeared", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-do-i-wake-up-at-3am"],
  },
  "why-do-i-crave-sweets": {
    slug: "why-do-i-crave-sweets",
    title: { en: "Why Do I Crave Sweets?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Crave Sweets? Eastern Body Type Insights | EastType",
    metaDesc: "Can't stop craving sugar? Your Eastern body type may explain sweet cravings. Learn which TCM patterns are linked to sugar addiction.",
    ogDesc: "Always reaching for something sweet? Your body type may explain why.",
    h1: { en: "Why Do I Crave Sweets? The Sweet Tooth That Runs Deeper Than Willpower", "zh-TW": "", ja: "" },
    tag: "Cravings",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["always-bloated-after-eating", "why-do-i-keep-gaining-weight"],
  },
  "why-do-i-overthink-everything": {
    slug: "why-do-i-overthink-everything",
    title: { en: "Why Do I Overthink Everything?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Overthink Everything? Eastern Body Type Insights | EastType",
    metaDesc: "Can't stop replaying conversations in your head? Your Eastern body type may explain overthinking. Learn which TCM patterns are linked to racing thoughts.",
    ogDesc: "Stuck in a mental loop you can't escape? Your body type may explain it.",
    h1: { en: "Why Do I Overthink Everything? The Mind That Won't Put the Pen Down", "zh-TW": "", ja: "" },
    tag: "Mental",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-feel-anxious", "why-are-my-moods-all-over-the-place"],
  },
  "why-am-i-always-unmotivated": {
    slug: "why-am-i-always-unmotivated",
    title: { en: "Why Am I Always Unmotivated?", "zh-TW": "", ja: "" },
    metaTitle: "Why Am I Always Unmotivated? Eastern Body Type Insights | EastType",
    metaDesc: "No drive to do anything, even things you used to enjoy? Your Eastern body type may explain chronic low motivation. Learn which TCM patterns are linked to apathy.",
    ogDesc: "Can't get going no matter what? Your body type may explain why motivation feels out of reach.",
    h1: { en: "Why Am I Always Unmotivated? The Engine That Won't Turn Over", "zh-TW": "", ja: "" },
    tag: "Motivation",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yang_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-do-i-get-sick-so-often"],
  },
  "why-do-i-keep-breaking-out": {
    slug: "why-do-i-keep-breaking-out",
    title: { en: "Why Do I Keep Breaking Out?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Keep Breaking Out? Eastern Body Type Insights | EastType",
    metaDesc: "Persistent acne that won't respond to skincare? Your Eastern body type may explain recurring breakouts. Learn which TCM patterns are linked to skin issues.",
    ogDesc: "Tried every skincare product and still breaking out? Your body type may hold the answer.",
    h1: { en: "Why Do I Keep Breaking Out? The Skin That's Telling a Deeper Story", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["why-do-i-keep-gaining-weight", "why-do-i-crave-sweets"],
  },
  "why-is-my-hair-falling-out": {
    slug: "why-is-my-hair-falling-out",
    title: { en: "Why Is My Hair Falling Out?", "zh-TW": "", ja: "" },
    metaTitle: "Why Is My Hair Falling Out? Eastern Body Type Insights | EastType",
    metaDesc: "More hair in the brush than on your head? Your Eastern body type may explain hair thinning. Learn which TCM patterns are linked to hair loss.",
    ogDesc: "Watching your hair thin and don't know why? Your body type may explain it.",
    h1: { en: "Why Is My Hair Falling Out? The Roots That Lost Their Grip", "zh-TW": "", ja: "" },
    tag: "Hair",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-is-my-skin-so-dry"],
  },
  "why-am-i-so-irritable": {
    slug: "why-am-i-so-irritable",
    title: { en: "Why Am I So Irritable?", "zh-TW": "", ja: "" },
    metaTitle: "Why Am I So Irritable? Eastern Body Type Insights | EastType",
    metaDesc: "Snapping at people for no reason? Your Eastern body type may explain chronic irritability. Learn which TCM patterns are linked to a short fuse.",
    ogDesc: "Everything getting on your nerves? Your body type may explain why your patience is always running thin.",
    h1: { en: "Why Am I So Irritable? The Short Fuse That Keeps Getting Shorter", "zh-TW": "", ja: "" },
    tag: "Emotional",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-are-my-moods-all-over-the-place", "why-do-i-feel-anxious"],
  },
  "why-cant-i-lose-weight": {
    slug: "why-cant-i-lose-weight",
    title: { en: "Why Can't I Lose Weight?", "zh-TW": "", ja: "" },
    metaTitle: "Why Can't I Lose Weight? Eastern Body Type Insights | EastType",
    metaDesc: "Trying to lose weight but nothing works? Your Eastern body type may explain a sluggish metabolism. Learn which TCM patterns are linked to stubborn weight.",
    ogDesc: "Dieting but the scale won't move? Your body type may explain why your metabolism is stuck.",
    h1: { en: "Why Can't I Lose Weight? The Metabolism That Refuses to Budge", "zh-TW": "", ja: "" },
    tag: "Weight",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["why-do-i-keep-gaining-weight", "why-do-i-crave-sweets", "always-bloated-after-eating"],
  },
  "why-do-i-have-acid-reflux": {
    slug: "why-do-i-have-acid-reflux",
    title: { en: "Why Do I Have Acid Reflux?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Acid Reflux? Eastern Body Type Insights | EastType",
    metaDesc: "Burning in your chest after meals? Your Eastern body type may explain chronic acid reflux. Learn which TCM patterns are linked to heartburn.",
    ogDesc: "That burning feeling keeps coming back? Your body type may explain why reflux won't go away.",
    h1: { en: "Why Do I Have Acid Reflux? The Fire That Rises When It Shouldn't", "zh-TW": "", ja: "" },
    tag: "Digestion",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "damp_heat"],
    relatedSymptoms: ["always-bloated-after-eating", "why-am-i-always-sleepy", "why-do-i-have-brain-fog"],
  },
  "why-do-i-have-headaches": {
    slug: "why-do-i-have-headaches",
    title: { en: "Why Do I Have Headaches?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Headaches? Eastern Body Type Insights | EastType",
    metaDesc: "Frequent headaches with no clear cause? Your Eastern body type may explain recurring head pain. Learn which TCM patterns are linked to headaches.",
    ogDesc: "Headaches keep coming back and nothing fixes them? Your body type may hold the answer.",
    h1: { en: "Why Do I Have Headaches? The Pressure That Has Nowhere to Go", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant", "yin_deficient"],
    relatedSymptoms: ["why-do-i-feel-anxious", "why-am-i-so-irritable", "why-do-i-overthink-everything"],
  },
  "why-do-i-feel-dizzy": {
    slug: "why-do-i-feel-dizzy",
    title: { en: "Why Do I Feel Dizzy?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Feel Dizzy? Eastern Body Type Insights | EastType",
    metaDesc: "Dizzy spells that come and go without warning? Your Eastern body type may explain dizziness. Learn which TCM patterns are linked to feeling lightheaded.",
    ogDesc: "World spinning for no reason? Your body type may explain why your head feels unsteady.",
    h1: { en: "Why Do I Feel Dizzy? The Ground That Shifts Under Your Feet", "zh-TW": "", ja: "" },
    tag: "Dizziness",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yin_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-am-i-always-sleepy", "why-do-i-get-sick-so-often"],
  },
  "why-am-i-always-thirsty": {
    slug: "why-am-i-always-thirsty",
    title: { en: "Why Am I Always Thirsty?", "zh-TW": "", ja: "" },
    metaTitle: "Why Am I Always Thirsty? Eastern Body Type Insights | EastType",
    metaDesc: "Can't quench your thirst no matter how much you drink? Your Eastern body type may explain constant thirst. Learn which TCM patterns are linked to dry mouth.",
    ogDesc: "Always reaching for water but never satisfied? Your body type may explain why.",
    h1: { en: "Why Am I Always Thirsty? The Well That Never Fills", "zh-TW": "", ja: "" },
    tag: "Thirst",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-cant-i-fall-asleep", "why-is-my-skin-so-dry"],
  },
  "why-do-i-have-lower-back-pain": {
    slug: "why-do-i-have-lower-back-pain",
    title: { en: "Why Do I Have Lower Back Pain?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Lower Back Pain? Eastern Body Type Insights | EastType",
    metaDesc: "Chronic lower back pain with no clear injury? Your Eastern body type may explain it. Learn which TCM patterns are linked to persistent lower back ache.",
    ogDesc: "Back hurts but nothing showed up on the scan? Your body type may explain why your lower back keeps aching.",
    h1: { en: "Why Do I Have Lower Back Pain? The Foundation That Lost Its Support", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-cold", "why-am-i-always-tired"],
  },
  "why-do-i-have-eczema": {
    slug: "why-do-i-have-eczema",
    title: { en: "Why Do I Have Eczema?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Eczema? Eastern Body Type Insights | EastType",
    metaDesc: "Eczema that keeps coming back no matter what you apply? Your Eastern body type may explain recurring eczema. Learn which TCM patterns are linked to skin flare-ups.",
    ogDesc: "Cream after cream but the eczema keeps returning? Your body type may explain what your skin is trying to tell you.",
    h1: { en: "Why Do I Have Eczema? The Skin That Speaks in Flare-Ups", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_stagnant"],
    relatedSymptoms: ["why-is-my-skin-so-dry", "why-do-i-feel-anxious"],
  },
  "why-do-i-sweat-so-much": {
    slug: "why-do-i-sweat-so-much",
    title: { en: "Why Do I Sweat So Much?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Sweat So Much? Eastern Body Type Insights | EastType",
    metaDesc: "Sweating excessively even when it's not hot? Your Eastern body type may explain heavy sweating. Learn which TCM patterns are linked to excessive perspiration.",
    ogDesc: "Sweating through your shirt when everyone else is fine? Your body type may explain why your internal thermostat is stuck on high.",
    h1: { en: "Why Do I Sweat So Much? The Thermostat That Won't Turn Down", "zh-TW": "", ja: "" },
    tag: "Sweating",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yin_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-am-i-always-tired"],
  },
  "why-do-i-have-joint-pain": {
    slug: "why-do-i-have-joint-pain",
    title: { en: "Why Do I Have Joint Pain?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Joint Pain? Eastern Body Type Insights | EastType",
    metaDesc: "Aching joints with no injury or arthritis diagnosis? Your Eastern body type may explain joint pain. Learn which TCM patterns are linked to stiff, achy joints.",
    ogDesc: "Joints ache but the doctor says nothing is wrong? Your body type may explain why your joints feel stiff and sore.",
    h1: { en: "Why Do I Have Joint Pain? The Hinges That Lost Their Oil", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "blood_stasis"],
    relatedSymptoms: ["why-am-i-always-cold", "why-do-my-hands-and-feet-go-numb"],
  },
  "why-am-i-always-thirsty-at-night": {
    slug: "why-am-i-always-thirsty-at-night",
    title: { en: "Why Am I Always Thirsty at Night?", "zh-TW": "", ja: "" },
    metaTitle: "Why Am I Always Thirsty at Night? Eastern Body Type Insights | EastType",
    metaDesc: "Waking up thirsty every night? Your Eastern body type may explain nighttime thirst. Learn which TCM patterns are linked to dry mouth that disrupts sleep.",
    ogDesc: "Can't sleep because you're always reaching for water? Your body type may explain why nighttime thirst won't quit.",
    h1: { en: "Why Am I Always Thirsty at Night? The Midnight Dry Spell", "zh-TW": "", ja: "" },
    tag: "Sleep",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-am-i-always-thirsty", "why-do-i-wake-up-at-3am", "why-do-i-have-night-sweats"],
  },
  "why-do-i-have-hot-flashes": {
    slug: "why-do-i-have-hot-flashes",
    title: { en: "Why Do I Have Hot Flashes?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Hot Flashes? Eastern Body Type Insights | EastType",
    metaDesc: "Sudden waves of heat rushing through your body? Your Eastern body type may explain hot flashes. Learn which TCM patterns are linked to heat surges.",
    ogDesc: "Heat rising from nowhere and flushing your face? Your body type may explain why your internal thermostat keeps spiking.",
    h1: { en: "Why Do I Have Hot Flashes? The Heat That Rises Without Warning", "zh-TW": "", ja: "" },
    tag: "Heat",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "damp_heat"],
    relatedSymptoms: ["why-am-i-always-thirsty", "why-do-i-have-night-sweats"],
  },
  "why-do-i-have-water-retention": {
    slug: "why-do-i-have-water-retention",
    title: { en: "Why Do I Have Water Retention?", "zh-TW": "", ja: "" },
    metaTitle: "Why Do I Have Water Retention? Eastern Body Type Insights | EastType",
    metaDesc: "Puffy, swollen, or heavy from fluid buildup? Your Eastern body type may explain water retention. Learn which TCM patterns are linked to holding onto moisture.",
    ogDesc: "Rings tight, face puffy, legs heavy? Your body type may explain why your body holds onto water it should be releasing.",
    h1: { en: "Why Do I Have Water Retention? The Sponge That Won't Wring Out", "zh-TW": "", ja: "" },
    tag: "Swelling",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp"],
    relatedSymptoms: ["always-bloated-after-eating", "why-do-i-keep-gaining-weight"],
  },
  "why-am-i-always-constipated": {
    slug: "why-am-i-always-constipated",
    title: { en: "Why Am I Always Constipated?", "zh-TW": "", ja: "" },
    metaTitle: "Why Am I Always Constipated? Eastern Body Type Insights | EastType",
    metaDesc: "Chronic constipation that fiber doesn't fix? Your Eastern body type may explain it. Learn which TCM patterns are linked to sluggish bowel movements.",
    ogDesc: "Eating fiber and drinking water but still blocked? Your body type may explain why your digestion can't get things moving.",
    h1: { en: "Why Am I Always Constipated? The Pipe That Forgot How to Flow", "zh-TW": "", ja: "" },
    tag: "Digestion",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "yin_deficient"],
    relatedSymptoms: ["why-do-i-have-acid-reflux", "always-bloated-after-eating"],
  },
}

export const SYMPTOM_SLUGS = Object.keys(SYMPTOMS)
