export interface SymptomPage {
  slug: string
  title: { en: string; "zh-TW": string; ja: string }
  metaTitle: string
  metaDesc: string
  ogDesc: string
  h1: { en: string; "zh-TW": string; ja: string }
  tag: string
  readTime: string
  relatedTypes: string[]
  relatedSymptoms: string[]
}

export const SYMPTOMS: Record<string, SymptomPage> = {
  "why-am-i-always-tired": {
    slug: "why-am-i-always-tired",
    title: { en: "Why Am I Always Tired?", "zh-TW": "為什麼我總是累？", ja: "なぜいつも疲れている？" },
    metaTitle: "Always Tired? You're Not Lazy — Your Body Type May Be Why",
    metaDesc: "Sleep 8 hours and still exhausted? It might be your body type, not your sleep. Simple food changes may help more than coffee. Free 5-min quiz.",
    ogDesc: "Sleeping well but still exhausted? Eastern wellness says your body type may explain why. Free 5-min assessment included.",
    h1: { en: "Why Am I Always Tired? What Your Body Type May Reveal", "zh-TW": "為什麼我總是累？你的體質可能透露什麼", ja: "なぜいつも疲れている？体質が明かすこと" },
    tag: "Fatigue",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yang_deficient"],
    relatedSymptoms: ["why-am-i-always-sleepy", "why-do-i-feel-anxious"],
  },
  "why-am-i-always-cold": {
    slug: "why-am-i-always-cold",
    title: { en: "Why Am I Always Cold?", "zh-TW": "為什麼我總是冷？", ja: "なぜいつも寒い？" },
    metaTitle: "Always Cold? It's Not Just Winter — Your Body Type Matters",
    metaDesc: "Wearing 3 layers while others are fine? Your inner furnace might need help. See which warming foods may help. Free body type quiz.",
    ogDesc: "Cold hands and feet year-round? Your Eastern body type may explain it. Learn which foods can warm you from the inside.",
    h1: { en: "Why Am I Always Cold? What Your Body Type May Reveal", "zh-TW": "為什麼我總是冷？你的體質可能透露什麼", ja: "なぜいつも寒い？体質が明かすこと" },
    tag: "Cold Sensitivity",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-do-i-wake-up-at-3am"],
  },
  "why-do-i-wake-up-at-3am": {
    slug: "why-do-i-wake-up-at-3am",
    title: { en: "Why Do I Wake Up at 3AM?", "zh-TW": "為什麼我凌晨三點會醒？", ja: "なぜ午前3時に目が覚める？" },
    metaTitle: "Wake Up at 3AM Every Night? Your Body Is Sending a Signal",
    metaDesc: "Same time every night? In Eastern wellness, 3AM means something specific. A simple tea may help you sleep through. Free quiz.",
    ogDesc: "3AM wakeups every night? Eastern wellness says your body type may be the reason. Find out which type and what may help.",
    h1: { en: "Why Do I Wake Up at 3AM? What Your Body Type May Reveal", "zh-TW": "為什麼我凌晨三點會醒？你的體質可能透露什麼", ja: "なぜ午前3時に目が覚める？体質が明かすこと" },
    tag: "Sleep",
    readTime: "7 min",
    relatedTypes: ["yin_deficient", "qi_stagnant"],
    relatedSymptoms: ["why-am-i-always-tired", "always-bloated-after-eating"],
  },
  "always-bloated-after-eating": {
    slug: "always-bloated-after-eating",
    title: { en: "Always Bloated After Eating", "zh-TW": "飯後總是脹氣", ja: "食後いつもお腹が張る" },
    metaTitle: "Bloated After Every Meal? It's Not What You Eat — It's Your Body Type",
    metaDesc: "Feel like a balloon after normal meals? Your digestion might be running cold. One tea before meals may help. Free 5-min quiz.",
    ogDesc: "Bloated after meals? Your Eastern body type may explain it. Learn which foods are easier on your digestion.",
    h1: { en: "Always Bloated After Eating? What Your Body Type May Reveal", "zh-TW": "飯後總是脹氣？你的體質可能透露什麼", ja: "食後いつもお腹が張る？体質が明かすこと" },
    tag: "Digestion",
    readTime: "7 min",
    relatedTypes: ["qi_deficient", "phlegm_damp"],
    relatedSymptoms: ["why-am-i-always-tired", "why-am-i-always-sleepy"],
  },
  "why-am-i-always-sleepy": {
    slug: "why-am-i-always-sleepy",
    title: { en: "Why Am I Always Sleepy?", "zh-TW": "為什麼我總是想睡？", ja: "なぜいつも眠い？" },
    metaTitle: "Always Sleepy During the Day? Your Body Type Drains Your Battery",
    metaDesc: "Can't stay awake even after sleeping? It might be your body type, not your sleep schedule. Simple foods may help. Free quiz.",
    ogDesc: "Always sleepy no matter how much you sleep? Your body type may be the reason. Free assessment to find out.",
    h1: { en: "Why Am I Always Sleepy? What Your Body Type May Reveal", "zh-TW": "為什麼我總是想睡？你的體質可能透露什麼", ja: "なぜいつも眠い？体質が明かすこと" },
    tag: "Energy",
    readTime: "7 min",
    relatedTypes: ["qi_deficient", "phlegm_damp"],
    relatedSymptoms: ["why-am-i-always-tired", "always-bloated-after-eating"],
  },
  "why-do-i-have-night-sweats": {
    slug: "why-do-i-have-night-sweats",
    title: { en: "Why Do I Have Night Sweats?", "zh-TW": "為什麼我會盜汗？", ja: "なぜ寝汗をかく？" },
    metaTitle: "Night Sweats Every Night? Your Body Is Overheating From Within",
    metaDesc: "Waking up drenched but the room isn't hot? Your body type may be running too warm internally. Cooling foods may help. Free quiz.",
    ogDesc: "Night sweats but no fever? Eastern wellness says your body type may explain it. Free assessment to find out.",
    h1: { en: "Why Do I Have Night Sweats? What Your Body Type May Reveal", "zh-TW": "為什麼我會盜汗？你的體質可能透露什麼", ja: "なぜ寝汗をかく？体質が明かすこと" },
    tag: "Night Sweats",
    readTime: "7 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-wake-up-at-3am", "why-is-my-hair-falling-out"],
  },
  "why-do-i-feel-anxious": {
    slug: "why-do-i-feel-anxious",
    title: { en: "Why Do I Feel Anxious?", "zh-TW": "為什麼我總是焦慮？", ja: "なぜ不安を感じる？" },
    metaTitle: "Anxious for No Reason? Your Chest Might Be Holding Something",
    metaDesc: "Racing heart, tight chest, can't sit still? It might not be stress. Your body type could be the cause. Free 5-min quiz.",
    ogDesc: "Anxious but nothing is wrong? Eastern wellness says your body type may explain it. Free assessment to find out.",
    h1: { en: "Why Do I Feel Anxious? What Your Body Type May Reveal", "zh-TW": "為什麼我總是焦慮？你的體質可能透露什麼", ja: "なぜ不安を感じる？体質が明かすこと" },
    tag: "Anxiety",
    readTime: "7 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-wake-up-at-3am", "why-am-i-so-irritable"],
  },
  "why-do-i-have-brain-fog": {
    slug: "why-do-i-have-brain-fog",
    title: { en: "Why Do I Have Brain Fog?", "zh-TW": "", ja: "" },
    metaTitle: "Brain Fog Won't Lift? Your Body Type Might Be Clouding Your Mind",
    metaDesc: "Can't think clearly? Forgetting what you were saying? Your body type might be the reason, not just lack of sleep. Free quiz.",
    ogDesc: "Head in a cloud? Your Eastern body type may explain why your thinking feels foggy.",
    h1: { en: "Why Do I Have Brain Fog? When Your Head Lives in a Cloud", "zh-TW": "", ja: "" },
    tag: "Mental Clarity",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-sleepy", "always-bloated-after-eating"],
  },
  "why-cant-i-fall-asleep": {
    slug: "why-cant-i-fall-asleep",
    title: { en: "Why Can't I Fall Asleep?", "zh-TW": "", ja: "" },
    metaTitle: "Can't Fall Asleep? Your Body Type Won't Let Your Mind Shut Off",
    metaDesc: "Body exhausted but mind won't stop? It might be your body type running too hot. One calming tea may help. Free quiz.",
    ogDesc: "Can't fall asleep even when you're exhausted? Your body type may hold the answer.",
    h1: { en: "Why Can't I Fall Asleep? The Nighttime Tug-of-War", "zh-TW": "", ja: "" },
    tag: "Sleep",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_stagnant"],
    relatedSymptoms: ["why-do-i-wake-up-at-3am", "why-do-i-have-night-sweats"],
  },
  "why-do-i-keep-gaining-weight": {
    slug: "why-do-i-keep-gaining-weight",
    title: { en: "Why Do I Keep Gaining Weight?", "zh-TW": "", ja: "" },
    metaTitle: "Keep Gaining Weight? It Might Not Be the Calories",
    metaDesc: "Eating the same but the scale keeps climbing? Your body type might be holding water, not fat. Draining foods may help. Free quiz.",
    ogDesc: "Eating the same but the scale keeps climbing? Your body type may explain why.",
    h1: { en: "Why Do I Keep Gaining Weight? The Soggy Metabolism", "zh-TW": "", ja: "" },
    tag: "Weight",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["always-bloated-after-eating", "why-am-i-always-tired"],
  },
  "why-are-my-moods-all-over-the-place": {
    slug: "why-are-my-moods-all-over-the-place",
    title: { en: "Why Are My Moods All Over the Place?", "zh-TW": "", ja: "" },
    metaTitle: "Mood Swings Out of Nowhere? Your Body Type Might Be the Storm",
    metaDesc: "Fine one minute, furious the next? It might not be hormones alone. Your body type could be driving the swings. Free quiz.",
    ogDesc: "Fine one minute, furious or tearful the next? Your body type may be behind it.",
    h1: { en: "Why Are My Moods All Over the Place? The Internal Pressure Cooker", "zh-TW": "", ja: "" },
    tag: "Emotional",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-feel-anxious", "why-do-i-wake-up-at-3am"],
  },
  "why-do-i-get-sick-so-often": {
    slug: "why-do-i-get-sick-so-often",
    title: { en: "Why Do I Get Sick So Often?", "zh-TW": "", ja: "" },
    metaTitle: "Always Getting Sick? Your Body Type Might Have Weak Defenses",
    metaDesc: "Catching every cold that goes around? Your body type might mean your immune shield has gaps. Simple foods may help. Free quiz.",
    ogDesc: "Every cold, every flu season? Your body type may explain it.",
    h1: { en: "Why Do I Get Sick So Often? The Body That Forgot Its Shield", "zh-TW": "", ja: "" },
    tag: "Immunity",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yang_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-am-i-always-cold"],
  },
  "why-do-my-hands-and-feet-go-numb": {
    slug: "why-do-my-hands-and-feet-go-numb",
    title: { en: "Why Do My Hands and Feet Go Numb?", "zh-TW": "", ja: "" },
    metaTitle: "Numb Hands and Feet? Your Circulation Might Be Too Slow",
    metaDesc: "Tingling, numbness, pins and needles? Your body type might be why blood can't reach your extremities. Warming foods may help. Free quiz.",
    ogDesc: "Tingling, numbness, pins and needles? Your body type may explain it.",
    h1: { en: "Why Do My Hands and Feet Go Numb? When Your Extremities Check Out", "zh-TW": "", ja: "" },
    tag: "Circulation",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-cold", "why-am-i-always-tired"],
  },
  "why-is-my-skin-so-dry": {
    slug: "why-is-my-skin-so-dry",
    title: { en: "Why Is My Skin So Dry?", "zh-TW": "", ja: "" },
    metaTitle: "Dry Skin That Lotion Won't Fix? The Problem Is From Within",
    metaDesc: "Moisturizing every day and still flaky? Your body type might mean your internal hydration is empty. Certain foods may help. Free quiz.",
    ogDesc: "Lotion every day and still dry? Your body type may explain it.",
    h1: { en: "Why Is My Skin So Dry? The Moisture That Disappeared", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-do-i-wake-up-at-3am"],
  },
  "why-do-i-crave-sweets": {
    slug: "why-do-i-crave-sweets",
    title: { en: "Why Do I Crave Sweets?", "zh-TW": "", ja: "" },
    metaTitle: "Can't Stop Craving Sweets? Your Body Type Might Be Begging for Fuel",
    metaDesc: "Need dessert every night? 3PM sugar crash? Your body type might be driving the craving, not your willpower. Free quiz.",
    ogDesc: "Always reaching for something sweet? Your body type may explain why.",
    h1: { en: "Why Do I Crave Sweets? The Sweet Tooth That Runs Deeper Than Willpower", "zh-TW": "", ja: "" },
    tag: "Cravings",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["always-bloated-after-eating", "why-do-i-keep-gaining-weight"],
  },
  "why-do-i-overthink-everything": {
    slug: "why-do-i-overthink-everything",
    title: { en: "Why Do I Overthink Everything?", "zh-TW": "", ja: "" },
    metaTitle: "Can't Stop Overthinking? Your Body Type Won't Let Your Mind Rest",
    metaDesc: "Thoughts looping endlessly? Can't make decisions? Your body type might be why your brain won't power down. Free quiz.",
    ogDesc: "Stuck in a mental loop you can't escape? Your body type may explain it.",
    h1: { en: "Why Do I Overthink Everything? The Mind That Won't Put the Pen Down", "zh-TW": "", ja: "" },
    tag: "Mental",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-feel-anxious", "why-are-my-moods-all-over-the-place"],
  },
  "why-am-i-always-unmotivated": {
    slug: "why-am-i-always-unmotivated",
    title: { en: "Why Am I Always Unmotivated?", "zh-TW": "", ja: "" },
    metaTitle: "No Motivation? You're Not Lazy — Your Body Type Might Be Why",
    metaDesc: "Can't get going no matter what? Your body type might mean your engine has fuel but no spark. Simple foods may help. Free quiz.",
    ogDesc: "Can't get going no matter what? Your body type may explain why motivation feels out of reach.",
    h1: { en: "Why Am I Always Unmotivated? The Engine That Won't Turn Over", "zh-TW": "", ja: "" },
    tag: "Motivation",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yang_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-do-i-get-sick-so-often"],
  },
  "why-do-i-keep-breaking-out": {
    slug: "why-do-i-keep-breaking-out",
    title: { en: "Why Do I Keep Breaking Out?", "zh-TW": "", ja: "" },
    metaTitle: "Breaking Out Nonstop? Your Skin Is an Exit Door for Internal Heat",
    metaDesc: "Tried every skincare product? Your breakouts might be coming from inside. Cooling foods may help where creams can't. Free quiz.",
    ogDesc: "Tried every skincare product and still breaking out? Your body type may hold the answer.",
    h1: { en: "Why Do I Keep Breaking Out? The Skin That's Telling a Deeper Story", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["why-do-i-keep-gaining-weight", "why-do-i-crave-sweets"],
  },
  "why-is-my-hair-falling-out": {
    slug: "why-is-my-hair-falling-out",
    title: { en: "Why Is My Hair Falling Out?", "zh-TW": "", ja: "" },
    metaTitle: "Hair Falling Out? Your Deepest Energy Reserves Might Be Running Low",
    metaDesc: "More hair on your brush than your head? Your body type might be why. Nourishing foods may help from within. Free quiz.",
    ogDesc: "Watching your hair thin and don't know why? Your body type may explain it.",
    h1: { en: "Why Is My Hair Falling Out? The Roots That Lost Their Grip", "zh-TW": "", ja: "" },
    tag: "Hair",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-is-my-skin-so-dry"],
  },
  "why-am-i-so-irritable": {
    slug: "why-am-i-so-irritable",
    title: { en: "Why Am I So Irritable?", "zh-TW": "", ja: "" },
    metaTitle: "Always Irritable? Your Body Type Might Be the Short Fuse",
    metaDesc: "Snapping at everyone? Everything annoys you? Your body type might be why patience feels impossible. Free 5-min quiz.",
    ogDesc: "Everything getting on your nerves? Your body type may explain why your patience is always running thin.",
    h1: { en: "Why Am I So Irritable? The Short Fuse That Keeps Getting Shorter", "zh-TW": "", ja: "" },
    tag: "Emotional",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-are-my-moods-all-over-the-place", "why-do-i-feel-anxious"],
  },
  "why-cant-i-lose-weight": {
    slug: "why-cant-i-lose-weight",
    title: { en: "Why Can't I Lose Weight?", "zh-TW": "", ja: "" },
    metaTitle: "Can't Lose Weight? It Might Be Water, Not Fat",
    metaDesc: "Dieting but the scale won't move? Your body type might be holding water, not fat. Draining foods may help. Free quiz.",
    ogDesc: "Dieting but the scale won't move? Your body type may explain why your metabolism is stuck.",
    h1: { en: "Why Can't I Lose Weight? The Metabolism That Refuses to Budge", "zh-TW": "", ja: "" },
    tag: "Weight",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["why-do-i-keep-gaining-weight", "why-do-i-crave-sweets", "always-bloated-after-eating"],
  },
  "why-do-i-have-acid-reflux": {
    slug: "why-do-i-have-acid-reflux",
    title: { en: "Why Do I Have Acid Reflux?", "zh-TW": "", ja: "" },
    metaTitle: "Acid Reflux Won't Quit? Internal Heat Might Be Pushing It Up",
    metaDesc: "Burning chest after meals? Your body type might be running too hot. Cooling foods may help where antacids only mask it. Free quiz.",
    ogDesc: "That burning feeling keeps coming back? Your body type may explain why reflux won't go away.",
    h1: { en: "Why Do I Have Acid Reflux? The Fire That Rises When It Shouldn't", "zh-TW": "", ja: "" },
    tag: "Digestion",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "damp_heat"],
    relatedSymptoms: ["always-bloated-after-eating", "why-am-i-always-sleepy", "why-do-i-have-brain-fog"],
  },
  "why-do-i-have-headaches": {
    slug: "why-do-i-have-headaches",
    title: { en: "Why Do I Have Headaches?", "zh-TW": "", ja: "" },
    metaTitle: "Frequent Headaches? Pressure Might Be Building From Within",
    metaDesc: "Headaches keep coming back? Your body type might be why tension or heat is collecting in your head. Free quiz.",
    ogDesc: "Headaches keep coming back and nothing fixes them? Your body type may hold the answer.",
    h1: { en: "Why Do I Have Headaches? The Pressure That Has Nowhere to Go", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant", "yin_deficient"],
    relatedSymptoms: ["why-do-i-feel-anxious", "why-am-i-so-irritable", "why-do-i-overthink-everything"],
  },
  "why-do-i-feel-dizzy": {
    slug: "why-do-i-feel-dizzy",
    title: { en: "Why Do I Feel Dizzy?", "zh-TW": "", ja: "" },
    metaTitle: "Dizzy Spells? Your Brain Might Not Be Getting Enough Fuel",
    metaDesc: "Lightheaded standing up? Room spinning? Your body type might be why energy can't reach your head. Free quiz.",
    ogDesc: "World spinning for no reason? Your body type may explain why your head feels unsteady.",
    h1: { en: "Why Do I Feel Dizzy? The Ground That Shifts Under Your Feet", "zh-TW": "", ja: "" },
    tag: "Dizziness",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yin_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-am-i-always-sleepy", "why-do-i-get-sick-so-often"],
  },
  "why-am-i-always-thirsty": {
    slug: "why-am-i-always-thirsty",
    title: { en: "Why Am I Always Thirsty?", "zh-TW": "", ja: "" },
    metaTitle: "Always Thirsty? Water Might Not Be the Answer",
    metaDesc: "Can't quench your thirst no matter how much you drink? Your body type might be why moisture can't stay inside. Free quiz.",
    ogDesc: "Always reaching for water but never satisfied? Your body type may explain why.",
    h1: { en: "Why Am I Always Thirsty? The Well That Never Fills", "zh-TW": "", ja: "" },
    tag: "Thirst",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-cant-i-fall-asleep", "why-is-my-skin-so-dry"],
  },
  "why-do-i-have-lower-back-pain": {
    slug: "why-do-i-have-lower-back-pain",
    title: { en: "Why Do I Have Lower Back Pain?", "zh-TW": "", ja: "" },
    metaTitle: "Lower Back Pain? Your Deepest Energy Battery Might Be Draining",
    metaDesc: "Back aches but nothing showed on the scan? Your body type might be why your foundation feels weak. Free quiz.",
    ogDesc: "Back hurts but nothing showed up on the scan? Your body type may explain why your lower back keeps aching.",
    h1: { en: "Why Do I Have Lower Back Pain? The Foundation That Lost Its Support", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-cold", "why-am-i-always-tired"],
  },
  "why-do-i-have-eczema": {
    slug: "why-do-i-have-eczema",
    title: { en: "Why Do I Have Eczema?", "zh-TW": "", ja: "" },
    metaTitle: "Eczema Keeps Coming Back? The Trigger Might Be Inside",
    metaDesc: "Cream after cream but it keeps returning? Your body type might be why heat and dampness push through your skin. Free quiz.",
    ogDesc: "Cream after cream but the eczema keeps returning? Your body type may explain what your skin is trying to tell you.",
    h1: { en: "Why Do I Have Eczema? The Skin That Speaks in Flare-Ups", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_stagnant"],
    relatedSymptoms: ["why-is-my-skin-so-dry", "why-do-i-feel-anxious"],
  },
  "why-do-i-sweat-so-much": {
    slug: "why-do-i-sweat-so-much",
    title: { en: "Why Do I Sweat So Much?", "zh-TW": "", ja: "" },
    metaTitle: "Sweating Too Much? Your Internal Thermostat Might Be Stuck",
    metaDesc: "Sweating through your shirt when others are fine? Your body type might be why your pores won't close. Free quiz.",
    ogDesc: "Sweating through your shirt when everyone else is fine? Your body type may explain why your internal thermostat is stuck on high.",
    h1: { en: "Why Do I Sweat So Much? The Thermostat That Won't Turn Down", "zh-TW": "", ja: "" },
    tag: "Sweating",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yin_deficient"],
    relatedSymptoms: ["why-do-i-have-night-sweats", "why-am-i-always-tired"],
  },
  "why-do-i-have-joint-pain": {
    slug: "why-do-i-have-joint-pain",
    title: { en: "Why Do I Have Joint Pain?", "zh-TW": "", ja: "" },
    metaTitle: "Aching Joints? Cold and Dampness Might Be Camping Inside",
    metaDesc: "Joints ache but no arthritis? Your body type might be why stiffness settles in. Warming foods may help. Free quiz.",
    ogDesc: "Joints ache but the doctor says nothing is wrong? Your body type may explain why your joints feel stiff and sore.",
    h1: { en: "Why Do I Have Joint Pain? The Hinges That Lost Their Oil", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "blood_stasis"],
    relatedSymptoms: ["why-am-i-always-cold", "why-do-my-hands-and-feet-go-numb"],
  },
  "why-am-i-always-thirsty-at-night": {
    slug: "why-am-i-always-thirsty-at-night",
    title: { en: "Why Am I Always Thirsty at Night?", "zh-TW": "", ja: "" },
    metaTitle: "Thirsty All Night? Your Body Dries Out While You Sleep",
    metaDesc: "Waking up parched every night? Your body type might be why your cooling system runs dry overnight. Free quiz.",
    ogDesc: "Can't sleep because you're always reaching for water? Your body type may explain why nighttime thirst won't quit.",
    h1: { en: "Why Am I Always Thirsty at Night? The Midnight Dry Spell", "zh-TW": "", ja: "" },
    tag: "Sleep",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-am-i-always-thirsty", "why-do-i-wake-up-at-3am", "why-do-i-have-night-sweats"],
  },
  "why-do-i-have-hot-flashes": {
    slug: "why-do-i-have-hot-flashes",
    title: { en: "Why Do I Have Hot Flashes?", "zh-TW": "", ja: "" },
    metaTitle: "Hot Flashes? Your Body Type Sends Heat Without Warning",
    metaDesc: "Sudden heat rushing through your body? Your body type might be why your thermostat keeps spiking. Free quiz.",
    ogDesc: "Heat rising from nowhere and flushing your face? Your body type may explain why your internal thermostat keeps spiking.",
    h1: { en: "Why Do I Have Hot Flashes? The Heat That Rises Without Warning", "zh-TW": "", ja: "" },
    tag: "Heat",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "damp_heat"],
    relatedSymptoms: ["why-am-i-always-thirsty", "why-do-i-have-night-sweats"],
  },
  "why-do-i-have-water-retention": {
    slug: "why-do-i-have-water-retention",
    title: { en: "Why Do I Have Water Retention?", "zh-TW": "", ja: "" },
    metaTitle: "Puffy and Swollen? Your Body Might Be Holding Water It Can't Drain",
    metaDesc: "Rings tight, face puffy, legs heavy? Your body type might be why your drainage system is clogged. Free quiz.",
    ogDesc: "Rings tight, face puffy, legs heavy? Your body type may explain why your body holds onto water it should be releasing.",
    h1: { en: "Why Do I Have Water Retention? The Sponge That Won't Wring Out", "zh-TW": "", ja: "" },
    tag: "Swelling",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp"],
    relatedSymptoms: ["always-bloated-after-eating", "why-do-i-keep-gaining-weight"],
  },
  "why-am-i-always-constipated": {
    slug: "why-am-i-always-constipated",
    title: { en: "Why Am I Always Constipated?", "zh-TW": "", ja: "" },
    metaTitle: "Always Constipated? Your Intestines Might Not Have Enough Energy",
    metaDesc: "Fiber and water but still stuck? Your body type might be why your digestion can't push things through. Free quiz.",
    ogDesc: "Eating fiber and drinking water but still blocked? Your body type may explain why your digestion can't get things moving.",
    h1: { en: "Why Am I Always Constipated? The Pipe That Forgot How to Flow", "zh-TW": "", ja: "" },
    tag: "Digestion",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "yin_deficient"],
    relatedSymptoms: ["why-do-i-have-acid-reflux", "always-bloated-after-eating"],
  },
  "why-is-my-libido-low": {
    slug: "why-is-my-libido-low",
    title: { en: "Why Is My Libido Low?", "zh-TW": "", ja: "" },
    metaTitle: "Low Libido? Your Body's Deepest Fire Might Be Burning Low",
    metaDesc: "Desire just disappeared? Your body type might be why your deepest energy reserves are running on empty. Free quiz.",
    ogDesc: "Desire just disappeared one day and never came back? Your body type may explain why your drive went quiet.",
    h1: { en: "Why Is My Libido Low? The Drive That Went on Strike", "zh-TW": "", ja: "" },
    tag: "Energy",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-am-i-always-cold"],
  },
  "why-do-i-have-pms": {
    slug: "why-do-i-have-pms",
    title: { en: "Why Do I Have PMS?", "zh-TW": "", ja: "" },
    metaTitle: "Severe PMS Every Month? Your Body Type Might Be the Storm",
    metaDesc: "Mood swings, bloating, cramps before every period? Your body type might be why PMS hits you so hard. Free quiz.",
    ogDesc: "Every month your body stages a rebellion before your period? Your body type may explain why PMS hits you so hard.",
    h1: { en: "Why Do I Have PMS? The Monthly Rebellion Your Body Stages", "zh-TW": "", ja: "" },
    tag: "Hormonal",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-are-my-moods-all-over-the-place", "why-do-i-feel-anxious"],
  },
  "why-is-my-metabolism-so-slow": {
    slug: "why-is-my-metabolism-so-slow",
    title: { en: "Why Is My Metabolism So Slow?", "zh-TW": "", ja: "" },
    metaTitle: "Slow Metabolism? Your Internal Furnace Might Be Barely Lit",
    metaDesc: "Eating less but still not losing weight? Your body type might be why your metabolism is stuck in first gear. Free quiz.",
    ogDesc: "Hardly eating and still gaining weight? Your body type may explain why your metabolism is stuck in first gear.",
    h1: { en: "Why Is My Metabolism So Slow? The Engine Running in First Gear", "zh-TW": "", ja: "" },
    tag: "Metabolism",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "qi_deficient"],
    relatedSymptoms: ["why-cant-i-lose-weight", "why-do-i-keep-gaining-weight"],
  },
  "why-do-i-have-poor-circulation": {
    slug: "why-do-i-have-poor-circulation",
    title: { en: "Why Do I Have Poor Circulation?", "zh-TW": "", ja: "" },
    metaTitle: "Poor Circulation? Your Blood River Might Have Too Many Dams",
    metaDesc: "Cold hands, cold feet, bruises easily? Your body type might be why blood can't flow freely. Free quiz.",
    ogDesc: "Hands blue, feet numb, always freezing? Your body type may explain why your circulation is running on low.",
    h1: { en: "Why Do I Have Poor Circulation? The River That Slowed to a Trickle", "zh-TW": "", ja: "" },
    tag: "Circulation",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "blood_stasis"],
    relatedSymptoms: ["why-am-i-always-cold", "why-do-my-hands-and-feet-go-numb"],
  },
  "why-do-i-have-seasonal-allergies": {
    slug: "why-do-i-have-seasonal-allergies",
    title: { en: "Why Do I Have Seasonal Allergies?", "zh-TW": "", ja: "" },
    metaTitle: "Allergies Won't Quit? Your Body Type Might Be Overreacting",
    metaDesc: "Every spring your body fights pollen like a war? Your body type might be why your defenses overreact. Free quiz.",
    ogDesc: "Every spring your body declares war on pollen? Your body type may explain why your immune system overreacts.",
    h1: { en: "Why Do I Have Seasonal Allergies? The Body That Overreacts to Every Season", "zh-TW": "", ja: "" },
    tag: "Immunity",
    readTime: "8 min",
    relatedTypes: ["sensitive"],
    relatedSymptoms: ["why-do-i-get-sick-so-often", "why-do-i-have-eczema"],
  },
  "why-do-i-have-dark-circles": {
    slug: "why-do-i-have-dark-circles",
    title: { en: "Why Do I Have Dark Circles?", "zh-TW": "", ja: "" },
    metaTitle: "Dark Circles Won't Go Away? It's Not Just Lack of Sleep",
    metaDesc: "Sleeping fine but still look exhausted? Your body type might be why those shadows won't fade. Free quiz.",
    ogDesc: "Sleeping fine but still look exhausted? Your body type may explain why those dark circles won't go away.",
    h1: { en: "Why Do I Have Dark Circles? The Shadows Sleep Can't Erase", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-is-my-skin-so-dry"],
  },
  "why-am-i-always-hungry": {
    slug: "why-am-i-always-hungry",
    title: { en: "Why Am I Always Hungry?", "zh-TW": "", ja: "" },
    metaTitle: "Always Hungry? Your Body Might Not Be Absorbing What You Eat",
    metaDesc: "Just ate but already thinking about food? Your body type might be why your stomach never sends the full signal. Free quiz.",
    ogDesc: "Just ate but already thinking about the next meal? Your body type may explain why your hunger never shuts off.",
    h1: { en: "Why Am I Always Hungry? The Stomach That Never Sends the 'Full' Signal", "zh-TW": "", ja: "" },
    tag: "Appetite",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "yin_deficient"],
    relatedSymptoms: ["why-do-i-crave-sweets", "why-do-i-keep-gaining-weight"],
  },
  "why-do-i-have-period-cramps": {
    slug: "why-do-i-have-period-cramps",
    title: { en: "Why Do I Have Period Cramps?", "zh-TW": "", ja: "" },
    metaTitle: "Painful Period Cramps? Cold Might Be Freezing the Flow",
    metaDesc: "Curled up in bed every month? Your body type might be why cold and stuck blood makes your period painful. Free quiz.",
    ogDesc: "Curled up in bed every month? Your body type may explain why your cramps feel like a small war.",
    h1: { en: "Why Do I Have Period Cramps? The Monthly Siege on Your Lower Belly", "zh-TW": "", ja: "" },
    tag: "Women's Health",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant", "blood_stasis"],
    relatedSymptoms: ["why-do-i-have-pms", "why-are-my-moods-all-over-the-place"],
  },
  "why-is-my-period-irregular": {
    slug: "why-is-my-period-irregular",
    title: { en: "Why Is My Period Irregular?", "zh-TW": "", ja: "" },
    metaTitle: "Irregular Periods? Your Body Clock Might Be Running Low on Energy",
    metaDesc: "Never know when your period will come? Your body type might be why your cycle can't stay on schedule. Free quiz.",
    ogDesc: "Never know when your period will show up? Your body type may explain why your cycle has a mind of its own.",
    h1: { en: "Why Is My Period Irregular? The Clock That Won't Keep Time", "zh-TW": "", ja: "" },
    tag: "Women's Health",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant", "yang_deficient"],
    relatedSymptoms: ["why-do-i-have-pms", "why-do-i-have-period-cramps"],
  },
  "why-is-my-period-so-heavy": {
    slug: "why-is-my-period-so-heavy",
    title: { en: "Why Is My Period So Heavy?", "zh-TW": "", ja: "" },
    metaTitle: "Heavy Periods? Your Body Might Not Be Holding What It Should",
    metaDesc: "Soaking through pads every month? Your body type might be why your body can't contain the flow. Free quiz.",
    ogDesc: "Your period feels like a flood every month? Your body type may explain why the flow never lets up.",
    h1: { en: "Why Is My Period So Heavy? The Flood That Won't Stop", "zh-TW": "", ja: "" },
    tag: "Women's Health",
    readTime: "8 min",
    relatedTypes: ["blood_stasis", "qi_deficient"],
    relatedSymptoms: ["why-do-i-have-period-cramps", "why-do-i-feel-dizzy"],
  },
  "why-do-i-have-breast-tenderness": {
    slug: "why-do-i-have-breast-tenderness",
    title: { en: "Why Do I Have Breast Tenderness?", "zh-TW": "", ja: "" },
    metaTitle: "Breast Tenderness Before Your Period? Stuck Energy Might Be Pooling",
    metaDesc: "Can't stand your bra the week before your period? Your body type might be why energy gets stuck in your chest. Free quiz.",
    ogDesc: "Can't stand your bra the week before your period? Your body type may explain why your breasts feel like bruised fruit.",
    h1: { en: "Why Do I Have Breast Tenderness? The Bruises That Arrive on Schedule", "zh-TW": "", ja: "" },
    tag: "Women's Health",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-have-pms", "why-do-i-have-period-cramps"],
  },
  "why-do-i-have-menopause-symptoms": {
    slug: "why-do-i-have-menopause-symptoms",
    title: { en: "Why Do I Have Menopause Symptoms?", "zh-TW": "", ja: "" },
    metaTitle: "Menopause Symptoms? Your Cooling and Warming Systems Might Be Off",
    metaDesc: "Hot flashes, night sweats, mood swings? Your body type might be why the transition feels so rough. Free quiz.",
    ogDesc: "Hot one minute, freezing the next? Your body type may explain why menopause feels like a rollercoaster.",
    h1: { en: "Why Do I Have Menopause Symptoms? The Thermostat That Lost Its Manual", "zh-TW": "", ja: "" },
    tag: "Women's Health",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "qi_stagnant"],
    relatedSymptoms: ["why-do-i-have-hot-flashes", "why-do-i-have-night-sweats"],
  },
  "why-do-i-have-nausea": {
    slug: "why-do-i-have-nausea",
    title: { en: "Why Do I Have Nausea?", "zh-TW": "", ja: "" },
    metaTitle: "Always Nauseous? Your Stomach Energy Might Be Flowing the Wrong Way",
    metaDesc: "Queasy for no clear reason? Your body type might be why your stomach keeps trying to reject food. Free quiz.",
    ogDesc: "Stomach turning for no obvious reason? Your body type may explain why nausea keeps coming back.",
    h1: { en: "Why Do I Have Nausea? The Stomach That Keeps Threatening to Strike", "zh-TW": "", ja: "" },
    tag: "Digestion",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp"],
    relatedSymptoms: ["always-bloated-after-eating", "why-am-i-always-constipated"],
  },
  "why-do-i-have-diarrhea": {
    slug: "why-do-i-have-diarrhea",
    title: { en: "Why Do I Have Diarrhea?", "zh-TW": "", ja: "" },
    metaTitle: "Chronic Diarrhea? Your Digestion Might Be Running Too Fast or Too Hot",
    metaDesc: "Always rushing to the bathroom? Your body type might be why your gut can't slow down. Free quiz.",
    ogDesc: "Always rushing to the bathroom? Your body type may explain why your digestion runs too fast.",
    h1: { en: "Why Do I Have Diarrhea? The Pipe That Flushes Too Fast", "zh-TW": "", ja: "" },
    tag: "Digestion",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "damp_heat"],
    relatedSymptoms: ["always-bloated-after-eating", "why-am-i-always-constipated"],
  },
  "why-do-i-feel-sick-after-eating": {
    slug: "why-do-i-feel-sick-after-eating",
    title: { en: "Why Do I Feel Sick After Eating?", "zh-TW": "", ja: "" },
    metaTitle: "Sick After Every Meal? Your Digestion Engine Might Be Stalling",
    metaDesc: "Eating used to feel fine but now it doesn't? Your body type might be why your stomach can't process fuel. Free quiz.",
    ogDesc: "Eating used to feel good. Now it feels like a chore? Your body type may explain why meals don't sit right anymore.",
    h1: { en: "Why Do I Feel Sick After Eating? The Welcome Mat Your Stomach Pulled In", "zh-TW": "", ja: "" },
    tag: "Digestion",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "phlegm_damp"],
    relatedSymptoms: ["always-bloated-after-eating", "why-do-i-have-nausea"],
  },
  "why-do-i-have-bad-breath": {
    slug: "why-do-i-have-bad-breath",
    title: { en: "Why Do I Have Bad Breath?", "zh-TW": "", ja: "" },
    metaTitle: "Bad Breath Won't Go Away? The Problem Might Be In Your Stomach",
    metaDesc: "Brushing and mouthwash but still can't fix it? Your body type might be why heat is cooking inside. Free quiz.",
    ogDesc: "Brushing and mouthwash but still can't shake the smell? Your body type may explain what's really going on.",
    h1: { en: "Why Do I Have Bad Breath? The Fire Down Below That Rises to the Top", "zh-TW": "", ja: "" },
    tag: "Oral",
    readTime: "8 min",
    relatedTypes: ["damp_heat"],
    relatedSymptoms: ["why-do-i-have-acid-reflux", "always-bloated-after-eating"],
  },
  "why-is-my-face-so-oily": {
    slug: "why-is-my-face-so-oily",
    title: { en: "Why Is My Face So Oily?", "zh-TW": "", ja: "" },
    metaTitle: "Oily Face by Noon? Internal Heat Might Be Pushing Oil Out",
    metaDesc: "Wash your face and it's oily again? Your body type might be why your skin acts like a grease factory. Free quiz.",
    ogDesc: "Wash your face and it's oily again an hour later? Your body type may explain why your skin produces too much oil.",
    h1: { en: "Why Is My Face So Oily? The Faucet That Won't Stop Dripping", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp", "damp_heat"],
    relatedSymptoms: ["why-do-i-keep-breaking-out", "why-is-my-skin-so-dry"],
  },
  "why-do-i-have-rosacea": {
    slug: "why-do-i-have-rosacea",
    title: { en: "Why Do I Have Rosacea?", "zh-TW": "", ja: "" },
    metaTitle: "Rosacea Won't Fade? Blood and Heat Might Be Trapped in Your Face",
    metaDesc: "Red flushed cheeks that won't go away? Your body type might be why heat collects in your face. Free quiz.",
    ogDesc: "Your cheeks flush red and nothing calms them down? Your body type may explain why rosacea keeps flaring up.",
    h1: { en: "Why Do I Have Rosacea? The Blush That Never Fades", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["damp_heat"],
    relatedSymptoms: ["why-do-i-keep-breaking-out", "why-is-my-face-so-oily"],
  },
  "why-do-i-have-brittle-nails": {
    slug: "why-do-i-have-brittle-nails",
    title: { en: "Why Do I Have Brittle Nails?", "zh-TW": "", ja: "" },
    metaTitle: "Brittle Nails? Your Blood Might Not Be Reaching the Edges",
    metaDesc: "Nails splitting and peeling no matter what? Your body type might be why nourishment can't reach your fingertips. Free quiz.",
    ogDesc: "Your nails snap like dry twigs no matter how much lotion you use? Your body type may explain why.",
    h1: { en: "Why Do I Have Brittle Nails? The Twigs at Your Fingertips", "zh-TW": "", ja: "" },
    tag: "Nails",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yin_deficient"],
    relatedSymptoms: ["why-is-my-hair-falling-out", "why-is-my-skin-so-dry"],
  },
  "why-is-my-complexion-dull": {
    slug: "why-is-my-complexion-dull",
    title: { en: "Why Is My Complexion Dull?", "zh-TW": "", ja: "" },
    metaTitle: "Dull Complexion? Your Glow Might Be Blocked From Within",
    metaDesc: "Face looks tired and gray even when you're not? Your body type might be why blood can't reach the surface. Free quiz.",
    ogDesc: "Your face looks tired even when you're not? Your body type may explain why your complexion lost its glow.",
    h1: { en: "Why Is My Complexion Dull? The Light Behind the Glass That Dimmed", "zh-TW": "", ja: "" },
    tag: "Skin",
    readTime: "8 min",
    relatedTypes: ["blood_stasis", "qi_deficient"],
    relatedSymptoms: ["why-do-i-have-dark-circles", "why-is-my-skin-so-dry"],
  },
  "why-do-i-have-cellulite": {
    slug: "why-do-i-have-cellulite",
    title: { en: "Why Do I Have Cellulite?", "zh-TW": "", ja: "" },
    metaTitle: "Stubborn Cellulite? Dampness Might Be Pooling Under Your Skin",
    metaDesc: "Cellulite that won't budge despite exercise? Your body type might be why moisture collects under the surface. Free quiz.",
    ogDesc: "Cellulite that won't budge no matter what you try? Your body type may explain why those dimples settled in.",
    h1: { en: "Why Do I Have Cellulite? The Dimples That Moved In and Stayed", "zh-TW": "", ja: "" },
    tag: "Body",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp"],
    relatedSymptoms: ["why-do-i-keep-gaining-weight", "why-do-i-have-water-retention"],
  },
  "why-do-i-have-neck-pain": {
    slug: "why-do-i-have-neck-pain",
    title: { en: "Why Do I Have Neck Pain?", "zh-TW": "", ja: "" },
    metaTitle: "Chronic Neck Pain? Stuck Energy Might Be Knotting Your Muscles",
    metaDesc: "Stiff neck that never relaxes? Your body type might be why tension keeps collecting there. Free quiz.",
    ogDesc: "Your neck feels like it's carrying the weight of the world? Your body type may explain why the tension lives there.",
    h1: { en: "Why Do I Have Neck Pain? The Pillar That Carries Too Much", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-have-headaches", "why-am-i-so-irritable"],
  },
  "why-are-my-shoulders-always-tense": {
    slug: "why-are-my-shoulders-always-tense",
    title: { en: "Why Are My Shoulders Always Tense?", "zh-TW": "", ja: "" },
    metaTitle: "Shoulders Always Tense? Stress Might Be Camping In Your Body",
    metaDesc: "Shoulders living up near your ears? Your body type might be why stress locks into your muscles. Free quiz.",
    ogDesc: "Your shoulders live somewhere near your ears? Your body type may explain why they never relax.",
    h1: { en: "Why Are My Shoulders Always Tense? The Earrings You Never Asked For", "zh-TW": "", ja: "" },
    tag: "Tension",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-do-i-have-neck-pain", "why-do-i-feel-anxious"],
  },
  "why-do-i-have-stomach-pain": {
    slug: "why-do-i-have-stomach-pain",
    title: { en: "Why Do I Have Stomach Pain?", "zh-TW": "", ja: "" },
    metaTitle: "Stomach Pain With No Clear Cause? Your Body Is Sending a Signal",
    metaDesc: "Stomach hurts but tests come back normal? Your body type might be why your gut keeps sounding alarms. Free quiz.",
    ogDesc: "Your stomach hurts but the doctor says everything looks fine? Your body type may explain the pain.",
    h1: { en: "Why Do I Have Stomach Pain? The Alarm Bell Nobody Can Find", "zh-TW": "", ja: "" },
    tag: "Pain",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant", "phlegm_damp"],
    relatedSymptoms: ["why-do-i-have-acid-reflux", "always-bloated-after-eating"],
  },
  "why-am-i-always-stiff": {
    slug: "why-am-i-always-stiff",
    title: { en: "Why Am I Always Stiff?", "zh-TW": "", ja: "" },
    metaTitle: "Always Stiff? Cold and Dampness Might Be Freezing Your Joints",
    metaDesc: "Body feels like concrete every morning? Your body type might be why your joints won't loosen up. Free quiz.",
    ogDesc: "Your body feels like it was poured from concrete overnight? Your body type may explain the stiffness.",
    h1: { en: "Why Am I Always Stiff? The Body That Forgot How to Bend", "zh-TW": "", ja: "" },
    tag: "Mobility",
    readTime: "8 min",
    relatedTypes: ["yang_deficient", "blood_stasis"],
    relatedSymptoms: ["why-am-i-always-cold", "why-do-i-have-joint-pain"],
  },
  "why-do-i-keep-forgetting-things": {
    slug: "why-do-i-keep-forgetting-things",
    title: { en: "Why Do I Keep Forgetting Things?", "zh-TW": "", ja: "" },
    metaTitle: "Keep Forgetting Things? Your Brain Might Not Be Getting Enough Fuel",
    metaDesc: "Walking into rooms and forgetting why? Your body type might be why your memory feels like a sieve. Free quiz.",
    ogDesc: "Your brain feels like a sieve lately? Your body type may explain why nothing sticks.",
    h1: { en: "Why Do I Keep Forgetting Things? The Sieve Between Your Ears", "zh-TW": "", ja: "" },
    tag: "Cognitive",
    readTime: "8 min",
    relatedTypes: ["qi_deficient", "yin_deficient"],
    relatedSymptoms: ["why-do-i-have-brain-fog", "why-am-i-always-tired"],
  },
  "why-cant-i-focus": {
    slug: "why-cant-i-focus",
    title: { en: "Why Can't I Focus?", "zh-TW": "", ja: "" },
    metaTitle: "Can't Focus? Dampness Might Be Fogging Your Mental Windshield",
    metaDesc: "Reading the same paragraph three times? Your body type might be why your attention keeps slipping. Free quiz.",
    ogDesc: "Reading the same paragraph three times? Your body type may explain why your attention keeps slipping.",
    h1: { en: "Why Can't I Focus? The Attention That Keeps Changing Channels", "zh-TW": "", ja: "" },
    tag: "Cognitive",
    readTime: "8 min",
    relatedTypes: ["qi_deficient"],
    relatedSymptoms: ["why-do-i-have-brain-fog", "why-do-i-keep-forgetting-things"],
  },
  "why-do-i-cry-so-easily": {
    slug: "why-do-i-cry-so-easily",
    title: { en: "Why Do I Cry So Easily?", "zh-TW": "", ja: "" },
    metaTitle: "Cry Too Easily? Your Heart's Energy Might Be Fragile and Overflowing",
    metaDesc: "Tears at commercials and small things? Your body type might be why your emotions spill over so fast. Free quiz.",
    ogDesc: "A sad commercial and you're reaching for tissues? Your body type may explain why your tear ducts are always on standby.",
    h1: { en: "Why Do I Cry So Easily? The Faucet With No Off Switch", "zh-TW": "", ja: "" },
    tag: "Emotional",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant", "qi_deficient"],
    relatedSymptoms: ["why-are-my-moods-all-over-the-place", "why-do-i-feel-anxious"],
  },
  "why-do-i-have-no-patience": {
    slug: "why-do-i-have-no-patience",
    title: { en: "Why Do I Have No Patience?", "zh-TW": "", ja: "" },
    metaTitle: "No Patience? Your Body Type Might Be Behind the Short Fuse",
    metaDesc: "Everything and everyone testing your patience? Your body type might be why you can't wait for anything. Free quiz.",
    ogDesc: "One more slow walker and you're going to lose it? Your body type may explain why your patience tank is always empty.",
    h1: { en: "Why Do I Have No Patience? The Fuse That's Always Short", "zh-TW": "", ja: "" },
    tag: "Emotional",
    readTime: "8 min",
    relatedTypes: ["qi_stagnant"],
    relatedSymptoms: ["why-am-i-so-irritable", "why-are-my-moods-all-over-the-place"],
  },
  "why-do-i-have-a-chronic-cough": {
    slug: "why-do-i-have-a-chronic-cough",
    title: { en: "Why Do I Have a Chronic Cough?", "zh-TW": "", ja: "" },
    metaTitle: "Chronic Cough Won't Stop? Your Lungs Might Be Dry and Irritated",
    metaDesc: "Coughing for weeks and nothing helps? Your body type might be why internal heat keeps your throat irritated. Free quiz.",
    ogDesc: "That cough just won't go away no matter what you try? Your body type may explain why it keeps coming back.",
    h1: { en: "Why Do I Have a Chronic Cough? The Tickles That Set Up Residence", "zh-TW": "", ja: "" },
    tag: "Respiratory",
    readTime: "8 min",
    relatedTypes: ["yin_deficient", "phlegm_damp"],
    relatedSymptoms: ["why-do-i-have-a-sore-throat", "why-do-i-have-post-nasal-drip"],
  },
  "why-do-i-always-have-a-sore-throat": {
    slug: "why-do-i-always-have-a-sore-throat",
    title: { en: "Why Do I Always Have a Sore Throat?", "zh-TW": "", ja: "" },
    metaTitle: "Sore Throat Keeps Coming Back? Internal Heat Might Be Burning Below",
    metaDesc: "Throat always scratchy or raw? Your body type might be why heat keeps rising to your throat. Free quiz.",
    ogDesc: "Your throat always feels scratchy or raw? Your body type may explain why it never fully heals.",
    h1: { en: "Why Do I Always Have a Sore Throat? The Fire in the Chimney", "zh-TW": "", ja: "" },
    tag: "Respiratory",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-have-a-chronic-cough", "why-am-i-always-thirsty"],
  },
  "why-do-i-have-post-nasal-drip": {
    slug: "why-do-i-have-post-nasal-drip",
    title: { en: "Why Do I Have Post-Nasal Drip?", "zh-TW": "", ja: "" },
    metaTitle: "Post-Nasal Drip? Dampness Might Be Dripping From Your Sinuses",
    metaDesc: "Always clearing your throat? Your body type might be why mucus keeps collecting in the back. Free quiz.",
    ogDesc: "Always clearing your throat or feeling something drip down the back? Your body type may explain why the drainage never stops.",
    h1: { en: "Why Do I Have Post-Nasal Drip? The Drip That Never Stops", "zh-TW": "", ja: "" },
    tag: "Respiratory",
    readTime: "8 min",
    relatedTypes: ["phlegm_damp"],
    relatedSymptoms: ["why-do-i-have-a-chronic-cough", "why-do-i-have-seasonal-allergies"],
  },
  "why-do-i-wake-up-to-pee": {
    slug: "why-do-i-wake-up-to-pee",
    title: { en: "Why Do I Wake Up to Pee?", "zh-TW": "", ja: "" },
    metaTitle: "Waking Up to Pee Every Night? Your Kidney's Water Gate Might Be Leaking",
    metaDesc: "Two, three times a night? Your body type might be why your bladder can't hold through the night. Free quiz.",
    ogDesc: "Two, three, four times a night? Your body type may explain why your bladder has a graveyard shift.",
    h1: { en: "Why Do I Wake Up to Pee? The Bladder's Night Shift", "zh-TW": "", ja: "" },
    tag: "Sleep",
    readTime: "8 min",
    relatedTypes: ["yang_deficient"],
    relatedSymptoms: ["why-do-i-wake-up-at-3am", "why-am-i-always-cold"],
  },
  "why-do-i-have-tinnitus": {
    slug: "why-do-i-have-tinnitus",
    title: { en: "Why Do I Have Tinnitus?", "zh-TW": "", ja: "" },
    metaTitle: "Ringing in Your Ears? Your Deepest Energy Might Be Too Low",
    metaDesc: "That buzzing nobody else can hear? Your body type might be why your ears won't go quiet. Free quiz.",
    ogDesc: "That high-pitched ringing that nobody else can hear? Your body type may explain why your ears won't go quiet.",
    h1: { en: "Why Do I Have Tinnitus? The Bell Nobody Else Can Hear", "zh-TW": "", ja: "" },
    tag: "Sensory",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-am-i-always-thirsty", "why-do-i-have-night-sweats"],
  },
  "why-am-i-so-sensitive-to-heat": {
    slug: "why-am-i-so-sensitive-to-heat",
    title: { en: "Why Am I So Sensitive to Heat?", "zh-TW": "", ja: "" },
    metaTitle: "Always Too Hot? Your Body's Cooling System Might Be Broken",
    metaDesc: "Everyone else is fine but you're melting? Your body type might be why your internal AC can't keep up. Free quiz.",
    ogDesc: "Everyone else is fine but you're melting? Your body type may explain why your internal AC is broken.",
    h1: { en: "Why Am I So Sensitive to Heat? The AC That Broke Down", "zh-TW": "", ja: "" },
    tag: "Temperature",
    readTime: "8 min",
    relatedTypes: ["yin_deficient"],
    relatedSymptoms: ["why-do-i-have-hot-flashes", "why-am-i-always-thirsty"],
  },
  "why-do-i-wake-up-tired": {
    slug: "why-do-i-wake-up-tired",
    title: { en: "Why Do I Wake Up Tired?", "zh-TW": "", ja: "" },
    metaTitle: "Wake Up Tired After 8 Hours? Your Body Might Not Be Recharging",
    metaDesc: "Slept all night but still feel drained? Your body type might be why rest doesn't equal recovery. Free quiz.",
    ogDesc: "You slept 8 hours and still feel like you didn't sleep at all? Your body type may explain why rest doesn't equal recovery.",
    h1: { en: "Why Do I Wake Up Tired? The Rest That Doesn't Restore", "zh-TW": "", ja: "" },
    tag: "Sleep",
    readTime: "8 min",
    relatedTypes: ["qi_deficient"],
    relatedSymptoms: ["why-am-i-always-tired", "why-do-i-have-brain-fog"],
  },
  "why-do-i-have-cold-sweats": {
    slug: "why-do-i-have-cold-sweats",
    title: { en: "Why Do I Have Cold Sweats?", "zh-TW": "", ja: "" },
    metaTitle: "Cold Sweats for No Reason? Your Body Might Be Leaking Warmth",
    metaDesc: "Sweating but feeling cold? Your body type might be why your body can't hold onto its own heat. Free quiz.",
    ogDesc: "Sweating but feeling cold at the same time? Your body type may explain why your sweat has a chill to it.",
    h1: { en: "Why Do I Have Cold Sweats? The Chill That Comes With the Drip", "zh-TW": "", ja: "" },
    tag: "Sweating",
    readTime: "8 min",
    relatedTypes: ["qi_deficient"],
    relatedSymptoms: ["why-do-i-sweat-so-much", "why-am-i-always-tired"],
  },
}

export const SYMPTOM_SLUGS = Object.keys(SYMPTOMS)
