from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

STYLE_BLOCK = """Style: warm wellness aesthetic, cream background (#FAF6F0),
gold accents (#C9A355), warm brown text (#2A1F14). Clean modern
infographic with subtle Chinese medicine heritage feel. Small
flat food illustrations beside key ingredients. Soft shadows, generous
whitespace, organized in clear sections. The footer URL should be
very small and unobtrusive at the bottom edge. Professional,
saveable, information-rich. All text in English only."""

FOOTER = 'Small footer at very bottom: "Discover your body type -> myeasterntype.com"'

# Each recipe: (series, title, subtitle, symptoms, tcm_explain, ingredients, steps, when_eat, timeline, link)
RECIPES = [

# ===== DIGESTION SERIES (6) =====

("Digestion",
 "Bloated After Every Meal?",
 "This Simple Porridge May Help Your Digestion",
 ["Bloating and fullness after eating",
  "Fatigue or heaviness after meals",
  "Loose stools or irregular digestion",
  "Sensitive stomach to cold or raw foods",
  "Poor appetite or feeling full quickly",
  "Recovering from stomach flu or food poisoning"],
 "Chinese medicine says your Spleen is too weak to process food efficiently. Millet porridge is the gentlest food to rebuild digestive strength.",
 [("1/2 cup Yellow Millet", "easy to find in Asian grocery stores"),
  ("4 cups Water", ""),
  ("Pinch of Salt", ""),
  ("Optional: 3 Red Dates", "for extra energy"),
  ("Optional: 2 slices Ginger", "for extra warmth")],
 ["Rinse millet under cold water 2-3 times until water runs clear",
  "Bring 4 cups of water to a boil in a pot",
  "Add rinsed millet, reduce heat to low",
  "Simmer uncovered for 20 minutes, stirring occasionally",
  "Add optional red dates and ginger after 10 minutes",
  "When it reaches a soft porridge consistency, add a pinch of salt",
  "Remove from heat and let cool slightly before eating"],
 ["As breakfast (7-9 AM is your Spleen's strongest time)",
  "Replace your heaviest meal with this for 3 days",
  "Eat warm, never cold"],
 ["First 3 days: less bloating after meals",
  "After 1 week: steadier energy throughout the day",
  "After 2-3 weeks: stronger digestion, better appetite",
  "Continue 2-3 times per week as maintenance"]),

("Digestion",
 "Acid Reflux and Heartburn?",
 "Cooling Mung Bean Soup to Calm Stomach Heat",
 ["Burning sensation in chest or stomach",
  "Sour taste rising up to throat",
  "Excessive hunger even after eating",
  "Bad breath that won't go away",
  "Mouth ulcers or canker sores",
  "Thirst for cold drinks"],
 "In Chinese medicine, this often means Stomach Heat. The digestive fire is burning too intensely. Mung beans are the strongest cooling food for this pattern.",
 [("1/2 cup dried Mung Beans", "found in Asian grocery stores"),
  ("3 cups Water", ""),
  ("Optional: Rock Sugar or Honey", "to taste"),
  ("Optional: Dried Tangerine Peel", "1 small piece for flavor")],
 ["Rinse mung beans and soak for 2 hours (or overnight)",
  "Drain and add to a pot with 3 cups of water",
  "Bring to a boil, then reduce to medium heat",
  "Simmer for 30-40 minutes until beans split open",
  "Add rock sugar or tangerine peel in last 10 minutes",
  "Strain the liquid for a clear soup, or blend for creamy texture",
  "Serve at room temperature or slightly warm"],
 ["As a light afternoon snack (2-4 PM)",
  "2-3 times per week during flare-ups",
  "Especially helpful in summer heat",
  "Avoid drinking it ice cold"],
 ["First 1-2 days: less burning and sour taste",
  "After 1 week: reduced reflux frequency",
  "After 2-3 weeks: fewer mouth ulcers, better breath",
  "Continue 1-2 times per week when symptoms return"]),

("Digestion",
 "Always Constipated?",
 "Black Sesame Paste to Moisten Your Intestines",
 ["Hard dry stools that are difficult to pass",
  "Going more than 2 days without bowel movement",
  "Straining with little result",
  "Dry skin and dry mouth alongside constipation",
  "Rabbit pellet shaped stools"],
 "In Chinese medicine, dry-type constipation means your intestines lack moisture. Black sesame seeds provide natural oils to lubricate the gut.",
 [("1/2 cup Black Sesame Seeds", "found in Asian grocery stores"),
  ("1 tbsp Honey", ""),
  ("1 cup Warm Water", ""),
  ("Optional: 2 tbsp Walnut Pieces", "for extra moisture")],
 ["Toast black sesame seeds in a dry pan for 3 minutes on low heat until fragrant",
  "Let cool, then grind into a fine powder using a blender or mortar",
  "Mix 2 tablespoons of the powder with warm water",
  "Add honey to taste and stir well",
  "Optional: add crushed walnuts on top",
  "Store remaining powder in an airtight jar in the fridge for up to 2 weeks"],
 ["First thing in the morning on an empty stomach",
  "Or 1 hour before bed",
  "Drink warm",
  "Daily for best results"],
 ["First 2-3 days: easier passage, less straining",
  "After 1 week: more regular pattern",
  "After 2 weeks: consistently softer stools",
  "Continue every other day for maintenance"]),

("Digestion",
 "Child Has Weak Digestion?",
 "Gentle Rice Congee with Chinese Yam to Strengthen Their Gut",
 ["Picky eater or low appetite",
  "Frequent stomach aches",
  "Loose stools or undigested food in stool",
  "Low energy compared to peers",
  "Catches colds easily",
  "Sweats easily during sleep"],
 "In Chinese medicine, children often have naturally weak Spleen energy. Rice congee with Chinese yam is the most gentle, time-tested food to strengthen a child's digestion.",
 [("1/2 cup White Rice", "jasmine or short grain"),
  ("5 cups Water", ""),
  ("3 slices Chinese Yam (Shan Yao)", "fresh or dried, found in Asian markets"),
  ("2 Red Dates", "pitted, for natural sweetness"),
  ("Pinch of Salt", "")],
 ["Rinse rice until water runs clear",
  "Peel and slice fresh Chinese yam into thin rounds (skip if using dried)",
  "Add rice, water, Chinese yam, and red dates to a pot",
  "Bring to a boil, then reduce to very low heat",
  "Simmer for 45-60 minutes, stirring occasionally to prevent sticking",
  "The congee is ready when it looks like a smooth, thick porridge",
  "Remove red date skins if your child prefers, add tiny pinch of salt",
  "Serve warm in small portions"],
 ["As breakfast or dinner",
  "Replace one regular meal per day for 1 week",
  "Small portions (half a bowl) are better than large ones",
  "Serve warm, never cold"],
 ["First 3-5 days: better appetite, less stomach aches",
  "After 1 week: more formed stools",
  "After 2-3 weeks: steadier energy, fewer colds",
  "Continue 2-3 times per week as the child grows"]),

("Digestion",
 "Stomach Pain After Eating?",
 "Warm Ginger Honey Water to Soothe Your Stomach",
 ["Dull or sharp pain in the upper abdomen after meals",
  "Nausea or queasiness after eating",
  "Feeling of cold or heaviness in the stomach",
  "Pain worse with cold drinks or raw foods",
  "Relief with warm food and warm compress"],
 "In Chinese medicine, cold and stagnation in the Stomach cause pain after eating. Warm ginger honey water gently restores the digestive fire and moves stuck energy.",
 [("1 thumb-sized piece Fresh Ginger", "about 2 inches"),
  ("1 tbsp Honey", "raw is best"),
  ("2 cups Water", ""),
  ("Optional: 2 Red Dates", "pitted, for extra warmth")],
 ["Wash ginger thoroughly (no need to peel) and slice into 5-6 thin pieces",
  "Add ginger slices and water to a small pot",
  "Optional: add 2 pitted red dates",
  "Bring to a boil, then simmer for 10 minutes",
  "Remove from heat and let cool for 2-3 minutes",
  "Strain into a cup and stir in honey (add honey when warm, not boiling hot)",
  "Sip slowly while warm"],
 ["30 minutes before meals to prepare the stomach",
  "Or immediately after eating if you feel discomfort",
  "First thing in the morning on an empty stomach is also effective",
  "Drink warm, never cold"],
 ["Same day: reduced stomach discomfort",
  "After 3 days: less nausea after meals",
  "After 1 week: steadier digestion with less pain",
  "Continue daily before heavy or cold meals"]),

("Digestion",
 "Diarrhea or Loose Stools?",
 "Scallion Ginger Rice Soup to Warm and Settle the Gut",
 ["Frequent loose or watery bowel movements",
  "Abdominal cramping or cold feeling in gut",
  "Urgent need to use bathroom after eating",
  "Feeling cold, especially in the abdomen",
  "Weakness or fatigue after bowel movements",
  "Symptoms worse after cold drinks or raw food"],
 "In Chinese medicine, diarrhea often means Cold has invaded the Spleen and Stomach. Scallion and ginger warm the digestive core, while rice settles the gut.",
 [("1/2 cup White Rice", "cooked or uncooked"),
  ("3 cups Water or Broth", ""),
  ("3 stalks Scallion (green onion)", "white parts only"),
  ("1 thumb-sized piece Ginger", "sliced thin"),
  ("Pinch of Salt", "")],
 ["If using uncooked rice, rinse first",
  "Slice ginger thin and chop scallion whites",
  "Add water (or broth), rice, and ginger to a pot",
  "Bring to a boil, then simmer for 20-30 minutes until very soft",
  "Add scallion whites in the last 5 minutes",
  "Add a pinch of salt to taste",
  "Serve warm and eat slowly"],
 ["As a meal replacement when diarrhea is active",
  "Eat small portions, 2-3 times throughout the day",
  "Best served very warm",
  "Avoid solid or cold foods until symptoms improve"],
 ["Same day: reduced urgency and cramping",
  "After 1-2 days: more formed stools",
  "After 3-5 days: digestion returns to normal",
  "Continue for 1 more day after symptoms stop"]),

# ===== WOMEN'S SERIES (6) =====

("Women's Health",
 "Period Cramps Every Month?",
 "Ginger Brown Sugar Tea to Warm and Ease the Pain",
 ["Lower abdominal cramps before or during period",
  "Pain that feels better with warmth",
  "Dark clots in menstrual blood",
  "Cold hands and feet during period",
  "Lower back ache during period",
  "Cravings for warm food and drinks"],
 "In Chinese medicine, period cramps often mean Cold and Stagnation in the uterus. Warmth moves the stuck Blood. Ginger brown sugar tea is the classic Chinese remedy passed down for generations.",
 [("1 thumb-sized piece Fresh Ginger", "about 2 inches"),
  ("2 tbsp Brown Sugar", "or dark brown sugar"),
  ("2 cups Water", ""),
  ("Optional: 3 Red Dates", "pitted, for extra warmth")],
 ["Slice ginger into 5-6 thin pieces (keep the skin on for extra warmth)",
  "Add ginger, water, and optional red dates to a pot",
  "Bring to a boil, then simmer for 10 minutes",
  "Add brown sugar and stir until dissolved",
  "Strain into a cup or thermos",
  "Sip slowly while warm"],
 ["Start drinking 2-3 days before your period is due",
  "Continue through the first 2-3 days of your period",
  "Drink 1-2 cups per day",
  "Best in the morning and before bed",
  "Always drink warm or hot, never cold"],
 ["Same day: reduced cramping intensity",
  "After 1 cycle: less clotting, smoother flow",
  "After 2-3 cycles: significantly reduced pain",
  "Make it a monthly ritual for ongoing relief"]),

("Women's Health",
 "Exhausted After Your Period?",
 "Red Date Longan Tea to Rebuild Blood and Energy",
 ["Extreme fatigue for several days after period",
  "Pale lips and complexion",
  "Dizziness or lightheadedness",
  "Dry skin and brittle nails",
  "Poor sleep despite feeling exhausted",
  "Difficulty concentrating"],
 "Your body just lost Blood. In Chinese medicine, Blood Deficiency after periods is extremely common. Red dates and longan are the two most powerful foods to rebuild what was lost.",
 [("6 dried Red Dates (Jujube)", ""),
  ("1 tbsp dried Longan Fruit", "found in Asian grocery stores"),
  ("2 cups Water", ""),
  ("Optional: 1 tsp Goji Berries", "for extra nourishment")],
 ["Slice each red date open and remove the pit",
  "Rinse longan and goji berries",
  "Add red dates, longan, and water to a pot",
  "Bring to a boil, then simmer for 15 minutes",
  "Add goji berries in the last 5 minutes",
  "Strain into a cup, or eat the fruits along with drinking",
  "Drink warm"],
 ["Start the day your period ends",
  "Drink daily for 5-7 days after your period",
  "Best in the morning and afternoon",
  "Avoid drinking at night (longan can be energizing)"],
 ["First 2-3 days: energy starts to return",
  "After 1 week: dizziness fades, color returns to face",
  "After 2-3 cycles: significantly stronger after each period",
  "Use after every period as a recovery ritual"]),

("Women's Health",
 "PMS Mood Swings Driving You Crazy?",
 "Rose Petal Tea to Move Stuck Energy and Lift Your Mood",
 ["Irritability and short temper before period",
  "Breast tenderness or swelling",
  "Feeling frustrated or stuck emotionally",
  "Sighing frequently",
  "Bloating that fluctuates with your mood",
  "Mood improves once period starts"],
 "In Chinese medicine, PMS mood swings often mean Liver Qi is stuck. Rose petals are the traditional remedy to move Liver energy and restore emotional flow.",
 [("1 tbsp dried Rose Buds", "found in tea shops or Asian markets"),
  ("2 cups Water", ""),
  ("Optional: 1 tsp Goji Berries", "for added nourishment"),
  ("Optional: 1 tsp Honey", "after brewing")],
 ["Rinse rose buds briefly under cold water",
  "Bring 2 cups of water to a near boil (about 90C or 195F)",
  "Add rose buds to a teapot or mug",
  "Pour hot water over the rose buds",
  "Cover and steep for 5 minutes",
  "Add goji berries and let steep 2 more minutes",
  "Strain and add honey if desired"],
 ["Start drinking 5 days before your period is due",
  "Drink 1-2 cups per day",
  "Best in the afternoon or early evening",
  "Continue through the first day of your period"],
 ["First 2-3 days: less irritability, calmer mood",
  "After 1 week: reduced breast tenderness",
  "After 2-3 cycles: noticeably smoother PMS",
  "Use each cycle for ongoing emotional balance"]),

("Women's Health",
 "Hot Flashes Keeping You Up?",
 "Mulberry Lotus Seed Soup to Cool and Calm from Within",
 ["Sudden waves of heat, especially afternoon and evening",
  "Night sweats that soak nightclothes",
  "Dry mouth and throat at night",
  "Difficulty falling back asleep after a flash",
  "Flushed cheeks and warm palms",
  "Irritability with the heat"],
 "In Chinese medicine, hot flashes mean Kidney Yin (your cooling reserve) is running low. Mulberries and lotus seeds are gentle foods that help rebuild cooling energy.",
 [("1/4 cup dried Mulberries", "found in Asian markets"),
  ("2 tbsp dried Lotus Seeds", "soaked for 2 hours"),
  ("3 cups Water", ""),
  ("Optional: Rock Sugar", "to taste")],
 ["Soak lotus seeds in warm water for 2 hours",
  "Rinse mulberries under cold water",
  "Add lotus seeds and water to a pot, bring to boil",
  "Simmer for 30 minutes until lotus seeds are tender",
  "Add mulberries and simmer 10 more minutes",
  "Add rock sugar to taste, stir until dissolved",
  "Serve warm or at room temperature"],
 ["Drink 1 bowl in the late afternoon or early evening",
  "2-3 times per week",
  "Avoid drinking too close to bedtime (lotus seeds may keep you alert)",
  "Continue through menopause transition"],
 ["First week: less frequent night sweats",
  "After 2 weeks: reduced afternoon hot flashes",
  "After 1 month: deeper, less interrupted sleep",
  "Continue 2 times per week for maintenance"]),

("Women's Health",
 "Irregular Periods?",
 "Black Bean Goji Tea to Support Your Hormonal Foundation",
 ["Periods that come early, late, or skip months",
  "Very light or very heavy flow",
  "Lower back ache around cycle time",
  "Feeling tired and cold between periods",
  "Difficulty tracking when your next period will come"],
 "In Chinese medicine, the Kidney governs reproduction and cycles. Black beans nourish the Kidney, and goji berries support Liver Blood. Together they address the root of irregularity.",
 [("1/3 cup Black Beans", ""),
  ("1 tbsp Goji Berries", ""),
  ("3 cups Water", ""),
  ("Optional: 3 Red Dates", "pitted")],
 ["Rinse black beans and soak for 4-6 hours or overnight",
  "Drain and add to a pot with 3 cups of water",
  "Add red dates if using",
  "Bring to a boil, then simmer for 45 minutes until beans are soft",
  "Add goji berries in the last 10 minutes",
  "Strain the liquid to drink as tea, or eat as a soup",
  "Drink warm"],
 ["Drink 2-3 times per week, consistently",
  "Best in the morning or early afternoon",
  "Continue throughout your entire cycle, not just during period",
  "Be patient, this works gradually"],
 ["After 2-3 weeks: more consistent energy",
  "After 1 cycle: cycle timing may start to stabilize",
  "After 2-3 cycles: more predictable periods",
  "Continue long-term for cycle regulation"]),

("Women's Health",
 "Menopause Discomfort?",
 "White Fungus Pear Soup to Moisturize and Cool from Within",
 ["Persistent dry skin and dry mouth",
  "Hot flashes and night sweats",
  "Dry cough or throat irritation",
  "Vaginal dryness",
  "Restless sleep with vivid dreams"],
 "In Chinese medicine, menopause is a natural decline of Yin, the body's cooling and moistening energy. White fungus deeply moisturizes from within, while pear cools internal heat.",
 [("1 small piece dried White Fungus", "about 10g, found in Asian markets"),
  ("1 Asian Pear", "or any sweet pear"),
  ("3 cups Water", ""),
  ("Optional: Rock Sugar", "to taste"),
  ("Optional: 1 tbsp Goji Berries", "")],
 ["Soak dried white fungus in warm water for 30 minutes until it expands",
  "Trim and discard the hard yellow base, tear into small pieces",
  "Peel pear, remove core, and cut into chunks",
  "Add white fungus, pear, and water to a pot",
  "Bring to a boil, then simmer for 45 minutes",
  "Add rock sugar and goji berries in last 10 minutes",
  "Serve warm as a sweet soup"],
 ["As a dessert or afternoon snack",
  "2-3 times per week",
  "Especially helpful during dry seasons",
  "Avoid on days with diarrhea or bloating"],
 ["First week: less dry mouth, better hydration",
  "After 2-3 weeks: skin feels more moisturized",
  "After 1 month: reduced hot flash intensity",
  "Continue 1-2 times per week long-term"]),

# ===== SLEEP & EMOTION SERIES (5) =====

("Sleep & Emotion",
 "Can't Fall Asleep at Night?",
 "Lily Bulb Lotus Seed Soup to Calm Your Racing Mind",
 ["Lying awake for 30+ minutes unable to sleep",
  "Racing thoughts when your head hits the pillow",
  "Vivid or disturbing dreams",
  "Waking unrefreshed even after 8 hours",
  "Heart palpitations or chest fluttering",
  "Anxiety that peaks at night"],
 "In Chinese medicine, insomnia with racing thoughts often means Heart Yin is too low to anchor the mind. Lily bulb and lotus seed are the two classic foods that calm the spirit and settle the heart.",
 [("20g dried Lily Bulb (Bai He)", "found in Asian pharmacies or markets"),
  ("2 tbsp dried Lotus Seeds", "soaked 2 hours"),
  ("3 cups Water", ""),
  ("Optional: Rock Sugar", "to taste")],
 ["Soak lotus seeds in warm water for 2 hours",
  "Rinse lily bulbs under cold water",
  "Add lotus seeds and water to a pot, bring to boil",
  "Simmer for 20 minutes",
  "Add lily bulbs and simmer 15 more minutes",
  "Add rock sugar to taste",
  "Serve warm in a small bowl"],
 ["Drink 1 small bowl 1 hour before bed",
  "4-5 times per week",
  "Best consumed warm",
  "Make a fresh batch every 2 days"],
 ["First 2-3 nights: mind feels calmer at bedtime",
  "After 1 week: falling asleep faster",
  "After 2-3 weeks: deeper sleep with fewer vivid dreams",
  "Continue 3 times per week for maintenance"]),

("Sleep & Emotion",
 "Waking Up at 3 AM Every Night?",
 "Chrysanthemum Goji Tea to Calm Your Liver and Sleep Through",
 ["Consistently waking between 1 and 3 AM",
  "Unable to fall back asleep for an hour or more",
  "Racing or angry thoughts when you wake",
  "Feeling warm or restless at night",
  "Dry eyes or blurry vision",
  "Tension headaches during the day"],
 "In the Chinese medicine body clock, 1-3 AM is Liver time. Waking then often means Liver Heat is disturbing your sleep. Chrysanthemum cools the Liver while goji berries nourish it.",
 [("1 tbsp dried Chrysanthemum Flowers", "found in tea shops or Asian markets"),
  ("1 tsp Goji Berries", ""),
  ("2 cups Water", ""),
  ("Optional: 1 tsp Honey", "after brewing")],
 ["Rinse chrysanthemum flowers and goji berries",
  "Bring water to a near boil (about 90C or 195F)",
  "Add chrysanthemum and goji to a teapot",
  "Pour hot water over them",
  "Cover and steep for 5 minutes",
  "Strain into a cup and add honey if desired",
  "Drink warm"],
 ["Drink 1 cup in the late afternoon (4-5 PM)",
  "Or early evening (6-7 PM)",
  "Do NOT drink right before bed (it may stimulate)",
  "Daily for 2-3 weeks"],
 ["First 3-5 days: less tension during the day",
  "After 1 week: fewer 3 AM wake-ups",
  "After 2-3 weeks: sleeping through the night",
  "Continue 3-4 times per week"]),

("Sleep & Emotion",
 "Anxious and Can't Calm Down?",
 "Rose and Lotus Calming Tea to Settle Your Mind",
 ["Persistent worry and overthinking",
  "Chest tightness or shallow breathing",
  "Difficulty being present in the moment",
  "Muscle tension in shoulders and jaw",
  "Digestive upset that worsens with stress",
  "Feeling overwhelmed by small tasks"],
 "In Chinese medicine, anxiety often means Liver Qi is stuck and Heart energy is restless. Rose moves the stuck energy, lotus seed settles the heart. Together they create calm.",
 [("1 tsp dried Rose Buds", ""),
  ("1 tbsp dried Lotus Seeds", "cooked and soft, or use lotus seed powder"),
  ("2 cups Water", ""),
  ("Optional: 3 Red Dates", "pitted"),
  ("Optional: 1 tsp Honey", "after brewing")],
 ["If using dried lotus seeds, simmer them in water for 30 minutes first until soft",
  "Add rose buds and red dates to a teapot",
  "Pour hot (not boiling) water over the rose and dates",
  "Steep for 5 minutes",
  "Strain, add the cooked lotus seeds to the cup",
  "Add honey to taste",
  "Sip slowly"],
 ["Drink in the late afternoon or early evening",
  "1-2 cups per day",
  "Especially helpful on stressful days",
  "Take 5 deep breaths before each sip"],
 ["Same day: reduced chest tightness",
  "After 3-5 days: less daily anxiety",
  "After 2 weeks: calmer baseline mood",
  "Continue 3-4 times per week as needed"]),

("Sleep & Emotion",
 "Night Sweats Soaking Your Sheets?",
 "Wheat Berry Tea to Cool the Night Heat",
 ["Waking up drenched in sweat around the chest and back",
  "Feeling hot from inside at night",
  "Restless, vivid dreams",
  "Dry mouth and throat when you wake",
  "Irritability and emotional sensitivity",
  "Sleep that doesn't feel restorative"],
 "In Chinese medicine, night sweats mean the body's cooling system (Yin) is too low to hold heat down at night. Wheat, specifically 'floating wheat,' is the traditional Chinese remedy for this exact symptom.",
 [("1/3 cup Whole Wheat Berries", "or organic wheat grains"),
  ("3 cups Water", ""),
  ("Optional: 5 Red Dates", "pitted"),
  ("Optional: 1 tsp Goji Berries", "")],
 ["Rinse wheat berries under cold water",
  "Toast in a dry pan for 3 minutes on medium heat until fragrant",
  "Add toasted wheat, water, and red dates to a pot",
  "Bring to a boil, then simmer for 30 minutes",
  "Add goji berries in last 5 minutes",
  "Strain the liquid to drink as tea",
  "Drink warm"],
 ["Drink 1 cup in the evening (6-7 PM)",
  "1 hour before bed is ideal",
  "Daily for 2-3 weeks",
  "Store leftover tea in the fridge for up to 2 days"],
 ["First 3-5 nights: reduced sweating intensity",
  "After 1 week: fewer episodes, drier sleep",
  "After 2-3 weeks: significantly less night sweating",
  "Continue 3 times per week for maintenance"]),

("Sleep & Emotion",
 "Always Irritable and Frustrated?",
 "Celery Mint Cooler to Release Tension and Cool the Head",
 ["Short temper that flares quickly",
  "Feeling of pressure or tightness in the chest",
  "Frequent sighing",
  "Headaches on the sides of your head",
  "Bloating that comes and goes with mood",
  "Bitter taste in mouth, especially morning"],
 "In Chinese medicine, chronic irritability means Liver Qi is stuck and converting to Liver Fire. Celery moves energy downward, mint cools and releases tension. Together they clear the heat of frustration.",
 [("2 stalks Fresh Celery", ""),
  ("1 handful Fresh Mint Leaves", ""),
  ("2 cups Water", ""),
  ("Optional: 1 tsp Honey", ""),
  ("Optional: squeeze of Lemon", "")],
 ["Wash celery and mint thoroughly",
  "Chop celery into small pieces",
  "Add celery and water to a pot, bring to boil",
  "Simmer for 10 minutes",
  "Remove from heat, add fresh mint leaves",
  "Let steep for 5 minutes",
  "Strain, add honey and lemon to taste",
  "Serve warm or at room temperature"],
 ["Drink in the mid-morning or afternoon",
  "1-2 cups per day on stressful days",
  "Avoid drinking too late in the evening",
  "Best when you feel tension building"],
 ["Same day: reduced head pressure and irritability",
  "After 3-5 days: fewer tension headaches",
  "After 2 weeks: steadier mood baseline",
  "Use as needed on stressful days"]),

# ===== ENERGY SERIES (5) =====

("Energy",
 "Tired Even After 8 Hours Sleep?",
 "Red Date Goji Chicken Broth to Rebuild Your Core Energy",
 ["Chronic fatigue that sleep doesn't fix",
  "Weak voice or reluctance to speak",
  "Sweating with minimal exertion",
  "Pale complexion",
  "Frequent colds (more than 3 per year)",
  "Heavy, tired feeling after eating"],
 "In Chinese medicine, deep tiredness means your Qi (core energy) is depleted. Chicken broth with red dates and goji berries is the most nourishing food combination to rebuild from within.",
 [("2 Chicken Thighs or Bones", "bone-in for richer broth"),
  ("6 Red Dates (Jujube)", "pitted"),
  ("1 tbsp Goji Berries", ""),
  ("3 slices Fresh Ginger", ""),
  ("4 cups Water", ""),
  ("Pinch of Salt", "")],
 ["Rinse chicken and place in a pot with water",
  "Add ginger slices and bring to a boil",
  "Skim off any foam that rises to the top",
  "Reduce heat to low and add red dates",
  "Simmer gently for 60-90 minutes",
  "Add goji berries in last 10 minutes",
  "Add salt to taste",
  "Strain broth or serve with chicken pieces"],
 ["Drink 1 bowl as lunch or early dinner",
  "3-4 times per week",
  "Best in cooler months",
  "Sip slowly, chewing the dates and goji berries"],
 ["First week: morning energy starts to improve",
  "After 2-3 weeks: noticeably less fatigue",
  "After 1 month: stronger voice, fewer colds",
  "Continue 2 times per week as maintenance"]),

("Energy",
 "Afternoon Energy Crash?",
 "Sweet Potato Ginger Soup for Steady Afternoon Energy",
 ["Energy drops sharply between 2-4 PM",
  "Craving sugar or coffee in the afternoon",
  "Brain fog and difficulty concentrating after lunch",
  "Mood dips in late afternoon",
  "Need a nap to get through the day"],
 "In Chinese medicine, afternoon crashes mean your Spleen is struggling to sustain energy. Sweet potato provides steady fuel while ginger keeps the digestive fire going.",
 [("1 medium Sweet Potato", "peeled and cubed"),
  ("3 slices Fresh Ginger", ""),
  ("3 cups Water", ""),
  ("Optional: 2 tbsp Rock Sugar", "or brown sugar"),
  ("Optional: 3 Red Dates", "pitted")],
 ["Peel sweet potato and cut into bite-sized chunks",
  "Add sweet potato, ginger, red dates, and water to a pot",
  "Bring to a boil, then simmer for 20 minutes",
  "When sweet potato is soft, add rock sugar",
  "Stir until sugar dissolves",
  "Serve warm as a sweet soup"],
 ["Eat as a mid-morning snack (10-11 AM) to prevent the crash",
  "Or eat at the first sign of afternoon dip (2 PM)",
  "3-4 times per week",
  "Eat warm"],
 ["Same day: no afternoon energy crash",
  "After 1 week: steadier energy curve throughout the day",
  "After 2-3 weeks: reduced sugar and coffee cravings",
  "Continue 2-3 times per week"]),

("Energy",
 "Always Cold Hands and Feet?",
 "Cinnamon Walnut Milk to Warm from the Core",
 ["Cold hands and feet year-round",
  "Pale complexion and lips",
  "Frequent urination at night",
  "Lower back ache that feels cold",
  "Desire for warm food and drinks",
  "Low energy, move slowly"],
 "In Chinese medicine, always being cold means your internal furnace (Kidney Yang) is underpowered. Cinnamon warms the core, walnuts strengthen the Kidney. This warm milk delivers both.",
 [("1 cup Milk", "dairy or plant-based"),
  ("2 tbsp Walnuts", "crushed"),
  ("1/4 tsp Cinnamon Powder", "or 1 small cinnamon stick"),
  ("1 tsp Honey", "or brown sugar"),
  ("Optional: tiny pinch of Salt", "enhances sweetness")],
 ["Crush walnuts into rough pieces",
  "Add milk, walnuts, and cinnamon to a small pot",
  "Heat gently on low for 5 minutes (do not boil)",
  "Stir in honey and optional salt",
  "If using a cinnamon stick, remove before serving",
  "Pour into a mug and drink warm",
  "Optional: blend for a smoother texture"],
 ["Drink in the morning (7-9 AM)",
  "Or as an afternoon warming drink",
  "Daily during cold months",
  "Avoid at night (may be too warming for sleep)"],
 ["First 2-3 days: warmth spreads through the body",
  "After 1 week: warmer hands and feet",
  "After 2-3 weeks: less cold sensitivity overall",
  "Continue daily in winter, reduce in summer"]),

("Energy",
 "Brain Fog Can't Focus?",
 "Walnut Black Sesame Drink to Nourish Your Mind",
 ["Difficulty concentrating and thinking clearly",
  "Forgetfulness and scattered thoughts",
  "Heavy feeling in the head",
  "Tired eyes after reading or screen time",
  "Slow mental processing"],
 "In Chinese medicine, the brain is nourished by Kidney essence. Walnuts look like brains for a reason. Black sesame nourishes the Kidney and Blood. Together they are the classic brain food combo.",
 [("2 tbsp Walnuts", ""),
  ("1 tbsp Black Sesame Seeds", ""),
  ("1 cup Warm Water or Milk", ""),
  ("1 tsp Honey", ""),
  ("Optional: 2 Red Dates", "pitted, soaked soft")],
 ["Toast black sesame seeds in a dry pan for 3 minutes on low heat",
  "Toast walnuts for 2 minutes separately",
  "Let cool, then blend walnuts, sesame, and dates with warm water",
  "Blend until smooth and creamy",
  "Strain if you prefer a smoother drink",
  "Add honey to taste",
  "Serve warm"],
 ["Drink in the morning before work or study",
  "Or as a mid-afternoon brain boost (3 PM)",
  "3-4 times per week",
  "Drink warm"],
 ["First week: improved morning focus",
  "After 2 weeks: less brain fog after meals",
  "After 1 month: sharper memory and concentration",
  "Continue 2-3 times per week"]),

("Energy",
 "Low Libido and Back Ache?",
 "Chestnut Lamb Stew to Warm and Strengthen the Kidney",
 ["Lower back ache and knee weakness",
  "Feeling cold, especially in the lower body",
  "Low energy and low motivation",
  "Frequent clear urination at night",
  "Hair thinning or premature graying",
  "Reduced sexual desire"],
 "In Chinese medicine, lower back pain and low libido point to Kidney Yang deficiency. Lamb is the most warming meat, chestnuts warm the Kidney. This stew has been used for centuries to rebuild deep vitality.",
 [("200g Lamb", "bone-in or boneless, cut in chunks"),
  ("10 Chestnuts", "peeled (fresh or vacuum-packed)"),
  ("3 slices Ginger", ""),
  ("2 Red Dates", "pitted"),
  ("3 cups Water", ""),
  ("1 tbsp Soy Sauce", "optional"),
  ("Pinch of Salt", "")],
 ["Blanch lamb in boiling water for 2 minutes, then drain and rinse",
  "This removes impurities and strong odor",
  "Add lamb, ginger, water, and red dates to a clean pot",
  "Bring to a boil, then simmer for 60 minutes",
  "Add chestnuts and soy sauce, simmer 30 more minutes",
  "Add salt to taste",
  "Serve warm with rice or on its own"],
 ["Eat as a main meal, once or twice per week",
  "Best in autumn and winter",
  "Lunch is better than dinner (easier to digest)",
  "Avoid in hot summer months"],
 ["First week: warmer feeling in lower back",
  "After 2 weeks: more energy and warmth",
  "After 1 month: stronger lower back and knees",
  "Continue weekly during cold season"]),

# ===== SKIN & BEAUTY SERIES (4) =====

("Skin & Beauty",
 "Acne That Won't Go Away?",
 "Mung Bean Licorice Tea to Clear Skin from Within",
 ["Persistent breakouts, especially around mouth and chin",
  "Oily skin and enlarged pores",
  "Red, inflamed, or cystic acne",
  "Worsens with spicy, fried, or sweet foods",
  "Bad breath or bitter taste in mouth"],
 "In Chinese medicine, acne is often Damp-Heat rising to the face. The skin reflects internal heat. Mung beans clear heat, licorice root reduces inflammation. Together they address the root.",
 [("1/3 cup dried Mung Beans", ""),
  ("3-4 slices dried Licorice Root", "found in Chinese herbal shops, or omit"),
  ("3 cups Water", ""),
  ("Optional: Rock Sugar", "to taste")],
 ["Rinse mung beans and soak for 1 hour",
  "Add mung beans, licorice root, and water to a pot",
  "Bring to a boil, then simmer for 30 minutes",
  "Add rock sugar in last 5 minutes",
  "Strain the liquid to drink as tea",
  "Serve warm or at room temperature"],
 ["Drink 1 cup daily in the afternoon",
  "5 days per week, then rest 2 days",
  "Continue for 3-4 weeks",
  "Reduce dairy, fried food, and excess sugar during this time"],
 ["First week: less new breakouts",
  "After 2 weeks: reduced redness and oiliness",
  "After 3-4 weeks: clearer skin overall",
  "Continue 2-3 times per week for prevention"]),

("Skin & Beauty",
 "Dry Dull Skin in Winter?",
 "Snow Fungus Papaya Soup to Moisturize from Inside Out",
 ["Dry, flaky, or tight feeling skin",
  "Dull complexion lacking radiance",
  "Dry lips and throat",
  "Fine lines more visible in cold weather",
  "Skin not improving with topical products"],
 "In Chinese medicine, dry skin means Body Fluids and Yin are low. Snow fungus is known as the 'poor man's bird's nest' for its deeply moisturizing properties. Papaya aids absorption and adds natural sweetness.",
 [("1 small piece dried White Fungus", "about 10g"),
  ("1/2 Ripe Papaya", "peeled and cubed"),
  ("3 cups Water", ""),
  ("Optional: Rock Sugar", "to taste"),
  ("Optional: 1 tbsp Goji Berries", "")],
 ["Soak dried white fungus in warm water for 30 minutes until expanded",
  "Trim the hard yellow base, tear into small florets",
  "Add white fungus and water to a pot",
  "Bring to a boil, then simmer for 45 minutes",
  "Add papaya cubes, goji berries, and sugar",
  "Simmer 15 more minutes until papaya is soft",
  "Serve warm as a sweet dessert soup"],
 ["Eat as a daily dessert or afternoon snack",
  "3-4 times per week",
  "Best in autumn and winter",
  "Eat warm for best absorption"],
 ["First week: lips and throat feel less dry",
  "After 2 weeks: skin feels more supple",
  "After 1 month: visible improvement in skin radiance",
  "Continue 2 times per week for maintenance"]),

("Skin & Beauty",
 "Puffy Face Every Morning?",
 "Adzuki Bean Winter Melon Soup to Drain Overnight Swelling",
 ["Puffy face and eyes when you wake up",
  "Rings feel tight on fingers in the morning",
  "Heavy, bloated feeling throughout the body",
  "Weight fluctuates day to day from water",
  "Indentation marks from socks or waistband"],
 "In Chinese medicine, morning puffiness means your body is holding dampness overnight. Adzuki beans are the strongest damp-draining food. Winter melon promotes fluid metabolism. This soup drains excess water.",
 [("1/3 cup Adzuki Beans", ""),
  ("200g Winter Melon", "peeled and cubed, or substitute zucchini"),
  ("4 cups Water", ""),
  ("Pinch of Salt", "")],
 ["Rinse adzuki beans and soak for 2-4 hours",
  "Add beans and water to a pot, bring to boil",
  "Simmer for 30 minutes until beans start to soften",
  "Add winter melon cubes, simmer 15 more minutes",
  "Add a pinch of salt",
  "Serve as a light soup"],
 ["Eat for dinner (at least 3 hours before bed)",
  "2-3 times per week",
  "Avoid eating right before sleep",
  "Also reduce salt and alcohol intake"],
 ["Next morning: visibly less puffiness",
  "After 1 week: consistently less water retention",
  "After 2-3 weeks: lighter feeling in the body",
  "Use 1-2 times per week for maintenance"]),

("Skin & Beauty",
 "Hair Falling Out More Than Usual?",
 "Black Sesame Walnut Paste to Nourish Hair from the Root",
 ["More hair in the shower drain or brush",
  "Hair feeling thinner or weaker",
  "Dry, brittle hair lacking shine",
  "Pale or dry scalp",
  "Accompanied by tiredness or dizziness"],
 "In Chinese medicine, hair is governed by the Kidney and nourished by Blood. Black sesame and walnuts are the two most powerful foods for Kidney essence and Blood. This paste delivers both in concentrated form.",
 [("3 tbsp Black Sesame Seeds", ""),
  ("2 tbsp Walnuts", ""),
  ("1 tbsp Black Beans", "dry roasted, optional"),
  ("1 cup Warm Water or Milk", ""),
  ("1 tsp Honey", "")],
 ["Toast black sesame seeds in a dry pan on low heat for 3-4 minutes until fragrant",
  "Toast walnuts separately for 2-3 minutes",
  "Optional: dry roast black beans until they crack open",
  "Let everything cool completely",
  "Grind into a fine powder using a blender",
  "Store in an airtight jar in the fridge for up to 2 weeks",
  "To serve: mix 2 tablespoons of powder with warm water or milk, add honey"],
 ["Drink every morning before breakfast",
  "Daily for 3-4 weeks",
  "Best on an empty stomach",
  "Drink warm"],
 ["After 2 weeks: less hair shedding in shower",
  "After 1 month: hair feels stronger and shinier",
  "After 2-3 months: visible improvement in hair volume",
  "Continue 3-4 times per week long-term"]),

# ===== SEASONAL & DAILY SERIES (4) =====

("Seasonal & Daily",
 "Catch Every Cold Going Around?",
 "Scallion White Ginger Soup to Strengthen Your Defenses",
 ["Catching colds 3 or more times per year",
  "Colds that linger for weeks",
  "Sneezing and runny nose at the start of every cold",
  "Weak voice and low energy",
  "Feeling chilly and wanting warm drinks",
  "Slow recovery from illness"],
 "In Chinese medicine, frequent colds mean your Wei Qi (defensive energy) is weak. The Lung produces this shield. Scallion whites and ginger are the first-line Chinese remedies to release cold and strengthen defense at the first sign of illness.",
 [("3 stalks Scallion", "use the white parts only"),
  ("1 thumb-sized piece Fresh Ginger", "sliced"),
  ("2 cups Water", ""),
  ("Optional: 1 tsp Brown Sugar", "")],
 ["Cut scallion whites into 2-inch pieces",
  "Slice ginger into thin pieces",
  "Add scallion whites, ginger, and water to a pot",
  "Bring to a boil, then simmer for just 5 minutes (do not overcook)",
  "Add brown sugar if desired",
  "Strain and drink immediately while very warm",
  "Best drunk while wrapping yourself in a blanket"],
 ["At the very first sign of a cold (sneezing, chill, scratchy throat)",
  "Drink 1-2 cups and go straight to bed",
  "Sweat slightly under blankets",
  "Not for daily use, only at onset of illness"],
 ["If caught early: cold may resolve within 24 hours",
  "If cold has set in: reduces duration and severity",
  "Use at every cold onset to strengthen pattern",
  "Combine with rest and warm food for best results"]),

("Seasonal & Daily",
 "Always Thirsty with Dry Mouth?",
 "Pear Lotus Root Tea to Hydrate from Within",
 ["Persistent thirst that water doesn't fix",
  "Dry mouth and throat, especially at night",
  "Dry cough without phlegm",
  "Skin feeling dry and tight",
  "Constipation from internal dryness"],
 "In Chinese medicine, thirst that water alone can't fix means your Body Fluids are depleted. Pear and lotus root are both moistening foods that hydrate from within, beyond what drinking water can do.",
 [("1 Asian Pear", "or any sweet pear"),
  ("1 small section Lotus Root", "about 100g, or use lotus root powder"),
  ("3 cups Water", ""),
  ("Optional: Rock Sugar or Honey", "to taste")],
 ["Peel pear and cut into chunks",
  "Peel lotus root and slice thin (if using powder, add later)",
  "Add pear chunks, lotus root slices, and water to a pot",
  "Bring to a boil, then simmer for 20 minutes",
  "If using lotus root powder: mix 1 tbsp with cold water first, then stir into the hot tea",
  "Add rock sugar or honey to taste",
  "Strain and drink warm, or eat as a light soup"],
 ["Drink throughout the day, especially in dry seasons",
  "2-3 cups per day when thirsty",
  "Best in autumn and winter",
  "Drink warm or at room temperature"],
 ["Same day: reduced thirst and dry mouth",
  "After 3-5 days: skin feels more hydrated",
  "After 1-2 weeks: dry cough improves",
  "Continue in dry seasons as needed"]),

("Seasonal & Daily",
 "Allergies Every Spring?",
 "Chrysanthemum Mint Tea to Clear Your Head and Reduce Reactivity",
 ["Sneezing and itchy eyes every spring",
  "Runny nose with clear discharge",
  "Foggy head and difficulty concentrating",
  "Scratchy or sore throat during allergy season",
  "Symptoms worse outdoors and in wind"],
 "In Chinese medicine, seasonal allergies mean your Lung's defensive shield is weak and Wind-Heat is invading. Chrysanthemum clears heat from the head and eyes, mint opens the sinuses. This tea is gentle enough for daily allergy season use.",
 [("1 tbsp dried Chrysanthemum Flowers", ""),
  ("1 tsp dried Mint Leaves", "or 5 fresh leaves"),
  ("2 cups Water", ""),
  ("Optional: 1 tsp Honey", "after brewing")],
 ["Rinse chrysanthemum and mint briefly",
  "Bring water to a near boil (about 90C)",
  "Add chrysanthemum and mint to a teapot or mug",
  "Pour hot water over the herbs",
  "Cover and steep for 5 minutes",
  "Strain and add honey if desired",
  "Inhale the steam before drinking for sinus relief"],
 ["Drink 2-3 cups per day during allergy season",
  "Morning and afternoon are best",
  "Use daily for 2-3 weeks during peak pollen",
  "Reduce to 1 cup as symptoms improve"],
 ["First 2-3 days: less sneezing and itchiness",
  "After 1 week: clearer head, less congestion",
  "After 2-3 weeks: reduced reactivity to pollen",
  "Use each allergy season for prevention"]),

("Seasonal & Daily",
 "Gaining Weight Without Eating More?",
 "Adzuki Coix Seed Water to Drain Dampness and Support Metabolism",
 ["Weight slowly increasing despite normal eating",
  "Feeling heavy and sluggish in the body",
  "Sticky or sluggish bowel movements",
  "Puffy face and body, especially in humidity",
  "Difficult to lose weight even with exercise",
  "Craving sweets and heavy foods"],
 "In Chinese medicine, stubborn weight is often dampness, not just fat. A weak Spleen creates sticky deposits that the body holds onto. Adzuki beans and coix seed are the two most powerful damp-draining foods. This daily water helps your body process and release excess fluid.",
 [("1/3 cup Adzuki Beans", ""),
  ("1/3 cup Coix Seed (Job's Tears)", "found in Asian markets"),
  ("4 cups Water", "")],
 ["Rinse adzuki beans and coix seed",
  "Soak both together for 2-4 hours (or overnight)",
  "Drain and add to a pot with 4 cups of fresh water",
  "Bring to a boil, then simmer for 45-60 minutes",
  "The water will turn reddish-brown",
  "Strain the liquid into a thermos",
  "You can eat the beans as a side dish or discard them",
  "Drink the liquid throughout the day"],
 ["Drink 2-3 cups of the water throughout the day",
  "Replace some of your regular water intake",
  "Daily for 2-3 weeks, then take 1 week off",
  "Especially effective in humid weather",
  "Reduce dairy, sugar, and cold drinks during this time"],
 ["First week: lighter feeling, less puffiness",
  "After 2 weeks: 1-2 pounds may release (water weight)",
  "After 1 month: steadier digestion and less bloating",
  "Continue 3-4 days per week as a habit"]),
]

# ===== GENERATE DOCUMENT =====

doc = Document()

# Set default font
style = doc.styles['Normal']
font = style.font
font.name = 'Calibri'
font.size = Pt(11)

# Title page
title = doc.add_heading('Pinterest Pin Prompts — Chinese Medicine Recipe Cards', level=0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

subtitle = doc.add_paragraph()
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = subtitle.add_run('30 Symptom-Driven Natural Remedy Recipe Cards\nProblem → Remedy → Steps → When → Timeline')
run.font.size = Pt(14)
run.font.color.rgb = RGBColor(0xC9, 0xA3, 0x55)

doc.add_paragraph()

# Style guide
doc.add_heading('Unified Style Guide (Applies to All 30 Pins)', level=1)

items = [
    ('Image Size', '1000x1500px (2:3 vertical ratio)'),
    ('Color Palette', 'Cream background (#FAF6F0), Gold accents (#C9A355), Warm brown text (#2A1F14)'),
    ('Font', 'Playfair Display (serif) for titles, clean sans-serif for body'),
    ('Style Keywords', 'Warm wellness aesthetic, subtle Chinese medicine heritage feel, small flat food illustrations beside key ingredients, soft shadows, generous whitespace, organized in clear sections'),
    ('Footer', 'Very small, unobtrusive text at bottom edge: "Discover your body type -> myeasterntype.com"'),
    ('Language', 'All text in English only. No Chinese characters on images.'),
    ('Card Structure', 'Problem (symptoms) → Explanation → Ingredients → Steps → When to eat → Timeline'),
]
for label, value in items:
    p = doc.add_paragraph()
    p.add_run(f'{label}: ').bold = True
    p.add_run(value)

doc.add_page_break()

# Table of contents
doc.add_heading('Contents', level=1)
series_counts = {}
for r in RECIPES:
    series = r[0]
    series_counts[series] = series_counts.get(series, 0) + 1

for series, count in series_counts.items():
    doc.add_paragraph(f'{series} ({count} recipes)', style='List Number')

doc.add_page_break()

# Generate each recipe
current_series = ""
for idx, recipe in enumerate(RECIPES):
    series, title_text, subtitle_text, symptoms, tcm_explain, ingredients, steps, when_eat, timeline = recipe
    pin_num = idx + 1

    # Series heading
    if series != current_series:
        current_series = series
        doc.add_heading(series, level=1)

    # Pin heading
    doc.add_heading(f'Pin #{pin_num}: {title_text}', level=2)

    # Build full prompt
    lines = []
    lines.append('Create a vertical Pinterest infographic (1000x1500px, 2:3 ratio)')
    lines.append(f'about a Chinese medicine natural remedy: {subtitle_text.lower()}.')
    lines.append('')
    lines.append(f'Title in elegant serif font: "{title_text}"')
    lines.append(f'Subtitle in smaller text: "{subtitle_text}"')
    lines.append('')

    # Symptoms section
    lines.append('Section 1 — heading "IF YOU EXPERIENCE":')
    for s in symptoms:
        lines.append(f'- {s}')
    lines.append('')
    lines.append(f'Then text: "{tcm_explain}"')
    lines.append('')

    # Ingredients
    lines.append('Section 2 — heading "WHAT YOU NEED":')
    for ing in ingredients:
        if len(ing) == 2 and ing[1]:
            lines.append(f'- {ing[0]} — {ing[1]}')
        else:
            lines.append(f'- {ing[0]}')
    lines.append('')

    # Steps
    lines.append('Section 3 — heading "HOW TO MAKE IT":')
    for i, step in enumerate(steps, 1):
        lines.append(f'{i}. {step}')
    lines.append('')

    # When to eat
    lines.append('Section 4 — heading "WHEN TO EAT/DRINK IT":')
    for w in when_eat:
        lines.append(f'- {w}')
    lines.append('')

    # Timeline
    lines.append('Section 5 — heading "HOW LONG UNTIL YOU FEEL BETTER":')
    for t in timeline:
        lines.append(f'- {t}')
    lines.append('')

    # Footer
    lines.append(FOOTER)
    lines.append('')
    lines.append(STYLE_BLOCK)

    full_prompt = '\n'.join(lines)

    # Add to document
    p = doc.add_paragraph()
    run = p.add_run(full_prompt)
    run.font.name = 'Consolas'
    run.font.size = Pt(10)

    doc.add_paragraph('---')
    doc.add_paragraph()

# Save
import os
output_path = os.path.join(os.getcwd(), 'Pinterest_Recipe_Prompts_30.docx')
doc.save(output_path)
print(f'Document saved: {output_path}')
print(f'Total recipes: {len(RECIPES)}')
print(f'Series breakdown:')
for s, c in series_counts.items():
    print(f'  {s}: {c}')
